---
title: "Cross-linguistic comparison of the voicing effect"
author: "Stefano Coretta"
date: "10/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_minimal())
library(brms)
library(tidybayes)
library(coretta2018itapol)
data("token_measures")
library(coretta2019eng)
data("eng_durations")
```

```{r merge-data}
ita_pol <- token_measures %>%
  select(language, speaker, word, c2_phonation, v1_duration, c2_clos_duration, speech_rate) %>%
  rename(voicing = "c2_phonation")

eng <- eng_durations %>%
  filter(num_syl == "di") %>%
  mutate(language = "English") %>%
  select(language, speaker, word, voicing, v1_duration, c2_clos_duration, speech_rate) %>%
  mutate_if(is.factor, as.character)

enitpl <- bind_rows(eng, ita_pol) %>%
  mutate(
    language = factor(language, levels = c("English", "Italian", "Polish")),
    voicing = factor(voicing, levels = c("voiceless", "voiced")),
    speech_rate_c = scale(speech_rate),
    vc_ratio = v1_duration / c2_clos_duration
  ) %>%
  mutate_if(is.character, as.factor) %>%
  na.omit()
```

# V1 duration

```{r v1-dur}
enitpl %>%
  ggplot(aes(voicing, v1_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r brm-1}
priors <- c(
  prior(normal(145, 30), class = Intercept),
  prior(normal(0, 50), class = b, coef = languageItalian),
  prior(normal(0, 50), class = b, coef = languagePolish),
  prior(normal(25, 10), class = b, coef = voicingvoiced),
  prior(normal(0, 10), class = b, coef = languageItalian:voicingvoiced),
  prior(normal(0, 10), class = b, coef = languagePolish:voicingvoiced),
  prior(normal(-25, 10), class = b, coef = speech_rate_c),
  prior(cauchy(0, 25), class = sd),
  prior(lkj(2), class = cor),
  prior(cauchy(0, 25), class = sigma)
)

brm_1 <- brm(
  v1_duration ~
    language +
    voicing +
    language:voicing +
    speech_rate_c +
    (voicing | speaker) +
    (voicing | word),
  data = enitpl,
  family = gaussian(),
  prior = priors,
  file = "cross-ling/analysis/cache/brm_1",
  cores = 4,
  control = list(adapt_delta = 0.999, max_treedepth = 15)
)
```

```{r brm-2}
priors <- c(
  prior(normal(145, 30), class = Intercept),
  prior(normal(0, 50), class = b, coef = languageItalian),
  prior(normal(0, 50), class = b, coef = languagePolish),
  prior(normal(25, 10), class = b, coef = voicingvoiced),
  prior(normal(0, 10), class = b, coef = languageItalian:voicingvoiced),
  prior(normal(0, 10), class = b, coef = languagePolish:voicingvoiced),
  prior(normal(-25, 10), class = b, coef = speech_rate_c),
  prior(cauchy(0, 25), class = sd),
  prior(lkj(2), class = cor),
  prior(cauchy(0, 25), class = sigma)
)

brm_2 <- brm(
  v1_duration ~
    language +
    voicing +
    language:voicing +
    speech_rate_c +
    (voicing | speaker) +
    (1 | word),
  data = enitpl,
  family = gaussian(),
  prior = priors,
  file = "cross-ling/analysis/cache/brm_2",
  cores = 4,
  control = list(adapt_delta = 0.999, max_treedepth = 15),
  seed = 1532
)
```

```{r brm-2-summary}
summary(brm_2)
```

```{r brm-2-draws}
brm_2_draws <- brm_2 %>%
  gather_draws(`b_.*`, regex = TRUE) %>%
  filter(.variable != "b_Intercept")
```

```{r brm-2-intervals}
brm_2_draws %>%
  ungroup() %>%
  mutate(.variable = factor(.variable, levels = c("b_voicingvoiced", "b_languageItalian", "b_languagePolish", "b_languageItalian:voicingvoiced", "b_languagePolish:voicingvoiced", "b_speech_rate_c")[6:1])) %>%
  ggplot(aes(.value, .variable)) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(position = position_nudge(y = -0.15), .width = c(0.66, 0.98)) +
  scale_color_brewer()
```

# VC ratio

```{r vc-ratio}
enitpl %>%
  ggplot(aes(voicing, vc_ratio)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r vc-ratio-2}
enitpl %>%
  ggplot(aes(speech_rate, vc_ratio)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "gam") +
  facet_grid(voicing ~ language)
```
