---
title: "Pre-registration for Compensatory aspects of the effect of voicing on vowel duration in English"
author: "Stefano Coretta"
date: "20/12/2018"
output:
  pdf_document:
    citation_package: natbib
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
bibliography: linguistics.bib
biblio-style: unified.bst
mainfont: DejaVu Sans
fontsize: 11pt
header-includes:
- \usepackage{cleveref}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Study information

## Title

Compensatory aspects of the effect of voicing on vowel duration in English.

## Authorship

Stefano Coretta (The University of Manchester).

## Research questions

Vowel in English (and many more languages) are longer when followed by voiced stops than when followed by voiceless stops \citep{heffner1937}.
The origin of this 'voicing effect' is still object to debate.
According to the compensatory temporal adjustment account, the difference in vowel duration is the consequence of the difference in stop closure durations \citep{lindblom1967, slis1969a, slis1969, lehiste1970, lehiste1970a}.
Voiceless stops have longer closures than voiced stops \citep{lisker1957, van-summers1987, davis1989, de-jong1991}, so that vowels are longer when followed by the shorter closure durations of voiced stops.

An exploratory study by Coretta (submitted) indicates that the duration of the interval between two consecutive stops releases is not affected by consonant voicing in CV́CV words in Italian and Polish.
Coretta argues that the temporal stability of the release to release interval plus the difference in consonant closure durations drives differences in vowel durations by a mechanism of compensation between the duration of the vowel and that of the closure.

This study sets out to test whether English exhibits the same temporal pattern found in Italian and Polish.
The aim of the study is to answer the following questions:

* Q1: Is the duration of the interval between two consecutive stop releases (the release to release interval) in monosyllabic and disyllabic words affected by the voicing of C2 in English?
* Q2: Is the duration of the release to release interval affected by (a) the number of syllables of the word, (b) the quality of the V1, and (c) the place of C2?

## Hypotheses

In relation to Q1, the following hypotheses will be tested:

* H1a: The duration of the release to release interval is not affected by C2 voicing in disyllabic words.
* H1b: The release to release interval is longer in monosyllabic words with a voiced C2 than in monosyllabic words with a voiceless C2.

# Sampling plan

## Existing data

**Registration prior to creation of data**: As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realised.

## Explanation of existing data

NA.

## Data collection procedures

### Participants

Inclusion rule: Native speakers of English from the Manchester area, 18+ yo, with no reported hearing or speaking disorders, and with normal or corrected to normal vision.

### Procedure
\label{s:procedure}

The participants will be recorded while reading sentences with CVC and CV́CVC target words presented on a computer screen with PsychoPy [@peirce2009], in a sound attenuated room in the Phonetics Laboratory at the University of Manchester.
The test words are C\textsubscript{1}V\textsubscript{1}C\textsubscript{2}(VC) words, where C\textsubscript{1} = /t/, V\textsubscript{1} = /iː, əː, ɑː/, C\textsubscript{2} = /p, b, k, g/, and (VC) = /əs/.
This structure leads to 24 possible combinations.

\begin{tabular}{lll}
teep & teepus & teek & teekus \\
teeb & teebus & teeg & teegus \\
terp & terpus & terk & terkus \\
terb & terbus & terg & tergus \\
tarp & tarpus & tark & tarkus \\
tarb & tarbus & targ & targus \\
\end{tabular}

Each target word is combined with the following frame sentences: I'll say X this Thursday, You'll say X this Monday, She'll say X this Sunday, We'll say X this Friday, They'll say X this Tuesday.
Each word/frame combination will be read once.
Acoustic recording will be obtained with a Zoom H4n Pro recorder and a RØDE Lavalier microphone, at a sample rate of 44100 Hz (16-bit; downsampled to 22050 Hz for analysis).
The recordings will be subject to force alignment with SPPAS [@bigi2015] for analysis in Praat [@boersma2018].

## Sample size

24 words, 5 repetitions (= 120 tokens per participant).
We set a minimum of 20 participants with additional participants if needed (see following sections).

## Sample size rationale

The approach of the region of practical equivalence (ROPE) will be used for determining the participant sample size \citep{kruschke2015, vasishth2018a}.
This approach is based on establishing a region around 0 which could theoretically be interpreted as a 'no effect' region.
Based on estimates from the literature on the just noticeable difference \citep{huggins1972, nooteboom1980}, the chosen ROPE width is 20 milliseconds (from -10 to +10 milliseconds).

## Stopping rule

Data collection will stop either:

(a) When the width of the 95\% CI of the effect of C2 voicing will be less than 20 milliseconds, or
(b) If the ROPE target hasn't been reached by April 30th 2019, due to time constraints imposed on the project.

# Variables

## Manipulated variables
\label{s:manipulated}

* **Vowel**: /iː/, /əː/, /ɑː/.
* **Voicing of C2**: voiceless (/p, k/), voiced (/b, g/).
* **Place of articulation of C2**: labial (/p, b/), velar (/k, g/).
* **Number of syllables**: monosyllabic, disyllabic.
* **Frame sentence**: I'll say X this Thursday, You'll say X this Monday, She'll say X this Sunday, We'll say X this Friday, They'll say X this Tuesday.

See \Cref{s:procedure} for a list of word stimuli.

## Measured variables

* From the acoustic signal:
    * **Duration of the release to release interval**: from the release of C1 to the release of C2.
    * **V1 duration**: from appearance to disappearance of higher formant structure in the spectrogram in correspondence of V1 \citep{machac2009}.
    * **C2 closure duration**: from disappearance of higher formant structure in the V1C2 sequence to the release of C2 \citep{machac2009}.
    * **Speech rate**: calculated as number of syllables per second [`n of syllables in the sentence / sentence duration`, @plug2018].

## Indices

NA.

# Design plan

## Study type

Experiment---A researcher randomly assigns treatments to study subjects, this includes field or lab experiments.
This is also known as an intervention experiment and includes randomised controlled trials.

## Blinding

No blinding is involved in this study.

## Study design

Repeated measures, mixed design.

## Randomisation

The sentence stimuli will be randomised within participant by means of the built-in randomisation procedure in PsychoPy \citep{peirce2009}.

# Analysis plan

## Statistical models
\label{s:stats}


## Transformations

NA.

## Follow-up analyses

NA.

## Inference criteria


## Data exclusion


## Missing data

NA.

## Exploratory analysis


# Script (Optional)

## Analysis scripts (Optional)

See \Cref{s:stats}.

# Other
\label{s:other}

NA.
