---
title: "Gesture durations"
author: "Stefano Coretta"
date: "09/08/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(rticulate)
```

```{r read-data, message=FALSE}
columns <- c(
  "speaker",
  "seconds",
  "rec_date",
  "prompt",
  "label",
  "TT_displacement_sm",
  "TT_velocity",
  "TT_velocity_abs",
  "TD_displacement_sm",
  "TD_velocity",
  "TD_velocity_abs",
  "TR_displacement_sm",
  "TR_velocity",
  "TR_velocity_abs"
)

speakers <- read_csv("./italian-polish/data/datasets/speakers.csv")
stimuli <- read_csv("./italian-polish/data/datasets/stimuli.csv")

gestures <- list.files(
  path = "./italian-polish/data/datasets/ultrasound",
  pattern = "*-tongue-cart.tsv",
  full.names = TRUE
) %>%
  read_aaa(., columns, format = "wide") %>%
  select(-(X_1:Y_42), -(TT_displacement_sm:TR_velocity_abs)) %>%
  filter(label %in% c("NONS_TT", "NONS_TD", "NOFF_TT", "NOFF_TD")) %>%
  separate(label, c("gesture", "tongue.area")) %>%
  spread(gesture, seconds) %>%
  mutate(nucleus = (NOFF - NONS) * 1000, word = word(prompt, 2)) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate(c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))) %>%
  mutate_if(is.character, as.factor)
```

```{r}
gestures %>%
  ggplot(aes(nucleus, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r}
gestures %>%
  ggplot(aes(c2_phonation, nucleus)) +
  geom_boxplot()
```

```{r}
gestures %>%
  filter(nucleus < 35) %>%
  ggplot(aes(nucleus, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r}
gestures %>%
  filter(nucleus < 35) %>%
  ggplot(aes(c2_phonation, nucleus)) +
  geom_boxplot()
```

```{r}
gestures %>%
  filter(nucleus < 35) %>%
  ggplot(aes(c2_phonation, nucleus, fill = c2_phonation)) +
  geom_boxplot() +
  geom_jitter(width = 0.2, alpha = 0.1) +
  facet_grid(. ~ c2_place)
```
