---
title: "UTI FPCA"
author: "Stefano Coretta"
date: "31/05/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_light())
library(tidymv)
library(rticulate)
library(itsadug)
library(beepr)
library(fda)
library(coretta2018itapol)
data("tongue_contours")
```

# Data import

```{r read-data, message=FALSE}
it01 <- filter(tongue_contours, speaker == "it01", label == "closure_") %>%
  arrange(rec_date, fan_line) %>%
  mutate(
    contour = as.numeric(as.factor(rec_date))
  ) %>%
  transform_coord(use_XY = TRUE)
```

# Cartesian vs. Polar plotting

```{r}
tongue %>%
  filter(speaker == "it01", label == "closure_", X < 40) %>%
  ggplot(aes(X, Y, group = rec_date, colour = c2_phonation)) +
  geom_path() +
  coord_fixed(ratio = 1) +
  facet_grid(c2_place ~ vowel) +
  theme(legend.position = "none")
```

```{r}
it01 %>%
  filter(c2_place == "coronal", label == "closure_", X < 40) %>%
  ggplot(aes(X, Y, group = rec_date, colour = rec_date)) +
  geom_path() +
  facet_wrap(~vowel) +
  theme(legend.position = "none")
```

```{r}
it01 %>%
  filter(c2_place == "coronal", label == "closure_", X < 40) %>%
  ggplot(aes(X, Y, group = rec_date, colour = rec_date)) +
  geom_point() +
  facet_wrap(~vowel) +
  theme(legend.position = "none")
```

# FPCA

```{r}
it01_filtered <- filter(it01, X > 4.5, X < 5.5)
```

```{r}
it01_filtered %>%
  filter(c2_place == "coronal", label == "closure_", X < 40) %>%
  ggplot(aes(X, Y, group = rec_date, colour = rec_date)) +
  geom_point() +
  facet_wrap(~vowel) +
  theme(legend.position = "none")
```

```{r}
n_curves <- 117

X <- split(it01_filtered$X, it01_filtered$contour)
Y <- split(it01_filtered$Y, it01_filtered$contour)
```

```{r smoothing}
n_knots = 8 # try many
lambda = 1e-8 # try many; smoothness penalty

#knots <- seq(0,mean_dur,length.out = n_knots)
lfd_obj <- 3 # 2 + order of derivative expected to be used. We might need velocity, thus order = 1
n_order <- 2 + lfd_obj  # a fixed relation about B-splines
n_basis <- n_knots + n_order - 2 # a fixed relation about B-splines
basis <- create.bspline.basis(c(min(it01_filtered$X), max(it01_filtered$X)), n_basis, n_order) #, knots)

fd_par <- fdPar(basis, lfd_obj, lambda)
```

```{r}
i = 5
# t_norm = (time_list[[i]] / duration[i]) * mean_dur # linear time normalisation
curve_fd = smooth.basis(X[[i]], Y[[i]], fd_par)$fd

# plot
plot(
  X[[i]],
  Y[[i]],
  col = "red",
  las = 1,
  main = paste('curve',i,', n_knots =',n_knots,'lambda =',lambda)
)
lines(curve_fd, lwd = 2)
```

```{r}
y_coefs = matrix(nrow = n_basis, ncol = n_curves)

for (i in 1:n_curves) {
  y_coefs[,i] = c(smooth.basis(X[[i]],Y[[i]], fd_par)$fd$coefs)
}
y_fd = fd(coef = y_coefs, basisobj = basis)
```

```{r fpca}
lambda_pca <- lambda
pcafd_par  <- fdPar(basis, 2, lambda_pca) # here Lfdobj = 2 since we don't need derivatives of PC curves.
y_pcafd <- pca.fd(y_fd, nharm = 4, pcafd_par) # compute first 4 PCs
```

```{r}
par(mfrow = c(2,2))
plot.pca.fd(y_pcafd, nx = 40)
```

```{r}
it01_contour <- it01_filtered %>%
  select(-X, -Y, -fan_line) %>%
  unique()

scores <- as.tibble(y_pcafd$scores) %>%
  cbind(it01_contour)
```

```{r}
ggplot(scores, aes(V1, V3, colour = c2_place, shape = vowel)) +
  geom_point()
ggplot(scores, aes(V1, V2, colour = c2_place, shape = vowel)) +
  geom_point()
ggplot(scores, aes(V2, V3, colour = c2_place, shape = vowel)) +
  geom_point()
ggplot(scores, aes(V2, V3, colour = c2_phonation, shape = vowel)) +
  geom_point()
ggplot(scores, aes(V3, V4, colour = c2_phonation, shape = vowel)) +
  geom_point()
```

```{r}
ggplot(scores, aes(contour, V1, fill = c2_place)) +
  geom_bar(stat = "identity")
```

```{r}
ggplot(scores, aes(contour, V3, fill = vowel)) +
  geom_bar(stat = "identity")
```

```{r}
ggplot(scores, aes(contour, V3, fill = c2_phonation)) +
  geom_bar(stat = "identity")
```
