---
title: "Ultrafest"
author: "Stefano Coretta"
date: "03/04/2017"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath("../../"))
library(readr)
library(purrr)
library(tidyr)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
library(gss)
library(stringr)
library(lme4)
library(afex)
library(effects)
library(gamm4)
library(mgcv)
library(itsadug)
```

# Data

```{r read}
num.splines <- 42
first.columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
    )
columns <- c(first.columns,
             paste0(rep(c("X", "Y"), num.splines),
                    "_",
                    rep(1:num.splines, each = 2)
                    )
             )

splines.raw <- list.files(path = "./pilot/results",
                   pattern = "*-aaa.csv",
                   full.names = TRUE) %>%
    map_df(~read.delim(., col.names = columns, na.strings = "*"))

splines.closure.raw <- list.files(path = "./pilot/results",
                   pattern = "*-closure.csv",
                   full.names = TRUE) %>%
    map_df(~read.delim(., col.names = columns, na.strings = "*"))

splines.phantom.raw <- list.files(path = "./pilot/results",
                   pattern = "*-phantom.csv",
                   full.names = TRUE) %>%
    map_df(~read_tsv(., col_names = columns, na = "*"))

rm(num.splines, first.columns, columns)

languages <- read_csv("./pilot/stimuli/languages.csv")
words <- read_csv("./pilot/stimuli/nonce.csv")
```


```{r tidy}
splines <- splines.raw %>%
    gather(spline, coordinate, matches("[XY]_")) %>%
    separate(spline, c("axis", "fan"), convert = TRUE) %>%
    spread(axis, coordinate) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)

splines.it <- filter(splines, language == "italian")
splines.pl <- filter(splines, language == "polish")

splines.closure <- splines.closure.raw %>%
    gather(spline, coordinate, matches("[XY]_")) %>%
    separate(spline, c("axis", "fan"), convert = TRUE) %>%
    spread(axis, coordinate) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)

splines.closure.it <- filter(splines.closure, language == "italian")
splines.closure.pl <- filter(splines.closure, language == "polish")
```

# Italian

## Plot at maximum constriction

```{r group-coronal-it}
filter(splines.it, label == "max_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r group-velar-it}
filter(splines.it, label == "max_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r coronal-it}
filter(splines.it, label == "max_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r velar-it}
filter(splines.it, label == "max_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

## Plot at peak 1

```{r p1-group-coronal-it}
filter(splines.it, label == "peak1_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r p1-group-velar-it}
filter(splines.it, label == "peak1_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r p1-coronal-it}
filter(splines.it, label == "peak1_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r p1-velar-it}
filter(splines.it, label == "peak1_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

## Plot at closure

```{r closure-group-coronal-it}
filter(splines.closure.it, c2place == "coronal") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r closure-group-velar-it}
filter(splines.closure.it, c2place == "velar") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r closure-coronal-it}
filter(splines.closure.it, c2place == "coronal") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r closure-velar-it}
filter(splines.closure.it, c2place == "velar") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

## GAMMs at maximum constriction

```{r max-it}
splines.it$c2phonation.ord <- as.ordered(splines.it$c2phonation)
splines.it$c2place.ord <- as.ordered(splines.it$c2place)
splines.it$vowel.ord <- as.ordered(splines.it$vowel)
contrasts(splines.it$c2phonation.ord) <- "contr.treatment"
contrasts(splines.it$c2place.ord) <- "contr.treatment"
contrasts(splines.it$vowel.ord) <- "contr.treatment"
max.it <- filter(splines.it, label %in% c("max_TT", "max_TD")) %>%
    na.omit() %>%
    arrange(rec.date, fan)

previous <- ""
for (i in 1:nrow(max.it)) {
    if (max.it$rec.date[i] != previous) {
        max.it$start.event[i] <- TRUE
        previous <- max.it$rec.date[i]
    } else {
        max.it$start.event[i] <- FALSE
        previous <- max.it$rec.date[i]
    }
}
```


```{r max-it-gam}
max.it.gam <- bam(
    Y ~
        c2phonation.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr"),
    data = max.it,
    method = "ML"
)

summary(max.it.gam)

max.it.gam.null <- bam(
    Y ~
        s(X, bs = "cr"),
    data = max.it,
    method = "ML"
)

compareML(max.it.gam, max.it.gam.null)
```

```{r max-it-gam-plot}
plot_smooth(max.it.gam, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.it.gam, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r max-it-gam-acf}
acf_plot(resid(max.it.gam), split_by=list(max.it$rec.date))
```

```{r max-it-gam-2}
max.it.gam.2 <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.it,
    method = "fREML"
)

summary(max.it.gam.2)

max.it.gam.null <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr"),
    data = max.it,
    method = "fREML"
)

compareML(max.it.gam.2, max.it.gam.null)
```

```{r max-it-gam-2-plot}
plot_smooth(max.it.gam.2, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.it.gam.2, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r max-it-gam-2-acf}
acf_plot(resid(max.it.gam.2), split_by=list(max.it$rec.date))
```

```{r max-it-gamm}
max.it.gamm <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.it,
    method = "fREML"
)

summary(max.it.gamm)

max.it.gam.null <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.it,
    method = "fREML"
)

compareML(max.it.gamm, max.it.gam.null)
```

```{r max-it-gamm-plot}
plot_smooth(max.it.gamm, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.it.gamm, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r max-it-gamm-acf}
acf_plot(resid(max.it.gamm), split_by=list(max.it$rec.date))
```

### AR1 model

```{r max-it-gam-ar}
r1 <- start_value_rho(max.it.gamm, plot = TRUE)

max.it.gam.AR <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.it,
    method = "fREML",
    rho = r1,
    AR.start = max.it$start.event
)

summary(max.it.gam.AR)
```

```{r max-it-gam-ar-acf}
acf_plot(resid(max.it.gam.AR), split_by=list(max.it$rec.date))
acf_resid(max.it.gam.AR, split_pred = "AR.start")
```

```{r max-it-gam-ar-plot}
plot_smooth(max.it.gam.AR, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.it.gam.AR, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

## GAMMs at closure

```{r closure-it}
splines.closure.it$c2phonation.ord <- as.ordered(splines.closure.it$c2phonation)
splines.closure.it$c2place.ord <- as.ordered(splines.closure.it$c2place)
splines.closure.it$vowel.ord <- as.ordered(splines.closure.it$vowel)
contrasts(splines.closure.it$c2phonation.ord) <- "contr.treatment"
contrasts(splines.closure.it$c2place.ord) <- "contr.treatment"
contrasts(splines.closure.it$vowel.ord) <- "contr.treatment"
closure.it <- splines.closure.it %>%
    na.omit() %>%
    arrange(rec.date, fan) %>%
    start_event(column = "fan", event = c("rec.date"))
```


```{r closure-it-gam}
closure.it.gam <- bam(
    Y ~
        c2phonation.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr"),
    data = closure.it,
    method = "ML"
)

summary(closure.it.gam)

closure.it.gam.null <- bam(
    Y ~
        s(X, bs = "cr"),
    data = closure.it,
    method = "ML"
)

compareML(closure.it.gam, closure.it.gam.null)
```

```{r closure-it-gam-plot}
plot_smooth(closure.it.gam, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(closure.it.gam, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r closure-it-gam-acf}
acf_plot(resid(closure.it.gam), split_by=list(closure.it$rec.date))
```

```{r closure-it-gam-2}
closure.it.gam.2 <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = closure.it,
    method = "fREML"
)

summary(closure.it.gam.2)

closure.it.gam.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = closure.it,
    method = "fREML"
)

compareML(closure.it.gam.2, closure.it.gam.null)
```

```{r closure-it-gam-2-plot}
plot_smooth(closure.it.gam.2, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(closure.it.gam.2, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r closure-it-gam-2-acf}
acf_plot(resid(closure.it.gam.2), split_by=list(closure.it$rec.date))
```

```{r closure-it-gamm}
closure.it.gamm <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = closure.it,
    method = "fREML"
)

summary(closure.it.gamm)

closure.it.gamm.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = closure.it,
    method = "fREML"
)

compareML(closure.it.gamm, closure.it.gamm.null)
AIC(closure.it.gamm, closure.it.gamm.null)
```

```{r closure-it-gamm-plot}
plot_smooth(closure.it.gamm, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(closure.it.gamm, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r closure-it-gamm-acf}
acf_plot(resid(closure.it.gamm), split_by=list(closure.it$rec.date))
```

### AR1 model

```{r closure-it-gam-ar}
r1 <- start_value_rho(closure.it.gamm)

closure.it.gam.AR <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = closure.it,
    method = "fREML",
    rho = r1,
    AR.start = closure.it$start.event
)

summary(closure.it.gam.AR)
```

```{r closure-it-gam-ar-comparison}
closure.it.gam.AR.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = closure.it,
    method = "fREML",
    rho = r1,
    AR.start = closure.it$start.event
)

compareML(closure.it.gam.AR, closure.it.gam.AR.null)
```

```{r closure-it-gam-ar-acf}
acf_plot(resid(closure.it.gam.AR), split_by=list(closure.it$rec.date))
acf_resid(closure.it.gam.AR, split_pred = "AR.start")
```

```{r closure-it-gam-ar-plot}
plot_smooth(closure.it.gam.AR, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(closure.it.gam.AR, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```


## GAMMs at peak 1

```{r p1-it-gam}
splines.it$c2phonation.ord <- as.ordered(splines.it$c2phonation)
contrasts(splines.it$c2phonation.ord) <- "contr.treatment"
peak.it <- filter(splines.it, label %in% c("peak1_TT", "peak1_TD"))

peak.it.gam <- bam(
    Y ~
        c2phonation.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr"),
    data = peak.it,
    method = "ML"
)

summary(peak.it.gam)

peak.it.gam.null <- bam(
    Y ~
        s(X, bs = "cr"),
    data = peak.it,
    method = "ML"
)

compareML(peak.it.gam, peak.it.gam.null)
```

```{r p1-it-gam-plot}
plot_smooth(peak.it.gam, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(peak.it.gam, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

# Polish

## Plot at maximum constriction

```{r group-coronal-pl}
filter(splines.pl, label == "max_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r group-velar-pl}
filter(splines.pl, label == "max_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r coronal-pl}
filter(splines.pl, label == "max_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r velar-pl}
filter(splines.pl, label == "max_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

## Plot at peak 1

```{r p1-group-coronal-pl}
filter(splines.pl, label == "peak1_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r p1-group-velar-pl}
filter(splines.pl, label == "peak1_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r p1-coronal-pl}
filter(splines.pl, label == "peak1_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r p1-velar-pl}
filter(splines.pl, label == "peak1_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

## Plot at closure

```{r closure-group-coronal-pl}
filter(splines.closure.pl, c2place == "coronal") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1.5) +
    facet_grid(speaker ~ vowel)
```

```{r closure-group-velar-pl}
filter(splines.closure.pl, c2place == "velar") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r closure-coronal-pl}
filter(splines.closure.pl, c2place == "coronal") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

```{r closure-velar-pl}
filter(splines.closure.pl, c2place == "velar") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess") +
    coord_fixed(ratio = 1) +
    facet_grid(speaker ~ vowel)
```

## GAMMs at maximum constriction

```{r max-pl}
splines.pl$c2phonation.ord <- as.ordered(splines.pl$c2phonation)
splines.pl$c2place.ord <- as.ordered(splines.pl$c2place)
splines.pl$vowel.ord <- as.ordered(splines.pl$vowel)
contrasts(splines.pl$c2phonation.ord) <- "contr.treatment"
contrasts(splines.pl$c2place.ord) <- "contr.treatment"
contrasts(splines.pl$vowel.ord) <- "contr.treatment"
max.pl <- filter(splines.pl, label %in% c("max_TT", "max_TD")) %>%
    na.omit()
```


```{r max-pl-gam}
max.pl.gam <- bam(
    Y ~
        c2phonation.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr"),
    data = max.pl,
    method = "ML"
)

summary(max.pl.gam)

max.pl.gam.null <- bam(
    Y ~
        s(X, bs = "cr"),
    data = max.pl,
    method = "ML"
)

compareML(max.pl.gam, max.pl.gam.null)
```

```{r max-pl-gam-plot}
plot_smooth(max.pl.gam, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.pl.gam, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r max-pl-gam-2}
max.pl.gam.2 <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.pl,
    method = "fREML"
)

summary(max.pl.gam.2)

max.pl.gam.null <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, by = c2place.ord, bs = "cr"),
    data = max.pl,
    method = "fREML"
)

compareML(max.pl.gam.2, max.pl.gam.null)
```

```{r max-pl-gam-2-plot}
plot_smooth(max.pl.gam.2, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.pl.gam.2, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```

```{r max-pl-gamm}
max.pl.gamm <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.pl,
    method = "fREML"
)

summary(max.pl.gamm)

max.pl.gam.null <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.pl,
    method = "fREML"
)

compareML(max.pl.gamm, max.pl.gam.null)
```

```{r max-pl-gamm-plot}
plot_smooth(max.pl.gamm, view = "X",
            plot_all= "c2phonation.ord", rug = FALSE)
plot_diff(max.pl.gamm, view = "X",
          comp = list(c2phonation.ord = c("voiceless", "voiced")))
```
