---
title: "Tracegram pilot"
author: "Stefano Coretta"
date: "22 December 2017"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: readable
  pdf_document: 
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_bw())
library(lmerTest)
library(effects)
```

# Data import

```{r data}
degg_tracing <- read_csv("./tracegram-pilot/results/results.csv") %>%
    separate(file, c("speaker", "phonation")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(phonation = factor(phonation, levels = c("modal", "breathy"))) %>%
    gather(peak, value, degg_maximum:degg_minimum)

degg_tracing_norm <- read_csv("./tracegram-pilot/results/results.csv") %>%
    separate(file, c("speaker", "phonation")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(phonation = factor(phonation, levels = c("modal", "breathy"))) %>%
    gather(peak, value, degg_maximum:degg_minimum) %>%
    group_by(speaker) %>%
    mutate(value_norm = scale(value))

quotient <- read_csv("./tracegram-pilot/results/results.csv") %>%
    separate(file, c("speaker", "phonation")) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(phonation = factor(phonation, levels = c("modal", "breathy")),
           closed_quotient = degg_minimum - degg_maximum
           )

quotient_mean <- quotient %>%
    group_by(speaker, phonation, token) %>%
    summarise(mean_quotient = mean(closed_quotient))
```

# dEGG maxima and minima

```{r degg-boxplot}
ggplot(degg_tracing, aes(peak, value, colour = phonation)) +
    geom_boxplot() +
    facet_grid(. ~ speaker)
```

```{r degg-violin}
ggplot(degg_tracing, aes(peak, value, colour = phonation)) +
    geom_violin() +
    facet_grid(. ~ speaker)
```

# Tracegram plot

```{r speaker-tracegram-plot}
ggplot(degg_tracing, aes(time, value, colour = peak)) +
    geom_point(size = 0.5, alpha = 0.1) +
    geom_smooth(size = 0.5, method = "lm") +
    xlab("relative time (proportion of vowel duration)") +
    ylab("proportion of glottal period") +
    facet_grid(speaker ~ phonation) +
    ylim(0, 1)
```

```{r tracegram-plot}
ggplot(degg_tracing, aes(time, value, colour = peak)) +
    geom_point(size = 0.5, alpha = 0.1) +
    geom_smooth(size = 0.5, method = "loess") +
    xlab("relative time (proportion of vowel duration)") +
    ylab("proportion of glottal period") +
    facet_grid(. ~ phonation)
```

```{r norm-tracegram-plot}
ggplot(degg_tracing_norm, aes(time, value_norm, colour = peak)) +
    geom_point(size = 0.5, alpha = 0.1) +
    geom_smooth(size = 0.5, method = "lm") +
    xlab("relative time (proportion of vowel duration)") +
    ylab("proportion of glottal period") +
    facet_grid(. ~ phonation)
```

# Closed quotient

```{r cq-density}
ggplot(quotient, aes(closed_quotient, colour = phonation)) +
    geom_density() +
    facet_wrap(~ speaker)
```

```{r speaker-cq-boxplot}
ggplot(quotient, aes(phonation, closed_quotient)) +
    geom_boxplot() +
    facet_wrap(~ speaker)
```

```{r cq-boxplot}
ggplot(quotient, aes(phonation, closed_quotient)) +
    geom_boxplot()
```

```{r quotient-lmer}
quotient_lmer <- lmer(
    closed_quotient ~
        phonation +
        (1 + phonation|speaker),
    data = quotient
)

summary(quotient_lmer)
```

```{r quotient-likelyhood}
quotient_lmer_null <- lmer(
    closed_quotient ~
        (1 + phonation|speaker),
    data = quotient
)

anova(quotient_lmer_null, quotient_lmer)
```

```{r quotient-lmer-effects}
plot(allEffects(quotient_lmer))
```

```{r quotient-lmer-random-coefficients}
coefficients(quotient_lmer)$speaker
```

```{r cq-plot}
ggplot(quotient, aes(time, closed_quotient, colour = speaker)) +
    geom_point(alpha = 0.2) +
    facet_grid(phonation ~ .)
```

```{r cq-plot-2}
filter(quotient, token == 1) %>%
ggplot(aes(time, closed_quotient, colour = phonation)) +
    geom_point(alpha = 0.2) +
    geom_smooth(method = "lm") +
    facet_grid(. ~ speaker)
```

```{r mean-quotient-lmer}
mean_quotient_lmer <- lmer(
    mean_quotient ~
        phonation +
        (1 + phonation|speaker),
    data = quotient_mean
)

summary(mean_quotient_lmer)
```
