---
title: "Wavegram"
author: "Stefano Coretta"
date: "08/08/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(itsadug)
options(contrasts = rep("contr.treatment", 2))
```

# Data import

```{r data}
wavegram <- read_csv("../results/wavegram.csv") %>%
    separate(file, c("speaker", "phonation")) %>%
    mutate(
        phonation = ordered(phonation, levels = c("modal", "breathy")),
        speaker_phon = ordered(interaction(speaker, phonation))
    ) %>%
    mutate_if(is.character, as.factor)
```

# Analysis

```{r s01-gam}
s01_gam <- bam(
    amplitude ~
        phonation +
        s(sequence) + s(sample) +
        s(sequence, by = phonation) + s(sample, by = phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = phonation),
    data = filter(wavegram, speaker == "01")
)

summary(s01_gam)
```

```{r s01-gam-diff}
plot_diff2(
    s01_gam,
    view = c("sequence", "sample"), 
    comp = list(phonation = c("modal", "breathy")),
    zlim = c(-1, 1)
)
```

```{r s01-gam-plot}
fvisgam(
    s01_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "modal"),
    zlim = c(0, 1)
)

fvisgam(
    s01_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "breathy"),
    zlim = c(0, 1)
)
```

```{r}
sn.gam <- bam(
    amplitude ~
        s(sequence, k = 8) + s(sample) +
        s(sequence, by = phonation.ord, k = 8) + s(sample, by = phonation.ord),
#        ti(sequence, sample) +
#        ti(sequence, sample, by = phonation.ord),
    data = filter(wavegram, speaker == "sn")
)

summary(sn.gam)
```

```{r}
plot_diff2(
    sn.gam,
    view=c("sequence", "sample"), 
    comp=list(phonation.ord=c("modal", "breathy")),
    zlim = c(-1, 1)
)
```

```{r}
fvisgam(
    sn.gam,
    view = c("sequence","sample"),
    cond = list(phonation.ord = "modal"),
    zlim = c(0, 1)
)

fvisgam(
    sn.gam,
    view = c("sequence","sample"),
    cond = list(phonation.ord = "breathy"),
    zlim = c(0, 1)
)
```

```{r}
js.gam <- bam(
    amplitude ~
        s(sequence, k = 8) + s(sample) +
        s(sequence, by = phonation.ord, k = 8) + s(sample, by = phonation.ord) +
        ti(sequence, sample) +
        ti(sequence, sample, by = phonation.ord),
    data = filter(wavegram, speaker == "js"),
    method = "ML"
)

summary(sn.gam)

js.gam.null <- bam(
    amplitude ~
        s(sequence, k = 8) + s(sample) +
#        s(sequence, by = phonation.ord, k = 8) + s(sample, by = phonation.ord) +
        ti(sequence, sample),# +
#        ti(sequence, sample, by = phonation.ord),
    data = filter(wavegram, speaker == "js"),
    method = "ML"
)

compareML(js.gam.null, js.gam)
```

```{r}
plot_diff2(
    js.gam,
    view = c("sequence", "sample"), 
    comp = list(phonation.ord = c("modal", "breathy")),
    zlim = c(-1, 1)
)
```

```{r}
fvisgam(
    js.gam,
    view = c("sequence","sample"),
    cond = list(phonation.ord = "modal"),
    zlim = c(0, 1)
)

fvisgam(
    js.gam,
    view = c("sequence","sample"),
    cond = list(phonation.ord = "breathy"),
    zlim = c(0, 1)
)
```

```{r}
acf_plot(resid(js.gam))
```

```{r}
gb.gam <- bam(
    amplitude ~
        s(sequence, k = 6) +
        s(sample) +
        s(sequence, by = phonation.ord, k = 6) +
        s(sample, by = phonation.ord) +
        ti(sequence, sample) +
        ti(sequence, sample, by = phonation.ord),
    data = filter(wavegram, speaker == "gb"),
    method = "fREML"
)

summary(sn.gam)

gb.gam.null <- bam(
    amplitude ~
        s(sequence, k = 6) +
        s(sample) +
#        s(sequence, by = phonation.ord, k = 8) + s(sample, by = phonation.ord) +
        ti(sequence, sample),# +
#        ti(sequence, sample, by = phonation.ord),
    data = filter(wavegram, speaker == "gb"),
    method = "fREML"
)

compareML(gb.gam.null, gb.gam)
```

```{r}
plot_diff2(
    gb.gam,
    view = c("sequence", "sample"), 
    comp = list(phonation.ord = c("modal", "breathy")),
    zlim = c(-1, 1)
)
```

```{r all-gam}
phonation_gam <- bam(
    amplitude ~
        phonation +
        s(sequence, k = 6) +
        s(sample) +
        s(sequence, by = phonation, k = 6) +
        s(sample, by = phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = phonation) +
        s(sequence, speaker_phon, bs = "fs", m = 1),
    data = wavegram,
    method = "ML"
)

summary(phonation_gam)

phonation_gam_null <- bam(
    amplitude ~
#        phonation +
        s(sequence, k = 6) +
        s(sample) +
#        s(sequence, by = phonation, k = 8) + s(sample, by = phonation) +
        ti(sequence, sample) +
#        ti(sequence, sample, by = phonation)+
        s(sequence, speaker_phon, bs = "fs", m = 1),
    data = wavegram,
    method = "ML"
)

compareML(phonation_gam_null, phonation_gam)
```

```{r all-gam-diff}
plot_diff2(
    phonation_gam,
    view = c("sequence", "sample"), 
    comp = list(phonation = c("modal", "breathy")),
    zlim = c(-1, 1),
    rm.ranef = TRUE
)
```

```{r all-gam-plot}
fvisgam(
    phonation_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "modal"),
    zlim = c(0, 1),
    rm.ranef = TRUE
)

fvisgam(
    phonation_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "breathy"),
    zlim = c(0, 1),
    rm.ranef = TRUE
)
```
