---
title: "Wavegram pilot"
author: "Stefano Coretta"
date: "08/08/2017"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(itsadug)
options(contrasts = rep("contr.treatment", 2))
```

# Data import

```{r data}
wavegram <- read_csv("../results/wavegram.csv") %>%
    separate(file, c("speaker", "phonation")) %>%
    mutate(
        phonation = ordered(phonation, levels = c("modal", "breathy")),
        speaker_phon = ordered(interaction(speaker, phonation))
    ) %>%
    mutate_if(is.character, as.factor) %>%
    filter(sequence < 8)
```

# Analysis

## S01

```{r s01-gam}
s01_gam <- bam(
    amplitude ~
        phonation +
        s(sequence, k = 8) + s(sample) +
        s(sequence, by = phonation, k = 8) + s(sample, by = phonation) +
        ti(sequence, sample, k = 8) +
        ti(sequence, sample, by = phonation, k = 8),
    data = filter(wavegram, speaker == "01")
)

summary(s01_gam)
```

```{r s01-gam-diff}
plot_diff2(
    s01_gam,
    view = c("sequence", "sample"), 
    comp = list(phonation = c("modal", "breathy")),
    zlim = c(-1, 1)
)
```

```{r s01-gam-plot}
fvisgam(
    s01_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "modal"),
    zlim = c(0, 1)
)

fvisgam(
    s01_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "breathy"),
    zlim = c(0, 1)
)
```

```{r s02-gam}
s02_gam <- bam(
    amplitude ~
        phonation +
        s(sequence, k = 7) + s(sample) +
        s(sequence, by = phonation, k = 7) + s(sample, by = phonation) +
        ti(sequence, sample, k = 7) +
        ti(sequence, sample, by = phonation, k = 7),
    data = filter(wavegram, speaker == "02")
)

summary(s02_gam)
```

```{r s02-gam-diff}
plot_diff2(
    s02_gam,
    view = c("sequence", "sample"), 
    comp = list(phonation = c("modal", "breathy"))
)
```

```{r s02-gam-plot}
fvisgam(
    s02_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "modal")
)

fvisgam(
    s02_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "breathy")
)
```

## S03

```{r s03-gam}
s03_gam <- bam(
    amplitude ~
        phonation +
        s(sequence, k = 8) + s(sample) +
        s(sequence, by = phonation, k = 8) + s(sample, by = phonation) +
        ti(sequence, sample, k = 8) +
        ti(sequence, sample, by = phonation, k = 8),
    data = filter(wavegram, speaker == "03"),
    method = "ML"
)

summary(s03_gam)

s03_gam_null <- bam(
    amplitude ~
        # phonation +
        s(sequence, k = 8) + s(sample) +
        # s(sequence, by = phonation, k = 8) + s(sample, by = phonation) +
        ti(sequence, sample, k = 8),# +
        # ti(sequence, sample, by = phonation, k = 8),
    data = filter(wavegram, speaker == "03"),
    method = "ML"
)

compareML(s03_gam_null, s03_gam)
```

```{r s03-gam-diff}
plot_diff2(
    s03_gam,
    view = c("sequence", "sample"), 
    comp = list(phonation = c("modal", "breathy"))
)
```

```{r s03-gam-plot}
fvisgam(
    s03_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "modal")
)

fvisgam(
    s03_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "breathy")
)
```

```{r s03-gam-acf}
acf_plot(resid(s03_gam))
```

## All speakers

```{r all-gam}
phonation_gam <- bam(
    amplitude ~
        phonation +
        s(sequence, k = 8) +
        s(sample) +
        s(sequence, by = phonation, k = 8) +
        s(sample, by = phonation) +
        ti(sequence, sample, k = 8) +
        ti(sequence, sample, by = phonation, k = 8) +
        s(sequence, speaker_phon, bs = "fs", m = 1, k = 8),
    data = wavegram,
    method = "ML"
)

summary(phonation_gam)

phonation_gam_null <- bam(
    amplitude ~
#        phonation +
        s(sequence, k = 8) +
        s(sample) +
#        s(sequence, by = phonation, k = 8) + s(sample, by = phonation) +
        ti(sequence, sample, k = 8) +
#        ti(sequence, sample, by = phonation) +
        s(sequence, speaker_phon, bs = "fs", m = 1, k = 8),
    data = wavegram,
    method = "ML"
)

compareML(phonation_gam_null, phonation_gam)
```

```{r all-gam-diff}
plot_diff2(
    phonation_gam,
    view = c("sequence", "sample"), 
    comp = list(phonation = c("modal", "breathy")),
    rm.ranef = TRUE
)
```

```{r all-gam-plot}
fvisgam(
    phonation_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "modal"),
    rm.ranef = TRUE
)

fvisgam(
    phonation_gam,
    view = c("sequence","sample"),
    cond = list(phonation = "breathy"),
    rm.ranef = TRUE
)
```

```{r all-gam-plot-03}
fvisgam(
    phonation_gam,
    view = c("sequence","sample"),
    cond = list(
        phonation = "modal",
        speaker_phon = "03.modal"
    )
)

fvisgam(
    phonation_gam,
    view = c("sequence","sample"),
    cond = list(
        phonation = "breathy",
        speaker_phon = "03.breathy"
    )
)
```
