---
title: "Voicing durations"
author: "Stefano Coretta"
date: "02/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(lmerTest)
library(effects)
```

# Read data

```{r read-data}
languages <- read_csv("./voicing-effect/data/datasets/speakers.csv")
words <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

voicing <- list.files(
  path = "voicing-effect/data/datasets/egg/",
  pattern = "*-voicing.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--")) %>%
  left_join(., languages) %>%
  left_join(y = words) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    index = as.factor(index)
  )


voicing_voiceless <- filter(voicing, c2_phonation == "voiceless", c1_phonation == "voiceless")

voicing_norm <- voicing_voiceless %>%
  filter(voicing_duration < 250) %>%
  group_by(speaker) %>%
  mutate(voicing_duration_norm = scale(voicing_duration))
```

# Plots

```{r}
voicing_voiceless %>%
  ggplot(aes(voiced_points, fill = language)) +
  geom_bar() +
  facet_grid(~ language)
```

```{r}
voicing_voiceless %>%
  ggplot(aes(voiced_points, fill = vowel)) +
  geom_bar() +
  facet_grid(language ~ vowel)
```

```{r}
voicing_voiceless %>%
  group_by(language, voiced_points) %>%
  summarise(n = n())
```

```{r}
voicing_voiceless %>%
  filter(voiced_points < 2) %>%
  nrow()
```

```{r}
voicing_voiceless %>%
  filter(voiced_points < 4) %>%
  nrow()
```

```{r}
voicing_voiceless %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

It looks like there is something wrong with IT12 (Rome).
IT12 has several tokens of voiceless stops with voicing within closure.
It is probably better if I exclude IT12.

```{r}
voicing_voiceless %>%
  filter(voicing_duration < 250) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_wrap(~ speaker, scales = "free")
```

```{r}
voicing_voiceless %>%
  filter(voiced_points < 4) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_wrap(~ speaker, scales = "free")
```

```{r vowel-boxplot}
voicing_voiceless %>%
  filter(voicing_duration < 250) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot()
```

```{r vowel-boxplot}
voicing_voiceless %>%
  filter(voicing_duration < 250) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_grid(c2_place ~ .)
```

```{r vowel-boxplot-2}
voicing_voiceless %>%
  filter(voiced_points < 4) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot()
```

```{r vowel-language-boxplot}
voicing_voiceless %>%
  filter(voicing_duration < 250) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r vowel-language-boxplot-2}
voicing_voiceless %>%
  filter(voiced_points < 4) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r vowel-language-boxplot-3}
voicing_voiceless %>%
  filter(speaker != "it12", voicing_duration < 250) %>%
  ggplot(aes(vowel, voicing_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r norm-vowel-boxplot}
voicing_norm %>%
  ggplot(aes(vowel, voicing_duration_norm)) +
  geom_boxplot()
```

```{r norm-vowel-language-boxplot}
voicing_norm %>%
  ggplot(aes(vowel, voicing_duration_norm)) +
  geom_boxplot() +
  facet_grid(~ language)
```

# Lmer

```{r voicing-lm}
voicing_lm <- lmer(
  voicing_duration ~
    vowel +
    language +
    vowel:language +
    (1+vowel|speaker) +
    (1|word),
  data = filter(voicing_voiceless, voicing_duration < 250, speaker != "it12"),
  REML = FALSE
)
summary(voicing_lm)

voicing_lm_null <- lmer(
  voicing_duration ~
    vowel +
    language +
#    vowel:language +
    (1+vowel|speaker) +
    (1|word),
  data = filter(voicing_voiceless, voicing_duration < 250, speaker != "it12"),
  REML = FALSE
)

anova(voicing_lm_null, voicing_lm)

voicing_lm_null_2 <- lmer(
  voicing_duration ~
#    vowel +
    language +
#    vowel:language +
    (1+vowel|speaker) +
    (1|word),
  data = filter(voicing_voiceless, voicing_duration < 250, speaker != "it12"),
  REML = FALSE
)

anova(voicing_lm_null_2, voicing_lm_null)

voicing_lm_null_3 <- lmer(
  voicing_duration ~
#    vowel +
    language +
#    vowel:language +
    (1|speaker) +
    (1|word),
  data = filter(voicing_voiceless, voicing_duration < 250, speaker != "it12"),
  REML = FALSE
)

anova(voicing_lm_null_3, voicing_lm_null_2)
```

```{r voicing-effect}
plot(allEffects(voicing_lm))
```

```{r voicing-effect-null}
plot(allEffects(voicing_lm_null))
```

It seems vowel identity does not affect voicing duration (neither in Italian nor Polish).

```{r}
voicing_lm_2 <- lmer(
  voicing_duration ~
    vowel +
    language +
    vowel:language +
    (1+vowel|speaker) +
    (1|word),
  data = filter(voicing_voiceless, voiced_points < 4),
  REML = FALSE
)
summary(voicing_lm_2)
```

```{r}
plot(allEffects(voicing_lm_2))
```

```{r}
voicing_lm_3 <- lmer(
  voicing_duration ~
    vowel +
    language +
    vowel:language +
    (1+vowel|speaker) +
    (1|word),
  data = filter(voicing_voiceless, voiced_points < 4, speaker != "it12"),
  REML = FALSE
)
summary(voicing_lm_3)
```

```{r}
voicing_lm_4 <- lmer(
  voicing_duration_norm ~
    vowel +
    (1|word),
  data = filter(voicing_norm, voiced_points < 4),
  REML = FALSE
)
summary(voicing_lm_4)
```

```{r}
plot(allEffects(voicing_lm_4))
```

