---
title: "Perceptual pilot experiment"
author: "Stefano Coretta"
date: "11/01/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(sjPlot)
library(brms)
options(mc.cores = parallel::detectCores())
```

# Import data

```{r import}
pilot <- list.files(
  path = "./perceptual-pilot/experiment/results/",
  pattern = "*.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., col_types = cols(.default = "c"))) %>%
  mutate(
    key_resp_2.keys = ifelse(key_resp_2.keys == "z", "d", "t"),
    key_resp_8.keys = ifelse(key_resp_8.keys == "z", "t", "d"),
    response = coalesce(key_resp_2.keys, key_resp_8.keys),
    response = factor(response, levels = c("t", "d")),
    burst = as.numeric(burst),
    voicing = as.numeric(voicing),
    response_n = as.numeric(response) - 1,
    vowel = factor(vowel, levels = c("a", "i", "u"))
  ) %>%
  filter(!is.na(response))

contrasts(pilot$vowel) <- "contr.sum"

burst <- filter(pilot, condition == "burst")
voicing <- filter(pilot, condition == "voicing")
```

# Explore

```{r}
pilot %>%
    filter(condition == "burst") %>%
    ggplot(aes(burst, as.numeric(response))) +
    geom_smooth(method = "loess", se = FALSE) +
  ylim(1, 2)
```

```{r}
pilot %>%
    filter(condition == "voicing") %>%
    ggplot(aes(voicing, as.numeric(response))) +
    geom_smooth(method = "loess", se = FALSE) +
  ylim(1, 2)
```

# Inference

```{r}
burst_lm <- glmer(
  response_n ~
    burst *
    vowel +
    (1|participant),
  data = burst,
  family = binomial
)

summary(burst_lm)
```

```{r}
plot_model(burst_lm, "pred", terms = c("burst", "vowel"))
```

```{r}
voicing_lm <- glmer(
  response_n ~
    voicing *
    vowel +
    (1|participant),
  data = voicing,
  family = binomial
)

summary(voicing_lm)
```

```{r}
plot_model(voicing_lm, "pred", terms = c("voicing", "vowel"))
```

## Bayesian

```{r burst}
priors <- c(
  prior(student_t(3, 0, 2), class = Intercept),
  prior(student_t(3, 0, 2), class = b),
  prior(cauchy(0, 1), class = sd),
  prior(lkj(2), class = cor)
)

burst_bm <- brm(
  response_n ~
    burst *
    vowel +
    (1+burst|participant),
  data = burst,
  prior = priors,
  family = bernoulli,
  file = "./perceptual-pilot/data/cache/burst_bm"
)
```

