---
title: "A time-aligned account of lingual and laryngeal gestures using ultrasound tongue imaging (UTI) and electroglottography (EGG)"
author: "Stefano Coretta"
date: "14/01/2017"
output:
  pdf_document:
    citation_package: natbib
    latex_engine: xelatex
    number_sections: yes
    toc: yes
bibliography: linguistics.bib
biblio-style: unified.bst

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose

The combination of techniques described in the following sections allows a synchronous mapping of lingual gestures and phonation during speech.
Such methodology enables a time-aligned account of the movements of the tongue and the concomitant configuration of the glottis that characterises phonation.
These techniques employ ultrasound tongue imaging (UTI) and electroglottography (EGG) for the simultaneous acquisition of articulatory data from, respectively, the oral cavity and the glottis.


# Methodology


## Ultrasound tongue imaging

Ultrasound tongue imaging (UTI) uses ultrasonography for charting the movements of the tongue into a two-dimensional image.
In medical sonography, ultrasound waves (sound waves at high frequencies, ranging between 2 and 14 MHz) are emitted from a probe in a fan-like manner, and travel through organic material (such as skin and muscles).
When the surface of a material with different density is hit, the ultrasound waves are partially reflected, and such "echo" is registered by the probe.
These echoes can then be plotted on a two-dimensional graph, where different densities are represented by different shades (higher densities are brighter, while lower densities are darker).
The graph, or ultrasound image, will show high density surfaces as very bright lines, surrounded by darker areas.
By positioning the ultrasound probe in contact with the submental triangle (the surface below the chin), sagittally oriented, we can infer the cross-sectional profile of the tongue, which appears as a bright line in the resulting ultrasound image.


## Electroglottography

Electroglottography is a technique that measures the size of contact between the vocal folds (the Vocal Folds Contact Area, VFCA).


## Equipment setup

## Post-processing: synchronisation and dEGG extraction

Since the signals from the ultrasound machine and the laryngograph are recorded simultaneously but separately, data from both machines need to be synchronised after acquisition.
Synchronisation is achieved through the cross-correlation of the audio signals from both sources [@grimaldi2008].
The cross-correlation method creates a new sound file from two audio files.
The created new file is a convolution of the original files.
The time of the maximum amplitude in the convoluted sound wave is the amount of off-set between the two original files.
The off-set is trimmed from the beginning of the longer audio file, with the result that the files will be in sync.
A measure taken at any particular time in the ultrasound source can thus be related to a measure taken at that same time in the laryngograph source.

[image of cross-correlation]: #

Previous studies have shown that the mathematical first derivative of the EGG signal helps determine the moments of glottal closure and opening in each vibration cycle (glottal period).
The first derivative of a signal is basically the velocity of the signal, in other words how fast the signal changes in time.
The time of maximum velocity in the first derivative of the EGG signal (dEGG) roughly corresponds to the moment of glottal closure.
The time of minimum velocity corresponds to the moment of glottal opening.
Thus, glottal closure and opening for each glottal period can be extracted from the dEGG.

[say that shorter closed phase correlates with glottal spread]: #

@herbst2010 describe a new technique, called electroglottographic "wavegram," which displays the variations in the EGG and dEGG signals in a single graph.
A wavegram contains temporal information on the *x* and *y* axis, while changes in the VFCA are rendered as different colour intensities on the *z* axis.

The extraction of dEGG maxima and minima has been implemented in the PRAAT scripting language.
The algorithm consists of the following stages:
1. detection of the glottal periods
1. calculation of the dEGG
1. extraction of absolute dEGG maximum and minimum for each glottal period
1. calculation of maxima and minima relative to the glottal period



## dEGG tracegram analysis



# References
