---
title: This is a title and this is too
shorttitle: A subtitle goes on another line
author:
- name: Stefano Coretta
  affiliation: Linguistics and English Language, University of Manchester, Oxford Road, Manchester, M13 9PL, United Kingdom
  email: stefano.coretta\@manchester.ac.uk
  thanks: other info
output:
  jasaarticle::jasa_article:
    citation_package: natbib
    fig_caption: yes
abstract: |
  The abstract.
bibliography: linguistics.bib
mainfont: "Times New Roman"
classoption: preprint
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The position of the tongue root during the production of voiced stops plays a fundamental role in ensuring that voicing can be sustained.
The realisation of vocal fold vibration (i.e. voicing) requires a difference in air pressure between the cavities below and above the glottis.
Specifically, the sub-glottal pressure needs to be higher than the supra-glottal pressure for voicing to be maintained.
This property of voicing is formally known as the Aerodynamic Voicing Constraint [@ohala2011].
When the oral tract is completely occluded during the production of a stop closure, the supra-glottal pressure quickly increases, due to the incoming airstream from the lungs.
Such pressure increase can hinder the ability to sustain vocal fold vibration during closure, to the point in which voicing ceases.

An articulatory solution to counterbalance the increased pressure is to enlarge the supra-glottal cavity by advancing the root of the tongue.
It has been repeatedly observed that the tongue root is in a more front position in voiced stops compared to voiceless stops [@kent1969; @perkell1969; @westbury1983].
@rothenberg1967 calculates that the walls of the supraglottal cavity can absorb the incoming airflow for 20 to 30 ms by passive expansion, after which the sub- and supraglottal pressures would equalise and voicing cease.
@rothenberg1967 thus argues that a passive expansion of the pharyngeal walls is not sufficient.

According to @rothenberg1967, the active forward gesture of the tongue root would have a time constant of 70 to 90 ms.
Given that stop closures are generally much shorter than that, it is natural that advancement is initiated during the vowel, so that an appreciable amount of advancement is obtained when closure is achieved.
Furthermore, @westbury1983 finds that tongue root advancement is initiated before full closure is achieved and that there is a forward movement even in the context of voiceless stops, which is counterintuitive given that tongue root advancement is generally considered to be a feature of voiced stops.

However, the relationship between tongue root advancement and voicing is a complex one.
First, tongue root advancement is not the only mechanism for sustaining voicing during a stop [@rothenberg1967; @westbury1983; @ohala2011] and it has a certain level of idiosyncrasy [@ahn2016].
Other solutions include expansion of the lateral walls of the pharynx [], larynx lowering [@riordan1980], opening of the velopharyngeal port [@yanagihara1966], producing a retroflex occlusion [@sprouse2008].
Second, implementation of tongue root advancement can be decoupled from the presence of actual vocal fold vibration.
@ahn2015; @ahn2016 look at word-initial stops in American English.
The stops were phonologically voiceless or voiced.
They find that the tongue root is more advanced in the phonologically voiced stops independent of whether they actually show vocal fold vibration or not.

<!-- need more info on experiment -->
In an exploratory study of the link between voicing and vowel duration, @coretta2018f; @coretta2018d looks at the dynamics of tongue root position during the production of vowels before voiceless and voiced stops in Italian and Polish.
Coretta finds that the advancing gesture of the tongue root is initiated at around 50% into the duration of vowel and that the advancing gesture is present in vowels before both voiced and voiceless stops in both languages.
These findings are in agreement with @rothenberg1967 and @westbury1983.
<!-- evolutionary scenario? -->
The presence of an advancing gesture---relative to the position of the root at the onset of the vowel---in voiceless stops could be a mechanical consequence of tongue body raising.


The place of articulation of the consonant and the vowel type also have an effect on tongue root advancement.
<!-- maybe just mention vowels in a footnote? -->
Voiced labial stops do not generally show tongue root advancement but rather tongue body lowering [@svirsky1997; @vazquez-alvarez2007].
Tongue body lowering, however, is also a general property of labial stops (whether voiced or not), such that during the production of labial stops, the tongue body lowers relative to the preceding and following vocalic segment, phenomenon known as the trough effect.
<!-- and this interestingly fits within the evolutionary cooptation scenario -->

# Methods

## Participants

20 native speakers of American English participated in the experiment.
The participants received a monetary compensation of $10.

## Equipment set-up

The system set-up of the Speech Production Laboratory of the Department of Speech and Hearing Sciences at Indiana University, USA (@lulich2017; @charles2018).
The ultrasonic data was acquired with a Philips EPIQ 7G system using an xMatrix 117 x6-1 digital 3D/4D transducer ().
Stabilisation of the ultrasonic transducer was ensured with the Articulate Instruments Ltd™ headset (\citeyear{articulate2008}).
Synchronised audio was recorded with a SHURE KSM32 microphone, sampled at 48 kHz (16-bit).

## Materials

For this study we have chosen mono- and disyllabic nonce words as target words.
The monosyllabic words are C\textsubscript{1}VC\textsubscript{2} words (*pop*, *pob*, *caulk* [kʰɒkʰ], *cog*).
The disyllabic words have a C\textsubscript{1}VC\textsubscript{2}-*er* structure (*popper*, *pobber*, *cocker*, *cogger*).
The place of articulation of C\textsubscript{1} and C\textsubscript{2} was kept constant within each word to facilitate measuring tongue displacement and locating gestural landmarks.
Only one vowel (/ɒ/) was included in the study to keep the number of stimuli low, and hence the duration of the task short.
Moreover, back low vowels like /ɒ/ are easier to image with ultrasound given the proximity of tongue to the transducer.
<!-- possibly footnote we expect more TRA because the vowel is very retracted -->

## Procedure

The data was collected in a sound-attenuated booth in the Speech Production Laboratory at Indiana University.
The stabilisation headset was fitted on the participant head before recording started.
The hard palate was imaged by asking the participant to swallow water [@epstein2005].
The participants then read the sentence stimuli which were displayed on a screen via the WASL software.
WASL was developed by Steven M. Lulich and the Indiana University Speech Production Laboratory, \url{http://www.indiana.edu/~spliu/WASL.htm}.
Each participant read the list of 8 stimuli 10 times.
The order of the stimuli was randomised both across repetitions and across speakers.
A total of 1600 tokens were recorded (8 stimuli per 10 repetitions per 20 speakers).

## Data processing and analysis




\begin{acknowledgments}
Thanks to...
\end{acknowledgments}

\appendix
\section{Optional appendix}
