---
title: This is a title and this is too
shorttitle: A subtitle goes on another line
author:
- name: Stefano Coretta
  affiliation: Linguistics and English Language, University of Manchester, Oxford Road, Manchester, M13 9PL, United Kingdom
  email: stefano.coretta\@manchester.ac.uk
  thanks: other info
output: jasaarticle::jasa_article
abstract: |
  Put your abstract here. Abstracts are limited to 200 words for
  regular articles and 100 words for Letters to the Editor. Please no
  personal pronouns, also please do not use the words ``new'' and/or
  ``novel'' in the abstract. An article usually includes an abstract, a
  concise summary of the work covered at length in the main body of the
  article.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

<!-- need to say that tongue comes from UTI -->
Since the publication of the seminal paper by @davidson2006, statistical modelling of whole tongue contours has been dominated by the use of Smoothing Splines Analysis of Variance (SSANOVA), which undoubtedly brought a conspicuous advancement for understanding the articulation of speech sounds.
Some of the limitations of modelling tongue contours with SSANOVA is that separate models are needed for different phonetic contexts even within a single speaker, and secondly SSANOVA as implemented in most studies does not include random effects (which have been shown to be extremely important XXX).
The general difficulty felt with SSANOVA and tongue contours has favoured alternative methods like Principal Component Analysis.

On the other hand, developments in the statistical and programming world have seen the emergence of a highly flexible technique, Generalised Additive models (GAMs).
GAMs have being increasingly adopted in linguistics as a means to model dynamic speech data.
Indeed, @soskuthy2017 explicitly suggests the use of GAMs with tongue contours

This paper introduces an implementation of GAMs with tongue contours using polar coordinates.
The use of polar GAMs is illustrated with ultrasound tongue imaging data comparing voiceless and voiced stops.
The R package `rticulate` has been developed to facilitate the use of the model, and it is briefly introduced here.

## Ultrasound tongue imaging

Ultrasound imaging is a non-invasive technique for obtaining an image of internal organs and tissue.
Ultrasound imaging has been successfully used for imaging the mid-sagittal  section of the tongue surface [].
Ultrasound tongue imaging employs a transducer placed in contact with the sub-mental triangle (the area under the chin).
The transducer propagates ultrasonic waves that travel through the aperture of the mandible and get reflected by the air above the tongue surface.
The reflection is then translated into an image which shows the approximate location of the tongue surface.

## Generalised Additive models

Generalised additive modelling is a more general form of non-parametric modelling that allows fitting non-linear as well as linear effects.
Generalised additive models, or GAMs, are built with smoothing splines.
Smoothing splines are also at the heart of SSANOVA.
In GAMs, however, smoothing splines maximise the fit to the data while being constrained by a smoothing penalty estimated from the data itself which prevents overfitting.
GAMs are powerful and flexible models that can deal with non-linear data efficiently.
Moreover, random effects can also be implemented in GAMs, as generalised additive mixed models (or GAMMs).

Tongue contours as extracted from ultrasound imaging can be efficiently model using GAM(M)s.
The random effects part of GAMMs also constitutes an improvement over traditional SSANOVA, which usually implements fixed effects only.
<!-- say that you can specify the individual contours which reduces the autocorrelation -->

## Polar coordinates

@mielke2015 and @heyne2015a, @heyne2015 have shown the benefits of using polar coordinates of the tongue contours rather then cartesian coordinates.
Polar coordinates are constituted by pairs of radius and angular values, which define a point relative to the origin of the coordinate system.
The point is describes with a radius, which corresponds to the radial distance from the origin, and the angle from the reference radius.
Tongue contours, due to their shape, tend to have increasing slope at the left and right edges, in certain cases tending to become almost completely vertical.
The almost verticality of the contours has the effect of increasing the variance of the fitted contours (and hence increased confidence intervals), and is some cases it even generates uninterpretable curves.
When tongue contours are expressed with polar coordinates, on the other hand, the variance is reduced and the fitted contours generally reflect more closely the underlying tongue shape.
Mielke has implemented a series of R [@r-core-team2018] functions for fitting polar SSANOVAs to tongue contours in cartesian coordinates.
Plotting is subsequently obtained by reconverting the coordinates to cartesian.

# Polar GAM(M)s

Having shown the benefits of using GAMMs with dynamic data and polar coordinates, polar GAMMs for modelling tongue contours are introduced here. Polar GAMMs are GAMMs fitted to tongue contours using polar coordinates.
As with SSANOVA, the coordinates of the fitted contours are converted to cartesian coordinates for plotting.
A polar GAM is constructed as follows: the radius coordinates is the outcome variable, a smooth term over the angular coordinates is the predictor.
The smooth term enables modelling the non-linearities of the contours.
Predictors such as consonant or vowel type, or speech rate, can be specified in the model.
The predicted polar coordinates that are returned by the model can then be converted to cartesian coordinates using the cartesian coordinate of the origin that defines the polar system.
The polar origin is either known or estimated from the data, depending on the ultrasonic system used.

To illustrate the use of polar GAMs, an example will given in the following sections.
The main properties of the R package `rticulate` will also be discussed in relation to the experiment.

## Data collection and processing

Synchronised audio and ultrasound tongue imaging data have been recorded from 11 speakers of Italian.
An Articulate Instruments Ltd™ set-up was used for this study (\Cref{f:uti-setup}).
The ultrasonic data was collected through a TELEMED Echo Blaster 128 unit with a TELEMED C3.5/20/128Z-3 ultrasonic transducer (20mm radius, 2-4 MHz).
A synchronisation unit (P-Stretch) was plugged into the Echo Blaster unit and used for automatic audio/ultrasound synchronisation.
A FocusRight Scarlett Solo pre-amplifier and a Movo LV4-O2 Lavalier microphone were used for audio recording.
The acquisition of the ultrasonic and audio signals was achieved with the software Articulate Assistant Advanced (AAA, v2.17.2) running on a Hawlett-Packard ProBook 6750b laptop with Microsoft Windows 7.
Stabilisation of the ultrasonic transducer was ensured by using a headset produced by Articulate Instruments Ltd™ (\citeyear{articulate2008}).

Before the reading task, the participant's occlusal plane was obtained using a bite plate [@scobbie2011].
The participants read nonce words embedded in the frame sentence *Dico \_\_\_ lentamente* 'I say \_\_\_ slowly'.
The words follow the structure C\textsubscript{1}V́\textsubscript{1}C\textsubscript{2}V\textsubscript{2}, where C\textsubscript{1} = /p/, V\textsubscript{1} = /a, o, u/, C\textsubscript{2} = /t, d, k, g/, and V\textsubscript{2} = V\textsubscript{1}.
Each speaker repeated the stimuli six times.

Spline curves were fitted to the visible tongue contours using the AAA automatic tracking function.
Manual correction was applied in those cases that showed clear tracking errors.
The time of maximum tongue displacement within consonant closure was then calculated in AAA following the method in @strycharczuk2015, described in what follows.
A fan-like frame consisting of 42 equidistant radial lines was used as the coordinate system.
The origin of the 42 fan-lines coincides with the centre of the ultrasonic probe, such that each fan-line is parallel to the direction of the ultrasonic signal.
Tongue displacement was thus calculated as the displacement of the fitted splines along the fan-line vectors.
The time of maximum tongue displacement was the time of greater displacement along the vector that showed the greatest standard deviation.
The vector search area was restricted to the portion of the splines corresponding to the tongue tip for coronal consonants, and to the portion corresponding to the tongue dorsum for velar consonants.















\begin{acknowledgments}
Thanks to...
\end{acknowledgments}

\appendix
\section{Optional appendix}
