---
title: "2018-relrel-analysis"
author: "Stefano Coretta"
date: "30/01/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, fig.lp = "f:", fig.process = function(x) {
  x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
  if (file.rename(x, x2)) x2 else x
})
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(lmerTest)
library(effects)
library(broom)
library(broom.mixed)
library(knitr)
library(kableExtra)
```

```{r read-data, cache=TRUE, include=FALSE, message=FALSE}
load("./datasets/duration_data.Rdata")
durations_filtered <- durations_filtered %>%
  mutate(vor = (c2_rel - v1_ons) * 1000)
round_2 <- function(...) {
  round(..., digits = 2)
}
```

# Individual variation

```{r vow-lm}
vow_lm <- lmer(
  v1_duration ~
    c2_phonation *
    vowel *
    language +
    c2_place +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)

summary(vow_lm)
```

```{r vow-coef}
vow_coef <- as_tibble(coef(vow_lm)$speaker[,1:2], rownames = "speaker") %>%
  rename("intercept" = `(Intercept)`, "ve" = c2_phonationvoiced) %>%
  mutate(language = ifelse(str_detect(speaker, "^it"), "Italian", "Polish"), speaker = toupper(speaker))
```

```{r vow-coef-plot}
vow_coef %>%
  ggplot(aes(reorder(speaker, ve), ve, fill = language)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("black", "gray")) +
  labs(
    x = "Speaker",
    y = "Voicing effect (ms)"
  )
```

```{r vow-coef-plot-2}
vow_coef %>%
  ggplot(aes(ve, reorder(speaker, ve), colour = language)) +
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin = ve - 4.422, xmax = ve + 4.422)) +
  scale_colour_manual(values = c("black", "gray")) +
  labs(
    y = "Speaker",
    x = "Voicing effect (ms)"
  )
```

# Exclude IT02

```{r vow-lm-2}
vow_lm_2 <- lmer(
  v1_duration ~
    c2_phonation *
    vowel *
    language +
    c2_place +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  data = filter(durations_filtered, speaker != "it02")
)

summary(vow_lm_2)
```

# VOR

```{r variation}
durations_filtered %>%
  summarise(
    vor_cv = sd(vor, na.rm = TRUE) / mean(vor, na.rm = TRUE),
    rr_cv = sd(rel_rel, na.rm = TRUE) / mean(rel_rel, na.rm = TRUE),
    vor_cqv = (quantile(vor, na.rm = TRUE, probs = 0.75) -
        quantile(vor, na.rm = TRUE, probs = 0.25)) /
      (quantile(vor, na.rm = TRUE, probs = 0.75) +
         quantile(vor, na.rm = TRUE, probs = 0.25)),
    rr_cqv = (quantile(rel_rel, na.rm = TRUE, probs = 0.75) -
        quantile(rel_rel, na.rm = TRUE, probs = 0.25)) /
      (quantile(rel_rel, na.rm = TRUE, probs = 0.75) +
         quantile(rel_rel, na.rm = TRUE, probs = 0.25))
  )
```

```{r vor-bf}
vor_lm <- lme4::lmer(
  vor ~
    c2_phonation +
    vowel +
    c2_place +
    language +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

vor_lm_null <- lme4::lmer(
  vor ~
    # c2_phonation +
    vowel +
    c2_place +
    language +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

vor_bf <- round(exp((BIC(vor_lm) - BIC(vor_lm_null)) / 2))
```

```{r vv-bf}
vv_lm <- lme4::lmer(
  v_v ~
    c2_phonation +
    vowel +
    c2_place +
    language +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

vv_lm_null <- lme4::lmer(
  v_v ~
    # c2_phonation +
    vowel +
    c2_place +
    language +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

vv_bf_01 <- exp((BIC(vv_lm) - BIC(vv_lm_null)) / 2)
vv_bf_10 <- 1 / vv_bf_01
```
