---
title: "2018 JASA analysis"
author: "Stefano Coretta"
date: "02/07/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(lmerTest)
library(effects)
library(brms)
library(BayesFactor)
library(TOSTER)
library(simr)
```

```{r read-data, include=FALSE, message=FALSE}
speakers <- read_csv("./datasets/speakers.csv")
stimuli <- read_csv("./datasets/stimuli.csv")

durations <- list.files(
  path = "./datasets",
  pattern = "*-durations.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--")) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced")),
    language = recode(language, italian = "Italian", polish = "Polish"),
    syl_rate = ifelse(
      language == "Italian",
      8 / sentence_duration,
      6 / sentence_duration
    )
  ) %>%
  filter(c1_phonation == "voiceless")

durations_filtered <- durations %>%
  group_by(speaker) %>%
  mutate(
    vowel_duration_z = scale(vowel_duration),
    closure_duration_z = scale(closure_duration)
  ) %>%
  filter(
    vowel_duration_z < 3, vowel_duration_z > -3,
    closure_duration_z < 3, closure_duration_z > -3
  )

word_filtered <- durations %>%
    group_by(speaker) %>%
  mutate(
    word_duration_z = scale(word_duration)
  ) %>%
  filter(
    word_duration_z < 3, word_duration_z > -3
  )

rel_filtered <- durations %>%
    group_by(speaker) %>%
  mutate(
    rel_rel_z = scale(rel_rel)
  ) %>%
  filter(
    rel_rel_z < 3, rel_rel_z > -3
  )
```

## Summaries

```{r tokens}
durations %>% group_by(speaker) %>% summarise(n = n())
```


## Plotting

```{r vowel-duration}
durations %>%
  ggplot(aes(vowel_duration)) +
  geom_density() +
  geom_rug()
```

```{r vowel-duration}
durations %>%
  mutate(vowel_duration = log(vowel_duration)) %>%
  ggplot(aes(vowel_duration)) +
  geom_density() +
  geom_rug()
```

```{r vowel-duration}
durations %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel_duration)) %>%
  ggplot(aes(vowel_duration)) +
  geom_density() +
  geom_rug()
```

```{r vowel-duration}
durations %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel_duration)) %>%
  ggplot(aes(vowel_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  geom_rug()
```

```{r vowel-duration}
durations %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel_duration)) %>%
  ggplot(aes(vowel_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  geom_rug() +
  facet_grid(~ language)
```

```{r vowel-duration}
durations %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel_duration)) %>%
  filter(vowel_duration < 2.5, vowel_duration > -2.5) %>%
  ggplot(aes(vowel_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  geom_rug() +
  facet_grid(~ language)
```

```{r}
durations_filtered %>%
  ggplot(aes(vowel, vowel_duration, fill = c2_phonation)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r closure-duration}
durations %>%
  ggplot(aes(closure_duration)) +
  geom_density() +
  geom_rug()
```

```{r closure-duration}
durations %>%
  group_by(speaker) %>%
  mutate(closure_duration = scale(closure_duration)) %>%
  ggplot(aes(closure_duration)) +
  geom_density() +
  geom_rug()
```

```{r closure-duration}
durations %>%
  group_by(speaker) %>%
  mutate(closure_duration = scale(closure_duration)) %>%
  ggplot(aes(closure_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  geom_rug()
```

```{r closure-duration}
durations %>%
  group_by(speaker) %>%
  mutate(closure_duration = scale(closure_duration)) %>%
  ggplot(aes(closure_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  geom_rug() +
  facet_grid(~ language)
```

```{r rel-rel-non-filtr}
durations %>%
  ggplot(aes(c2_phonation, rel_rel)) +
  geom_violin() +
  geom_boxplot(width = 0.2)
```

```{r rel-rel}
durations_filtered %>%
  ggplot(aes(c2_phonation, rel_rel)) +
  geom_violin() +
  geom_boxplot(width = 0.2)
```

```{r rel-rel-box}
durations_filtered %>%
  ggplot(aes(c2_phonation, rel_rel)) +
  geom_boxplot()
```

```{r rel-rel-scaled}
durations_filtered %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(c2_phonation, rel_rel)) +
  geom_boxplot()
```

```{r rel-rel-scaled-speaker}
durations_filtered %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(c2_phonation, rel_rel)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r rel-rel-density}
durations_filtered %>%
  ggplot(aes(rel_rel, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r rel-rel-density-log}
durations_filtered %>%
  mutate(rel_rel = log(rel_rel)) %>%
  ggplot(aes(rel_rel, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r rel-rel-density-vowel}
durations_filtered %>%
  ggplot(aes(rel_rel, fill = vowel)) +
  geom_density(alpha = 0.5)
```

```{r rel-rel-box-vowel}
durations_filtered %>%
  ggplot(aes(vowel, rel_rel, fill = vowel)) +
  geom_boxplot() +
  facet_grid(~language)
```

```{r rel-rel-box-vowel-2}
durations_filtered %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(vowel, rel_rel, fill = vowel)) +
  geom_boxplot() +
  facet_grid(~language)
```

# Lmer

```{r vowel-lm-full}
vowel_lm_full <- lmer(
  vowel_duration ~
    c2_phonation *
    vowel *
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)
summary(vowel_lm_full)

vowel_lm <- lme4::lmer(
  vowel_duration ~
    c2_phonation +
    vowel +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)
summary(vowel_lm)
```

```{r vowel-lm-plot}
plot(allEffects(vowel_lm))
```

```{r closure-lm-full}
closure_lm_full <- lmer(
  closure_duration ~
    c2_phonation *
    vowel *
    language +
    c2_place +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)
summary(closure_lm_full)

closure_lm <- lme4::lmer(
  closure_duration ~
    c2_phonation +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)
summary(closure_lm)
```

```{r closure-lm-plot}
plot(allEffects(closure_lm))
```

```{r vow-clo-lm}
vow_clo_lm_full <- lmer(
  vowel_duration ~
    closure_duration *
    vowel +
    syl_rate +
    (1+closure_duration|speaker) +
    (1|item),
  data = durations_filtered
)
summary(vow_clo_lm_full)

vow_clo_lm <- lme4::lmer(
  vowel_duration ~
    closure_duration *
    vowel +
    syl_rate +
    (1+closure_duration|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)
summary(vow_clo_lm)
```

```{r vow-clo-lm-plot}
plot(allEffects(vow_clo_lm))
```

```{r word-bf}
word_lm <- lme4::lmer(
  word_duration ~
    c2_phonation +
    vowel +
    c2_place +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

word_lm_null <- lme4::lmer(
  word_duration ~
    # c2_phonation +
    vowel +
    c2_place +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

cat("Bayes factor in favor of H0 (`c2_phonationvoiced` = 0): BF01 =", exp((BIC(word_lm) - BIC(word_lm_null)) / 2))
```

```{r rel-rel-bf}
rel_rel_lm <- lme4::lmer(
  rel_rel ~
    c2_phonation +
    vowel +
    c2_place +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

rel_rel_lm_null <- lme4::lmer(
  rel_rel ~
    # c2_phonation +
    vowel +
    c2_place +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

cat("Bayes factor in favor of H0 (`c2_phonationvoiced` = 0): BF01 =", exp((BIC(rel_rel_lm) - BIC(rel_rel_lm_null)) / 2))
```

# Bayes

```{r}
durations_z <- durations %>%
  group_by(speaker) %>%
  mutate(rel_rel_z = scale(rel_rel)) %>%
  na.omit()
```

```{r}
full <- brm(
  rel_rel_z ~
    c2_phonation +
    vowel +
    c2_place +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_z,
  save_all_pars = TRUE,
  iter = 1000
)

null <- brm(
  rel_rel_z ~
    syl_rate +
    vowel +
    c2_place +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_z,
  save_all_pars = TRUE,
  iter = 1000
)

bayes_factor(null, full)
bayes_factor(full, null)
```

```{r}
full_2 <- brm(
  rel_rel ~
    c2_phonation +
    vowel +
    c2_place +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  save_all_pars = TRUE,
  iter = 1000
)

null_2 <- brm(
  rel_rel ~
    vowel +
    c2_place +
    syl_rate +
    (1|speaker) +
    (1|item),
  data = durations_filtered,
  save_all_pars = TRUE,
  iter = 1000
)

bayes_factor(full_2, null_2)
bayes_factor(null_2, full_2)
```

The following does not work.

```{r eval=FALSE}
full_BF <- lmBF(
  rel_rel ~
    c2_phonation +
    syl_rate +
    (1|speaker) +
    (1|item),
  data = durations_filtered
)

null_BF <- lmBF(
  rel_rel ~
    # c2_phonation +
    syl_rate +
    (1|speaker) +
    (1|item),
  data = durations_filtered
)

full_BF / null_BF
```


```{r}
priors <- c(
  set_prior("normal(194, 40)", class = "Intercept")
)

full_brm <- brm(
  rel_rel ~
    c2_phonation,
  data = durations_filtered,
  prior = priors,
  save_all_pars = TRUE
)

BF_brms_savage = hypothesis(full_brm, hypothesis = "c2_phonationvoiced = 0")
BF_brms_savage$hypothesis
```


# TOST

```{r}
TOSTtwo.raw(m1=196.1925,m2=191.3257,sd1=41.85775,sd2=37.37909,n1=534,n2=376,low_eqbound=-2, high_eqbound=2, alpha = 0.05, var.equal=FALSE)

TOSTtwo.raw(m1=187.0956
,m2=184.9379,sd1=41.85775,sd2=37.37909,n1=528,n2=375,low_eqbound=-5, high_eqbound=5, alpha = 0.05, var.equal=TRUE)
```

# Power analysis

```{r}
vowel_lm <- lmer(
  vowel_duration ~
    c2_phonation +
    c2_place +
    vowel +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)

fixef(vowel_lm)["c2_phonationvoiced"] <- 10

powerSim(vowel_lm, fixed("c2_phonationvoiced", "t"), nsim = 1000)

fixef(vowel_lm)["c2_phonationvoiced"] <- 5

powerSim(vowel_lm, fixed("c2_phonationvoiced", "t"), nsim = 1000)
```

```{r}
vowel_lm <- lmer(
  vowel_duration ~
    c2_phonation +
    c2_place +
    vowel +
    language +
    c2_phonation:language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)

fixef(vowel_lm)["c2_phonationvoiced:languagePolish"] <- -10

powerSim(vowel_lm, fixed("c2_phonationvoiced:languagePolish", "t"), nsim = 1000)

fixef(vowel_lm)["c2_phonationvoiced:languagePolish"] <- -13

vowel_lm_2 <- extend(vowel_lm, along = "speaker", n = 40)

lang_pc <- powerCurve(vowel_lm_2, fixed("c2_phonationvoiced:languagePolish", "t"), along = "speaker", nsim = 1000)

plot(lang_pc)
```

```{r}
vowel_lm <- lmer(
  vowel_duration ~
    c2_phonation +
    c2_place +
    vowel +
    language +
    c2_phonation:language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)

data_it <- subset(durations_filtered, language == "Italian")
data_pl <- subset(durations_filtered, language == "Polish")

xdata_it <- extend(data_it, along = "speaker", values = paste0("it", 1:40))
xdata_pl <- extend(data_pl, along = "speaker", values = paste0("pl", 1:40))

fixef(vowel_lm)["c2_phonationvoiced:languagePolish"] <- -10

getData(vowel_lm) <- rbind(xdata_it, xdata_pl)
getData(vowel_lm)$speaker <- as.factor(getData(vowel_lm)$speaker)

lang_pc <- powerCurve(vowel_lm, fixed("c2_phonationvoiced:languagePolish", "t"), along = "speaker", nsim = 1000)
plot(lang_pc)
```


# BRMS

```{r eval=FALSE}
priors <- c(
  set_prior("normal(0, 200)", class = "Intercept"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 25)", class = "b", coef = "languagePolish"),
  set_prior("normal(0, 50)", class = "b", coef = "syl_rate"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("normal(0, 50)", class = "sigma"),
  set_prior("lkj(2)", class = "cor")
)

rel_brm <- brm(
  rel_rel ~
    c2_phonation +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  family = gaussian(),
  prior = priors,
  iter = 20000,
  chains = 4,
  control = list(adapt_delta = 0.99),
  save_all_pars = TRUE
)
summary(rel_brm)
```

```{r eval=FALSE}
priors_0 <- c(
  set_prior("normal(0, 200)", class = "Intercept"),
  # set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 25)", class = "b", coef = "languagePolish"),
  set_prior("normal(0, 50)", class = "b", coef = "syl_rate"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("normal(0, 50)", class = "sigma"),
  set_prior("lkj(2)", class = "cor")
)

rel_brm_0 <- brm(
  rel_rel ~
    # c2_phonation +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  family = gaussian(),
  prior = priors_0,
  iter = 20000,
  chains = 4,
  control = list(adapt_delta = 0.99),
  save_all_pars = TRUE
)

bayes_factor(rel_brm_0, rel_brm)
```

# Speech rate as a confound for language

```{r}
durations_filtered %>%
  ggplot(aes(syl_rate, fill = language)) +
  geom_density(alpha = 0.5)
```

```{r}
durations_filtered %>%
  ggplot(aes(language, syl_rate)) +
  geom_boxplot()
```

```{r}
durations_filtered %>%
  ggplot(aes(syl_rate, fill = language)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~ speaker)
```

```{r}
sr_lm <- lmer(
  syl_rate ~
    language +
    (1|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)
summary(sr_lm)
```

```{r}
plot(allEffects(sr_lm))
```


