---
title: "dEGG tracegram analysis: a pilot study"
author: "Stefano Coretta"
date: "11/01/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
```

## Data import

Import data from `degg-tracing.csv` as `degg`.

```{r import}
degg <- read_csv("tracegram-prepilot/results/degg-tracing.csv")
degg.all <- degg %>%
  mutate_if(is.character, factor) %>%
  mutate(sound = factor(sound, levels = c("modal", "breathy", "creaky1", "mod2bre", "mod2bre2mod")))

degg <- filter(degg.all, sound != "creaky2" & sound != "mod2bre" & sound != "mod2bre2mod") %>%
  mutate(
    sound = factor(sound, levels = c("breathy", "modal", "creaky1"))
  )

degg.contour <- filter(degg.all, sound != "modal" & sound != "breathy" & sound != "creaky1")
```

# Plotting data

Let's first have a look at the tracegrams of modal, breathy and creaky voice.

```{r}
ggplot(degg, aes(x = time, colour = sound)) +
    geom_smooth(aes(y = maximum), size = 1, alpha = 0.2) +
    geom_smooth(aes(y = minimum), size = 1, alpha = 0.2) +
    ylim(0, 1) +
  facet_grid(~ sound)
```

```{r}
ggplot(degg.contour, aes(x = time, colour = sound)) +
    geom_smooth(aes(y = maximum), size = 1, alpha = 0.2) +
    geom_smooth(aes(y = minimum), size = 1, alpha = 0.2) +
    ylim(0, 1)
```

```{r}
ggplot(degg, aes(x = time, colour = sound, linetype = sound)) +
  geom_smooth(method = "lm", aes(y = maximum), size = 1, alpha = 0.2) +
  geom_smooth(method = "lm", aes(y = minimum), size = 1, alpha = 0.2) +
  geom_point(aes(y = maximum), alpha = 0.1) +
  geom_point(aes(y = minimum), alpha = 0.1) +
  ylim(0, 1) +
  facet_grid(~ sound)
```
