---
title: "2018 BAAP analysis"
author: "Stefano Coretta"
date: "05/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(effects)
library(mgcv)
library(itsadug)
library(tidymv)
library(rticulate)
options(contrasts = rep("contr.treatment", 2))
```

# Data import

```{r read-data}
columns <- c(
  "speaker",
  "seconds",
  "rec_date",
  "prompt",
  "label",
  "TT_displacement_sm",
  "TT_velocity",
  "TT_velocity_abs",
  "TD_displacement_sm",
  "TD_velocity",
  "TD_velocity_abs"
)

speakers <- read_csv("./voicing-effect/data/datasets/speakers.csv")
stimuli <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

splines <- list.files(
  path = "./presentations/2018-baap/datasets/ultrasound",
  pattern = "*-tongue-cart.tsv",
  full.names = TRUE
) %>%
  map_df(~read_aaa(., columns)) %>%
  mutate(word = word(prompt, 2)) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate(
    c2phonation = ordered(c2phonation, levels = c("voiceless", "voiced")),
    vowel = ordered(vowel, levels = c("a", "o", "u")),
    c2place = ordered(c2place, levels = c("coronal", "velar")),
    vow_phon = as.ordered(interaction(vowel, c2phonation)),
    c2place_phon = as.ordered(interaction(c2place, c2phonation))
  ) %>%
  mutate_if(is.character, as.factor) %>%
  arrange(rec_date, fan_line) %>%
  create_event_start("rec_date")

vowels <- list.files(
  path = "./presentations/2018-baap/datasets/acoustics/",
  pattern = "*-durations.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--")) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate(c2phonation = factor(c2phonation, levels = c("voiceless", "voiced"))) %>%
  mutate_if(is.character, as.factor)
```

# Exploratory

## Ultrasound

```{r it-coronal-tongue}
splines %>%
  filter(
    language == "italian",
    label == "max_TT"
  ) %>%
  ggplot(aes(X, Y, colour = c2phonation)) +
  geom_point(size = 0.5) +
  facet_grid(vowel ~ speaker) +
  coord_fixed(ratio = 1) +
  theme(legend.position = "top")
```

```{r it-velar-tongue}
splines %>%
  filter(
    language == "italian",
    label == "max_TD"
  ) %>%
  ggplot(aes(X, Y, colour = c2phonation)) +
  geom_point(size = 0.5) +
  facet_grid(vowel ~ speaker) +
  coord_fixed(ratio = 1) +
  theme(legend.position = "top")
```

```{r pl-coronal-tongue}
splines %>%
  filter(
    language == "polish",
    label == "max_TT"
  ) %>%
  ggplot(aes(X, Y, colour = c2phonation)) +
  geom_point(size = 0.5) +
  facet_grid(vowel ~ speaker) +
  coord_fixed(ratio = 1) +
  theme(legend.position = "top")
```

```{r pl-velar-tongue}
splines %>%
  filter(
    language == "polish",
    label == "max_TD"
  ) %>%
  ggplot(aes(X, Y, colour = c2phonation)) +
  geom_point(size = 0.5) +
  facet_grid(vowel ~ speaker) +
  coord_fixed(ratio = 1) +
  theme(legend.position = "top")
```

## Vowel duration

```{r vowdur-dens}
vowels %>%
  ggplot(aes(vowel.duration, fill = c2phonation, colour = c2phonation)) +
  geom_density(alpha = 0.2) +
  facet_grid(~ language)
```

```{r vowdur-dens}
vowels %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel.duration)) %>%
  ggplot(aes(vowel_duration, fill = c2phonation, colour = c2phonation)) +
  geom_density(alpha = 0.2) +
  facet_grid(~ language)
```

```{r vowdur-box}
vowels %>%
  ggplot(aes(c2phonation, vowel.duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r vowdur-box-speakers}
vowels %>%
  ggplot(aes(c2phonation, vowel.duration)) +
  geom_boxplot() +
  facet_wrap(~ speaker, ncol = 4, scales = "free")
```

```{r vowdur-box-speakers-vowels}
vowels %>%
  ggplot(aes(c2phonation, vowel.duration, fill = vowel)) +
  geom_boxplot() +
  facet_wrap(~ speaker, ncol = 4, scales = "free")
```

```{r vowdur-norm}
vowels %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel.duration)) %>%
  ggplot(aes(c2phonation, vowel_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r vowdur-norm-vowels}
vowels %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel.duration)) %>%
  ggplot(aes(vowel, vowel_duration, fill = c2phonation)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r it-vowdur-norm-vowels}
vowels %>%
  filter(language == "italian") %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel.duration)) %>%
  ggplot(aes(vowel, vowel_duration, fill = c2phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker, ncol = 2)
```

```{r pl-vowdur-norm-vowels}
vowels %>%
  filter(language == "polish") %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel.duration)) %>%
  ggplot(aes(vowel, vowel_duration, fill = c2phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker, ncol = 2)
```

# Polar GAMs

## Italian

```{r it01}
it01 <- filter(splines, speaker == "it01", label %in% c("max_TT", "max_TD"))
```

```{r it01-polar-gam}
it01_polar_gam <- polar_gam(
  Y ~
    c2phonation +
    vowel +
    c2place +
#    vow_phon +
#    c2place_phon +
    s(X, bs = "cr") +
    s(X, by = c2phonation, bs = "cr") +
    s(X, by = vowel, bs = "cr") +
    s(X, by = c2place, bs = "cr") +
#    s(X, by = vow_phon, bs = "cr") +
#    s(X, by = c2place_phon, bs = "cr") +
    s(X, rec_date, bs = "fs", xt = "cr", m = 1),
  data = it01,
  method = "ML"
)
summary(it01_polar_gam)
```

No need for interactions.

```{r it01-polar-smooths}
plot_polar_smooths(
  it01_polar_gam,
  X,
  c2phonation,
  facet_terms = c2place + vowel
)
```

```{r it01-polar-gam-null}
it01_polar_gam_null <- polar_gam(
  Y ~
#    c2phonation +
    vowel +
    c2place +
#    vow_phon +
#    c2place_phon +
    s(X, bs = "cr") +
#    s(X, by = c2phonation, bs = "cr") +
    s(X, by = vowel, bs = "cr") +
    s(X, by = c2place, bs = "cr") +
#    s(X, by = vow_phon, bs = "cr") +
#    s(X, by = c2place_phon, bs = "cr") +
    s(X, rec_date, bs = "fs", xt = "cr", m = 1),
  data = it01,
  method = "ML"
)

compareML(it01_polar_gam_null, it01_polar_gam)
```

```{r it01-acf}
acf_plot(resid(it01_polar_gam), split_by = list(it01$rec_date))
```

```{r it01-ar}
rho <- start_value_rho(it01_polar_gam)

it01_polar_gam_ar <- polar_gam(
  Y ~
    c2phonation +
    vowel +
    c2place +
    s(X, bs = "cr") +
    s(X, by = c2phonation, bs = "cr") +
    s(X, by = vowel, bs = "cr") +
    s(X, by = c2place, bs = "cr") +
    s(X, rec_date, bs = "fs", xt = "cr", m = 1),
  data = it01,
  method = "ML",
  rho = rho,
  AR_start = it01$start.event
)
summary(it01_polar_gam_ar)
```

```{r it01-ar-acf}
acf_resid(it01_polar_gam_ar, split_pred = "AR.start")
```

```{r it01-polar-ar-smooths}
plot_polar_smooths(
  it01_polar_gam_ar,
  X,
  c2phonation,
  facet_terms = c2place + vowel
)
```

```{r it02}
it02 <- filter(splines, speaker == "it02", label %in% c("max_TT", "max_TD"))
```

```{r it02-polar-gam}
it02_polar_gam <- polar_gam(
  Y ~
    c2phonation +
    vowel +
    c2place +
#    vow_phon +
#    c2place_phon +
    s(X, bs = "cr") +
    s(X, by = c2phonation, bs = "cr") +
    s(X, by = vowel, bs = "cr") +
    s(X, by = c2place, bs = "cr") +
#    s(X, by = vow_phon, bs = "cr") +
#    s(X, by = c2place_phon, bs = "cr") +
    s(X, rec_date, bs = "fs", xt = "cr", m = 1),
  data = it02,
  method = "ML"
)
summary(it02_polar_gam)
```

```{r it01-polar-smooth}
plot_polar_smooths(
  it02_polar_gam,
  X,
  c2phonation,
  facet_terms = c2place + vowel
)
```

# Vowel duration

```{r vow-it-lm}
vowels_it <- filter(vowels, language == "italian")

vowels_it_lm <- lmer(
  vowel.duration ~
    c2phonation +
    c2place +
    vowel +
    sentence.duration +
    (1+c2phonation|speaker) +
    (1|word),
  data = vowels_it
)

summary(vowels_it_lm)
```

```{r vow-it-effects}
plot(allEffects(vowels_it_lm))
```

```{r vow-pl-lm}
vowels_pl <- filter(vowels, language == "polish")

vowels_pl_lm <- lmer(
  vowel.duration ~
    c2phonation +
    c2place +
    vowel +
    sentence.duration +
    (1+c2phonation|speaker) +
    (1|word),
  data = vowels_pl
)

summary(vowels_pl_lm)
```

```{r vowe-pl-lm}
plot(allEffects(vowels_pl_lm))
```
