---
title: "Closure velocity"
author: "Stefano Coretta"
date: "29/06/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_bw())
library(stringr)
library(rticulate)
library(lmerTest)
library(effects)
```

# Data import

```{r data-import}
columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
)

languages <- read_csv("./voicing-effect/data/datasets/speakers.csv")
words <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

closure <- list.files(
    path = "./voicing-effect/data/datasets/ultrasound",
    pattern = "*-tongue-clos-cart.tsv",
    full.names = TRUE
    ) %>%
    read_aaa(., columns) %>%
    select(seconds, rec.date) %>%
    unique()

nons <- list.files(
    path = "./voicing-effect/data/datasets/ultrasound",
    pattern = "*-tongue-cart.tsv",
    full.names = TRUE
    ) %>%
    read_aaa(., columns) %>%
  filter(label %in% c("NONS_TT", "NONS_TD")) %>%
    select(seconds, rec.date) %>%
    unique()

gons <- list.files(
    path = "./voicing-effect/data/datasets/ultrasound",
    pattern = "*-closing-gons.tsv",
    full.names = TRUE
    ) %>%
    map_df(~read_tsv(., col_names = columns)) %>%
    inner_join(y = closure, by = "rec.date", suffix = c(".gons", ".clos")) %>%
    mutate(
      closing = seconds.clos - seconds.gons,
      closing = closing * 1000,
      word = word(prompt, 2)
    ) %>%
  inner_join(y = nons) %>%
  mutate(
    closing_2 = (seconds - seconds.gons) * 1000
  ) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
  filter(closing > 0, closing_2 > 0) %>%
    mutate_if(is.character, as.factor)

columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs",
    "TR.displacement.sm",
    "TR.velocity",
    "TR.velocity.abs"
)

gons_select <- select(gons, rec.date, closing, closing_2)

tongue_root <- list.files(
  path = "./voicing-effect/data/datasets/ultrasound/",
  pattern = "*-tra-cart.tsv",
  full.names = TRUE
) %>%
    map_df(~read_tsv(., col_names = columns)) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    left_join(y = gons_select) %>%
    # filter clear outlier
    filter(TR.displacement.sm > 40, closing < 200) %>%
    group_by(speaker) %>%
    mutate(
        TR_displacement_z = scale(TR.displacement.sm),
        closing_2_norm = scale(closing_2)
    )
```

# Data plotting

```{r}
gons %>%
  ggplot(aes(c2phonation, closing)) +
  geom_boxplot()
```


```{r}
gons %>%
    ggplot(aes(closing)) +
    geom_density()
```

```{r}
gons %>%
    ggplot(aes(closing)) +
    geom_histogram()
```

```{r}
gons %>%
    ggplot(aes(closing, colour = c2phonation)) +
    geom_density()
```

```{r}
gons %>%
    filter(c2place == "velar") %>%
    ggplot(aes(closing, colour = c2phonation)) +
    geom_density() +
    facet_grid(. ~ vowel)
```

```{r}
gons %>%
    ggplot(aes(closing, fill = c2phonation)) +
    geom_histogram()
```

```{r}
gons %>%
    ggplot(aes(language, closing, colour = c2phonation)) +
    geom_boxplot() +
    facet_grid(vowel ~ c2place)
```

```{r}
table(gons$c2phonation, gons$vowel, gons$c2place)
```

```{r}
gons %>%
  filter(language == "italian") %>%
  ggplot(aes(c2place, closing, colour = c2phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
gons_lm <- lmer(
  closing ~
#    c2phonation *
    vowel *
    c2place +
    (1|speaker) +
    (1|word),
  data = gons
)

summary(gons_lm)
```

```{r}
plot(allEffects(gons_lm))
```

## Closure 2

```{r}
gons %>%
  ggplot(aes(c2phonation, closing_2)) +
  geom_boxplot()
```

```{r}
gons %>%
  ggplot(aes(c2phonation, closing_2)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
gons %>%
  ggplot(aes(vowel, closing_2, colour = c2phonation)) +
  geom_boxplot() +
  facet_grid(c2place ~ speaker)
```

## TRA and closing gesture duration

```{r}
tongue_root %>%
  ggplot(aes(TR_displacement_z, closing, colour = c2phonation)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
tongue_root %>%
  ggplot(aes(TR_displacement_z, closing_2, colour = c2phonation)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(c2place ~ vowel)
```

```{r}
tongue_root %>%
  ggplot(aes(TR_displacement_z, closing_2_norm, colour = c2phonation)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
tongue_root %>%
  ggplot(aes(TR_displacement_z, closing_2_norm, colour = c2phonation)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(c2place ~ vowel)
```

```{r}
tongue_root %>%
  ggplot(aes(TR_displacement_z, closing_2_norm)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(c2place ~ vowel)
```

```{r}
tongue_root %>%
  filter(speaker %in% c("it01", "it02", "pl02", "pl03")) %>%
  ggplot(aes(TR_displacement_z, closing_2_norm)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
tongue_root %>%
  ggplot(aes(TR_displacement_z, closing_2_norm)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~ speaker)
```
