---
title: "Closing gesture"
author: "Stefano Coretta"
date: "29/06/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_bw())
library(rticulate)
library(lme4)
library(effects)
```

# Data import

```{r data-import}
columns <- c(
  "speaker",
  "seconds",
  "rec_date",
  "prompt",
  "label",
  "TT_displacement_sm",
  "TT_velocity",
  "TT_velocity_abs",
  "TD_displacement_sm",
  "TD_velocity",
  "TD_velocity_abs",
  "TR_displacement_sm",
  "TR_velocity",
  "TR_velocity_abs"
)

speakers <- read_csv("./voicing-effect/data/datasets/speakers.csv")
stimuli <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

duration <- list.files(
  path = "voicing-effect/data/datasets/acoustics/",
  pattern = "*-durations.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--"))

tongue <- list.files(
  path = "./voicing-effect/data/datasets/ultrasound",
  pattern = "*-tongue-cart.tsv",
  full.names = TRUE
) %>%
  read_aaa(., columns, format = "wide") %>%
  select(-(X_1:Y_42)) %>%
  mutate(word = word(prompt, 2)) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate(
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))
  ) %>%
  mutate_if(is.character, as.factor) %>%
  filter(c1_phonation == "voiceless")

closing <- tongue %>%
  filter(label %in% c("closure_", "GONS_TD", "GONS_TT")) %>%
  select(-(TT_displacement_sm:TR_velocity_abs)) %>%
  mutate(
    label = ifelse(
      label %in% c("GONS_TT", "GONS_TD"),
      "GONS",
      "closure"
    )
  ) %>%
  spread(label, seconds) %>%
  na.omit() %>%
  mutate(
    closing_duration = (closure - GONS) * 1000
  ) %>%
  filter(closing_duration > 0) %>%
  left_join(y = duration) %>%
  mutate(
    rel_gon = (GONS - c1_rel) * 1000
  )

tongue_root <- tongue %>%
  filter(label %in% c("max_TT", "max_TD")) %>%
  group_by(speaker) %>%
  mutate(TRA = -scale(TR_displacement_sm)) %>%
  ungroup() %>%
  select(rec_date, TR_displacement_sm, TRA) %>%
  inner_join(y = closing)

closing_velocity <- tongue %>%
  filter(label %in% c("peak1_TT", "peak1_TD"))
```

# Closing gesture duration

```{r}
closing %>%
  ggplot(aes(c2_phonation, closing_duration)) +
  geom_boxplot()
```


```{r}
closing %>%
    ggplot(aes(closing_duration)) +
    geom_density()
```

```{r}
closing %>%
    ggplot(aes(closing_duration)) +
    geom_histogram()
```

```{r}
closing %>%
    ggplot(aes(closing_duration, colour = c2_phonation)) +
    geom_density()
```

```{r}
closing %>%
    ggplot(aes(closing_duration, colour = c2_phonation)) +
    geom_density() +
    facet_grid(c2_place ~ vowel)
```

```{r}
closing %>%
    ggplot(aes(closing_duration, fill = c2_phonation)) +
    geom_histogram()
```

```{r}
closing %>%
    ggplot(aes(language, closing_duration, colour = c2_phonation)) +
    geom_boxplot() +
    facet_grid(vowel ~ c2_place)
```

```{r}
table(closing$c2_phonation, closing$vowel, closing$c2_place)
```

```{r}
closing %>%
  ggplot(aes(c2_place, closing_duration, colour = c2_phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
closing_lm <- lmer(
  closing_duration ~
    c2_phonation +
    vowel +
    c2_place +
    (1+c2_phonation|speaker) +
    (1|word),
  data = closing,
  REML = FALSE
)

summary(closing_lm)
```

```{r}
plot(allEffects(closing_lm))
```

## TRA and closing gesture duration

```{r}
tongue_root %>%
  filter(TRA < 3) %>%
  ggplot(aes(TRA, closing_duration, colour = c2_phonation)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(~ language)
```

```{r}
tra_closing <- lmer(
  closing_duration ~
    TRA +
    vowel +
    c2_phonation +
    (1|speaker) +
    (1|item),
  data = filter(tongue_root, TRA < 3),
  REML = FALSE
)
summary(tra_closing)
```

```{r}
plot(allEffects(tra_closing))
```


# Closing gesture velocity

```{r}
closing_velocity %>%
  filter(label == "peak1_TT") %>%
  ggplot(aes(c2_phonation, TT_velocity)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
closing_velocity %>%
  filter(label == "peak1_TD") %>%
  ggplot(aes(c2_phonation, TD_velocity)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

# Timing of closing gesture onset

```{r}
closing %>%
  ggplot(aes(rel_gon)) +
  geom_density()
```

```{r}
closing %>%
  ggplot(aes(rel_gon, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r}
closing %>%
  ggplot(aes(rel_gon, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(c2_place ~ vowel)
```

```{r}
closing %>%
  ggplot(aes(rel_gon, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(. ~ language)
```

```{r}
closing %>%
  group_by(speaker) %>%
  mutate(rel_gon = scale(rel_gon)) %>%
  ggplot(aes(rel_gon, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(. ~ language)
```

```{r}
closing %>%
  group_by(speaker) %>%
  mutate(rel_gon = scale(rel_gon)) %>%
  ggplot(aes(rel_gon, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r}
closing %>%
  group_by(speaker) %>%
  mutate(rel_gon = scale(rel_gon)) %>%
  ggplot(aes(rel_gon)) +
  geom_density()
```

```{r}
closing %>%
  group_by(speaker) %>%
  mutate(rel_gon = scale(rel_gon)) %>%
  ggplot(aes(c2_phonation, rel_gon, fill = c2_phonation)) +
  geom_boxplot()
```

```{r}
closing %>%
  group_by(speaker) %>%
  mutate(rel_gon = scale(rel_gon)) %>%
  filter(rel_gon < 3, rel_gon > -3) %>%
  ggplot(aes(c2_phonation, rel_gon, fill = c2_phonation)) +
  geom_boxplot()
```

```{r}
closing %>%
  ggplot(aes(c2_phonation, rel_gon, fill = c2_phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
rel_gon_lm <- lmer(
  rel_gon ~
    c2_phonation +
    vowel *
    c2_place +
#    language +
    (1 + c2_phonation|speaker) +
    (1|item),
  data = closing
)
summary(rel_gon_lm)
```

```{r}
plot(allEffects(rel_gon_lm))
```

