---
title: "Exploration of GAMMs with UTI data"
author: "Stefano Coretta"
date: "11/07/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath("../../../"))
library(tidyverse)
library(tidymv)
theme_set(theme_bw())
library(rticulate)
library(stringr)
library(itsadug)
options(contrasts = rep("contr.treatment", 2))
```

```{r}
columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
)

languages <- read_csv("voicing-effect/stimuli/languages.csv")
words <- read_csv("voicing-effect/stimuli/nonce.csv")

tongue <- read_aaa("voicing-effect/results/ultrasound/it01-tongue-cart.tsv", columns) %>%
    separate(label, c("gesture", "position")) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)

tongue.mm <- read_aaa("voicing-effect/results/ultrasound/it01-tongue-pol-mm.tsv", columns, coordinates = "polar") %>%
    separate(label, c("gesture", "position")) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)

tongue.mm.5 <- read_aaa("voicing-effect/results/ultrasound/it05-tongue-pol-mm.tsv", columns, coordinates = "polar") %>%
    separate(label, c("gesture", "position")) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    plot_tongue(geom = "path", alpha = 0.5) +
    aes(group = rec.date) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    plot_tongue(geom = "path", alpha = 0.5) +
    aes(group = rec.date, colour = c2_phonation) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    plot_tongue(alpha = 0.5) +
    aes(group = rec.date) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    plot_tongue(geom = "point", size = 0.5) +
    aes(group = rec.date) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    ggplot(aes(fan.line, Y, group = rec.date)) +
    geom_path(alpha = 0.5) +
    facet_grid(c2_place ~ vowel) +
    scale_x_reverse()
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    ggplot(aes(fan.line, Y, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    facet_grid(c2_place ~ vowel) +
    scale_x_reverse()
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    ggplot(aes(fan.line, Y, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) +
    facet_grid(c2_place ~ vowel) +
    scale_x_reverse()
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    ggplot(aes(fan.line, Y, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) +
    scale_x_reverse()
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    ggplot(aes(X, Y, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) 
```

```{r}
tongue.pol %>%
    filter(gesture == "max") %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) 
```

```{r}
tongue.mm %>%
    filter(theta < 3.7) %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) 
```

```{r}
tongue.mm.5 %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) 
```

```{r}
tongue.mm.5 %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_point(alpha = 0.5) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue.pol %>%
    filter(gesture == "max", vowel != "u") %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) 
```

```{r}
tongue.pol %>%
    filter(gesture == "max") %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue.max <- tongue %>%
    filter(gesture == "max") %>%
    mutate(fan.line.rev = -fan.line) %>%
    arrange(rec.date, fan.line.rev) %>%
    create_event_start("rec.date") %>%
    mutate(
        c2_phonation.ord = ordered(c2_phonation, levels = c("voiceless", "voiced")),
        c2_place.ord = ordered(c2_place, levels = c("coronal", "velar")),
        vowel.ord = ordered(vowel, levels = c("a", "o", "u")),
        place.vow.phon = interaction(c2_place, vowel, c2_phonation),
        place.vow.phon.ord = ordered(place.vow.phon, levels = c("coronal.a.voiceless", "coronal.a.voiced", "coronal.o.voiceless", "coronal.o.voiced", "coronal.u.voiceless", "coronal.u.voiced", "velar.a.voiceless", "velar.a.voiced", "velar.o.voiceless", "velar.o.voiced", "velar.u.voiceless", "velar.u.voiced"))
    )
```


```{r}
tongue.m1 <- bam(
    Y ~
#        c2_phonation.ord +
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "ML"
)

summary(tongue.m1)

tongue.m1.null <- bam(
    Y ~
#        c2_phonation.ord +
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
#        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "ML"
)

compareML(tongue.m1, tongue.m1.null)

tongue.m1.2 <- bam(
    Y ~
#        c2_phonation.ord +
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr") +
        s(fan.line.rev, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = filter(tongue.max, vowel != "u"),
    method = "fREML"
)

tongue.m1.3 <- bam(
    Y ~
#        c2_phonation.ord +
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "fREML"
)

compareML(tongue.m1.2, tongue.m1.3)

rho <- start_value_rho(tongue.m1)

tongue.m1.ar <- bam(
    Y ~
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "ML",
    rho = rho,
    AR.start = tongue.max$start.event
)

summary(tongue.m1.ar)

tongue.m2 <- bam(
    Y ~
        c2_phonation.ord +
        vowel.ord +
        c2_place.ord +
        s(fan.line, bs = "cr") +
        s(fan.line, by = c2_phonation.ord, bs = "cr") +
        s(fan.line, by = vowel.ord, bs = "cr") +
        s(fan.line, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "ML"
)

compareML(tongue.m2, tongue.m1)

summary(tongue.m1.2)
```

Adding a parametric term `c2_phonation.ord` does not improve the model.

```{r}
acf_plot(resid(tongue.m1), split_by=list(tongue.max$rec.date))
acf_resid(tongue.m1.ar, split_pred = "AR.start")
```


```{r}
plot_gamsd(
    tongue.m1.ar,
    "fan.line.rev",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
plot_gamsd(
    tongue.m1.2,
    "fan.line.rev",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
tongue.m3 <- bam(
    Y ~
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr") +
        s(fan.line.rev, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = tongue.max,
    method = "fREML"
)

summary(tongue.m3)

tongue.m3.2 <- bam(
    Y ~
        vowel.ord +
        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
        s(fan.line.rev, by = vowel.ord, bs = "cr") +
        s(fan.line.rev, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "fREML"
)

compareML(tongue.m3, tongue.m3.2)
```

```{r}
acf_plot(resid(tongue.m3), split_by=list(tongue.max$rec.date))
```


```{r}
plot_gamsd(
    tongue.m3,
    "fan.line.rev",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
tongue.m4 <- bam(
    Y ~
        vowel.ord +
        c2_place.ord +
        s(X, bs = "cr") +
        s(X, by = c2_phonation.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, by = c2_place.ord, bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = tongue.max,
    method = "fREML"
)

rho <- start_value_rho(tongue.m4)

tongue.m4.ar <- bam(
    Y ~
        vowel.ord +
        c2_place.ord +
        s(X, bs = "cr") +
        s(X, by = c2_phonation.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr") +
        s(X, by = c2_place.ord, bs = "cr"),
    data = tongue.max,
    method = "fREML",
    rho = rho,
    AR.start = tongue.max$start.event
)

summary(tongue.m4)
summary(tongue.m4.ar)
```

```{r}
plot_gamsd(
    tongue.m4,
    "X",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
plot_gamsd(
    tongue.m4.ar,
    "X",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
tongue.max.a <- tongue.max %>%
    filter(vowel == "a", c2_place == "coronal")
```

```{r}
tongue.m5 <- bam(
    Y ~
#        c2_place.ord +
        s(fan.line.rev, bs = "cr") +
        s(fan.line.rev, by = c2_phonation.ord, bs = "cr") +
#        s(fan.line.rev, by = c2_place.ord, bs = "cr") +
        s(fan.line.rev, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = tongue.max.a,
    method = "fREML"
)

summary(tongue.m5)
```

```{r}
plot_gamsd(
    tongue.m5,
    "fan.line.rev",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
tongue.pol <- read_aaa("voicing-effect/results/ultrasound/it01-tongue-pol.tsv", columns, coordinates = "polar") %>%
    separate(label, c("gesture", "position")) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)
```

```{r}
tongue.pol %>%
    filter(gesture == "max") %>%
    ggplot(aes(theta, radius, group = rec.date, colour = c2_phonation)) +
    geom_path(alpha = 0.5) +
    facet_grid(c2_place ~ vowel)
```

```{r}
tongue.max.pol <- tongue.pol %>%
    filter(gesture == "max") %>%
    arrange(rec.date, desc(fan.line)) %>%
    create_event_start("rec.date") %>%
    mutate(
        c2_phonation.ord = ordered(c2_phonation, levels = c("voiceless", "voiced")),
        c2_place.ord = ordered(c2_place, levels = c("coronal", "velar")),
        vowel.ord = ordered(vowel, levels = c("a", "o", "u")),
        phon.vowel = interaction(c2_phonation, vowel),
        phon.vowel.ord = as.ordered(phon.vowel)
    )
```

```{r}
tongue.m6 <- bam(
    radius ~
        vowel.ord +
        c2_place.ord +
        s(theta, bs = "cr") +
        s(theta, by = c2_phonation.ord, bs = "cr") +
        s(theta, by = vowel.ord, bs = "cr") +
        s(theta, by = c2_place.ord, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", m = 1, k = 5) +
        s(theta, phon.vowel.ord, bs = "fs", xt = "cr", m = 1, k = 5),
    data = filter(tongue.max.pol, vowel != "u"),
    method = "fREML"
)

summary(tongue.m6)
```

```{r}
plot_gamsd(
    tongue.m6,
    "theta",
    list(c2_phonation.ord = c("voiceless", "voiced")),
    list(vowel.ord = "a")
)
```

```{r}
tongue <- tongue %>%
    mutate(
        radius = sqrt(X^2 + Y^2),
        theta = atan2(Y, X)
    )
```

```{r}
tongue %>%
    filter(gesture == "max") %>%
    ggplot(aes(theta, radius, colour = c2_phonation)) +
    geom_point()
```

```{r}
tongue.mm.5 <- tongue.mm.5 %>%
    arrange(rec.date, desc(fan.line)) %>%
    create_event_start("rec.date") %>%
    mutate(
        c2_phonation.ord = ordered(c2_phonation, levels = c("voiceless", "voiced")),
        c2_place.ord = ordered(c2_place, levels = c("coronal", "velar")),
        vowel.ord = ordered(vowel, levels = c("a", "o", "u")),
        place.vow.phon = interaction(c2_place, vowel, c2_phonation),
        place.vow.phon.ord = ordered(place.vow.phon, levels = c("coronal.a.voiceless", "coronal.a.voiced", "coronal.o.voiceless", "coronal.o.voiced", "coronal.u.voiceless", "coronal.u.voiced", "velar.a.voiceless", "velar.a.voiced", "velar.o.voiceless", "velar.o.voiced", "velar.u.voiceless", "velar.u.voiced"))
    )
```

```{r}
tongue.m7 <- bam(
    radius ~
        vowel.ord +
#        c2_place.ord +
        s(theta, bs = "cr") +
        s(theta, by = c2_phonation.ord, bs = "cr") +
        s(theta, by = vowel.ord, bs = "cr") +
#        s(theta, by = c2_place.ord, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = filter(tongue.mm.5, c2_place == "coronal"),
    method = "fREML"
)

summary(tongue.m7)
```

```{r}
plot_gamsd(
    tongue.m7,
    "theta",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

```{r}
tongue.pol.mm <- rbind(tongue.max.pol[,1:31], tongue.mm.5[,1:31])
```

```{r}
tongue.m10 <- bam(
    radius ~
        vowel.ord +
        c2_place.ord +
        s(theta, bs = "cr") +
        s(theta, by = c2_phonation.ord, bs = "cr") +
        s(theta, by = vowel.ord, bs = "cr") +
        s(theta, by = c2_place.ord, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", m = 1, k = 5) +
        s(theta, speaker, bs = "fs", xt = "cr", m = 1, k = 5),
    data = tongue.pol.mm,
    method = "fREML"
)

summary(tongue.m10)
```

```{r}
plot_gamsd(
    tongue.m10,
    "theta",
    list(c2_phonation.ord = c("voiceless", "voiced")),
    list(vowel.ord = "a", c2_place.ord = "coronal")
)
```

```{r}
tongue.it01.pol.m1 <- bam(
    radius ~
        vowel.ord +
        c2_place.ord +
        s(theta, bs = "cr") +
        s(theta, by = c2_phonation.ord, bs = "cr") +
        s(theta, by = vowel.ord, bs = "cr") +
        s(theta, by = c2_place.ord, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = tongue.max.pol
)

rho <- start_value_rho(tongue.it01.pol.m1)

tongue.it01.pol.m1.ar <- bam(
    radius ~
        vowel.ord +
        c2_place.ord +
        s(theta, bs = "cr") +
        s(theta, by = c2_phonation.ord, bs = "cr") +
        s(theta, by = vowel.ord, bs = "cr") +
        s(theta, by = c2_place.ord, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", m = 1, k = 5),
    data = tongue.max.pol,
    rho = rho,
    AR.start = tongue.max.pol$start.event
)

summary(tongue.it01.pol.m1)
summary(tongue.it01.pol.m1.ar)
```

```{r}
plot_gamsd(
    tongue.it01.pol.m1.ar,
    "theta",
    list(c2_phonation.ord = c("voiceless", "voiced"))
)
```

