---
title: "Bayesial modelling of gestures"
author: "Stefano Coretta"
date: "16/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))

library(tidyverse)
theme_set(theme_minimal())
scale_fill_discrete <- function(...) scale_fill_brewer(..., type = "qual")
scale_colour_discrete <- function(...) scale_colour_brewer(..., type = "qual")
library(brms)
library(bayesplot)
library(tidybayes)

library(coretta2018itapol)
data("token_measures")

gestures <- token_measures %>%
  filter(c1_phonation == "voiceless", !is.na(c1_rel), !is.na(GONS), !is.na(max), GONS > 0, max > 0) %>%
  mutate(
    speech_rate_c = speech_rate - mean(speech_rate),
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced")),
    c2_place = factor(c2_place, levels = c("coronal", "velar")),
    vowel = factor(vowel, levels = c("a", "o", "u")),
    gons_max = (max - GONS) * 1000,
    rel_gons = (GONS - c1_rel) * 1000,
    mid = (NOFF - NONS) + NONS,
    rel_mid = (mid - c1_rel) * 1000,
    rel_noff = (NOFF - c1_rel) * 1000
  ) %>%
  mutate_if(is_character, as_factor)

gest_gmax <- filter(gestures, gons_max > 10)
```

# GONS to MAX

```{r gons-max-bm}
priors <- c(
  set_prior("normal(130, 75)", class = "Intercept"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 10)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 10)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_placevelar"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced:vowelo"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced:vowelu"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced:c2_placevelar"),
  set_prior("normal(0, 50)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

gons_max_bm <- brm(
  gons_max ~
    c2_phonation +
    c2_place +
    vowel +
    c2_phonation:c2_place +
    c2_phonation:vowel +
    speech_rate_c +
    (1|speaker) +
    (1|item),
  prior = priors,
  data = gest_gmax,
  cores = 4,
  file = "./voicing-effect/data/cache/gons_max_bm"
)
```

```{r gons-max-summary}
summary(gons_max_bm)
```

```{r gos-max-intervals}
gons_max_draws <- gons_max_bm %>%
  gather_draws(b_c2_phonationvoiced, b_c2_placevelar, b_vowelo, b_vowelu)

gons_max_draws %>%
  ungroup() %>%
  mutate(.variable = factor(
    .variable,
    levels = c("b_vowelu", "b_vowelo", "b_c2_placevelar", "b_c2_phonationvoiced")
  )) %>%
  ggplot(aes(.value, .variable)) +
  # annotate("rect", xmin = -10, xmax = 10, ymin = -Inf, ymax = Inf, alpha = 0.5) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(position = position_nudge(y = -0.2), .width = c(0.66, 0.98)) +
  scale_x_continuous(breaks = seq(-50, 25, 5)) +
  scale_y_discrete(labels = c("Vowel = /u/", "Vowel = /o/", "Place = velar", "Voicing = voiced")) +
  scale_color_brewer() +
  labs(
    x = "Difference in GONS to MAX (ms)",
    y = element_blank()
  ) +
  theme(panel.grid.minor = element_blank())
```

# C1 release to GONS

```{r rel-gons-bm}
priors <- c(
  set_prior("normal(0, 200)", class = "Intercept"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 10)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 10)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_placevelar"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced:vowelo"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced:vowelu"),
  set_prior("normal(0, 10)", class = "b", coef = "c2_phonationvoiced:c2_placevelar"),
  set_prior("normal(0, 50)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

rel_gons_bm <- brm(
  rel_gons ~
    c2_phonation +
    c2_place +
    vowel +
    c2_phonation:c2_place +
    c2_phonation:vowel +
    speech_rate_c +
    (1|speaker) +
    (1|item),
  prior = priors,
  data = gestures,
  cores = 4,
  file = "./voicing-effect/data/cache/rel_gons_bm"
)
```

```{r rel-gons-summary}
summary(rel_gons_bm)
```

```{r rel-gons-intervals}
rel_gons_draws <- rel_gons_bm %>%
  gather_draws(b_c2_phonationvoiced, b_c2_placevelar, b_vowelo, b_vowelu)

rel_gons_draws %>%
  ungroup() %>%
  mutate(.variable = factor(
    .variable,
    levels = c("b_vowelu", "b_vowelo", "b_c2_placevelar", "b_c2_phonationvoiced")
  )) %>%
  ggplot(aes(.value, .variable)) +
  # annotate("rect", xmin = -10, xmax = 10, ymin = -Inf, ymax = Inf, alpha = 0.5) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(position = position_nudge(y = -0.2), .width = c(0.66, 0.98)) +
  scale_x_continuous(breaks = seq(-50, 25, 5)) +
  scale_y_discrete(labels = c("Vowel = /u/", "Vowel = /o/", "Place = velar", "Voicing = voiced")) +
  scale_color_brewer() +
  labs(
    x = "Difference in release to GONS (ms)",
    y = element_blank()
  ) +
  theme(panel.grid.minor = element_blank())
```

