---
title: "Tongue root"
author: "Stefano Coretta"
date: "19/08/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
theme_set(theme_minimal())
library(itsadug)
library(tidymv)
data("kinematics_series", "kinematics", package = "coretta2018itapol")
kinematics_series <- kinematics_series %>%
  filter(c1_phonation == "voiceless") %>%
  mutate(
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))
  )
kine_s <- kinematics_series %>%
  filter(TR_displacement_sm > 10, proportion < 1) %>%
  mutate(
    trp = -TR_displacement_sm + max(TR_displacement_sm),
    c2_phonation_o = ordered(c2_phonation, levels = c("voiceless", "voiced")),
    place_vow_voi_o = as.ordered(interaction(c2_place, vowel, c2_phonation))
  ) %>%
  mutate_if(is.character, as.factor)
contrasts(kine_s$c2_phonation_o) <-  "contr.treatment"
contrasts(kine_s$place_vow_voi_o) <-  "contr.treatment"
```

# Data visualisation

```{r n-trajectories}
length(table(kine_s$rec_date))
```

```{r trp-point}
kinematics_series %>%
  ggplot(aes(proportion, -TR_displacement_sm)) +
  geom_point(alpha = 0.1)
```

```{r points-filtered}
kine_s %>%
  ggplot(aes(proportion, trp)) +
  geom_point(alpha = 0.1)
```

```{r points-voicing}
kine_s %>%
  ggplot(aes(proportion, trp, colour = c2_phonation)) +
  geom_point(alpha = 0.1)
```

```{r smooth-voicing}
kine_s %>%
  ggplot(aes(proportion, trp, colour = c2_phonation)) +
  geom_point(alpha = 0.1) +
  geom_smooth()
```

```{r smooth-voicing-2}
kine_s %>%
  ggplot(aes(proportion, trp, colour = c2_phonation)) +
  geom_smooth()
```

The smooths show advancement of the tongue root of 1.5 mm in vowels followed by voiced stops and a 1 mm advancement in vowels followed by voiceless stops.

```{r smooths-facet}
kine_s %>%
  ggplot(aes(proportion, trp, colour = c2_phonation)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 10)) +
  facet_grid(vowel ~ c2_place)
```

```{r trajectories}
kine_s %>%
  ggplot(aes(proportion, trp, group = reorder(rec_date, vowel_duration), colour = vowel_duration)) +
  geom_path(alpha = 0.5) +
  scale_colour_distiller(type = "seq", palette = "YlGn") +
  theme_dark()
```

```{r trajectories-facet}
kine_s %>%
  ggplot(aes(proportion, trp, group = reorder(rec_date, vowel_duration), colour = vowel_duration)) +
  geom_path(alpha = 0.5) +
  facet_grid(vowel ~ c2_place) +
  scale_colour_distiller(type = "seq", palette = "YlGn") +
  theme_dark()
```

```{r trajectories-facet-scaled}
kine_s %>%
  group_by(speaker) %>%
  mutate(trp = scale(trp)) %>%
  ggplot(aes(proportion, trp, group = reorder(rec_date, vowel_duration), colour = vowel_duration)) +
  geom_path(alpha = 0.5) +
  facet_grid(vowel ~ c2_place) +
  scale_colour_distiller(type = "seq", palette = "YlGn") +
  theme_dark()
```

```{r trajectories-sylrate}
kine_s %>%
  ggplot(aes(proportion, trp, group = reorder(rec_date, syl_rate), colour = syl_rate)) +
  geom_path(alpha = 0.5) +
  scale_colour_distiller(type = "seq", palette = "PuRd") +
  theme_dark()
```

# Significance testing

```{r trp-gam}
trp_gam  <- bam(
  trp ~
    place_vow_voi_o +
    s(proportion) +
    s(proportion, by = place_vow_voi_o) +
    # s(vowel_duration) +
    # ti(proportion, vowel_duration) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = kine_s
)
```

```{r}
plot_smooths(trp_gam, proportion, voicing, facet_terms = place + vowel, split = list(place_vow_voi_o = c("place", "vowel", "voicing")))
```

```{r}
acf_resid(trp_gam, split_pred = list(kine_s$rec_date))
```

```{r trp-gam-2}
trp_gam_2  <- bam(
  trp ~
    s(proportion) +
    s(vowel_duration) +
    ti(proportion, vowel_duration) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = kine_s
)
```

```{r}
fvisgam(trp_gam_2, c("proportion", "vowel_duration"), rm.ranef = TRUE)
```

```{r trp-gam-3}
trp_gam_3  <- bam(
  trp ~
    c2_phonation_o +
    s(proportion) +
    s(proportion, by = c2_phonation_o) +
    s(vowel_duration) +
    ti(proportion, vowel_duration) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = kine_s
)
```

```{r}
plot_smooths(trp_gam_3, proportion, c2_phonation_o) + scale_y_continuous(breaks = seq(15, 25, 1)) + scale_color_discrete() + scale_fill_discrete()
```

```{r trp-gam-4}
trp_gam_4  <- bam(
  trp ~
    c2_phonation_o +
    s(proportion) +
    s(proportion, by = c2_phonation_o) +
    s(vowel_duration) +
    ti(proportion, vowel_duration) +
    ti(proportion, vowel_duration, by = c2_phonation_o) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = kine_s
)
```

```{r}
fvisgam(trp_gam_4, c("proportion", "vowel_duration"), cond = list(c2_phonation_o = "voiceless"), rm.ranef = TRUE, zlim = c(18.5, 23.5))
fvisgam(trp_gam_4, c("proportion", "vowel_duration"), cond = list(c2_phonation_o = "voiced"), rm.ranef = TRUE, zlim = c(18.5, 23.5))
```
