---
title: "Tongue displacement"
author: "Stefano Coretta"
date: "08/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(rticulate)
library(lme4)
library(effects)
```

# Read data

```{r read-data}
columns <- c(
  "speaker",
  "seconds",
  "rec_date",
  "prompt",
  "label",
  "TT_displacement_sm",
  "TT_velocity",
  "TT_velocity_abs",
  "TD_displacement_sm",
  "TD_velocity",
  "TD_velocity_abs",
  "TR_displacement_sm",
  "TR_velocity",
  "TR_velocity_abs"
)

speakers <- read_csv("./voicing-effect/data/datasets/speakers.csv")
stimuli <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

displacement <- list.files(
  path = "./voicing-effect/data/datasets/ultrasound/",
  pattern = "*-tongue-cart.tsv",
  full.names = TRUE
) %>%
  map_df(~read_aaa(., column_names = columns, format = "wide")) %>%
  select(speaker, rec_date, prompt, TT_displacement_sm, TD_displacement_sm, label) %>%
  mutate(word = word(prompt, 2)) %>%
  mutate(label = str_sub(label, 1, nchar(label) - 3)) %>%
  filter(label %in% c("GONS", "peak1")) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate_if(is.character, as.factor)

displacement_tt <- displacement %>%
  filter(c2_place == "coronal", speaker != "it12") %>%
  select(-TD_displacement_sm) %>%
  spread(label, TT_displacement_sm)

displacement_td <- displacement %>%
  filter(c2_place == "velar", speaker != "it12") %>%
  select(-TT_displacement_sm) %>%
  spread(label, TD_displacement_sm)

displacement <- bind_rows(displacement_tt, displacement_td) %>%
  mutate(
    displacement = peak1 - GONS
  ) %>%
  filter(displacement > 0) %>%
  na.omit()
```

# Data plotting

```{r}
displacement %>%
  ggplot(aes(vowel, displacement, fill = c2_phonation)) +
  geom_boxplot() +
  facet_grid(language ~ c2_place)
```

