---
title: "Velocity"
author: "Stefano Coretta"
date: "14/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(coretta2018itapol)
library(mgcv)
library(tidymv)
library(akima)
library(lmerTest)

data("kinematics_series")

kinematics_series <- kinematics_series %>%
  filter(c1_phonation == "voiceless")

velocity_tt <- kinematics_series %>%
  filter(c2_place == "coronal") %>%
  mutate(velocity = TT_velocity, velocity_abs = TT_velocity_abs)
velocity_td <- kinematics_series %>%
  filter(c2_place == "velar") %>%
  mutate(velocity = TD_velocity, velocity_abs = TD_velocity_abs)

velocity <- rbind(velocity_tt, velocity_td) %>%
  mutate(
    proportion = (seconds - v_onset) / (v_offset - v_onset),
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))
  ) %>%
  filter(rec_date != "28/07/2017 15:40:44") %>% # remove wrong token
  mutate(
    voicing = ordered(c2_phonation, levels = c("voiceless", "voiced")),
    place_vow_voi = interaction(c2_place, vowel, c2_phonation),
    place_vow_voi = as.ordered(place_vow_voi),
    speaker_voi = interaction(speaker, c2_phonation),
    speaker_voi = as.ordered(speaker_voi),
    speech_rate_c = syl_rate - mean(syl_rate)
  ) %>%
  mutate_if(is.character, as.factor) %>%
  droplevels()

contrasts(velocity$voicing) <- "contr.treatment"
contrasts(velocity$place_vow_voi) <- "contr.treatment"
contrasts(velocity$speaker_voi) <- "contr.treatment"
```

# Plots

```{r velocity}
velocity %>%
  ggplot(aes(proportion, velocity)) +
  geom_point(alpha = 0.5) +
  facet_grid(~ c2_phonation)
```

```{r velocity-smooth}
velocity %>%
  ggplot(aes(proportion, velocity)) +
  geom_point(alpha = 0.05) +
  geom_smooth() +
  facet_grid(~ c2_phonation)
```

```{r velocity-smooth-2}
velocity %>%
  ggplot(aes(proportion, velocity, colour = c2_phonation, linetype = c2_phonation)) +
  geom_smooth()
```

```{r velocity-abs-smooth}
velocity %>%
  ggplot(aes(proportion, velocity_abs)) +
  geom_point(alpha = 0.05) +
  geom_smooth() +
  facet_grid(~ c2_phonation)
```

```{r velocity-abs-smooth-2}
velocity %>%
  ggplot(aes(proportion, velocity_abs, colour = c2_phonation, linetype = c2_phonation)) +
  geom_smooth()
```

```{r velocity-abs-0.8}
velocity %>%
  filter(proportion < 0.8) %>%
  ggplot(aes(proportion, velocity_abs, colour = c2_phonation, linetype = c2_phonation)) +
  geom_smooth()
```

```{r velocity-abs-place-vow}
velocity %>%
  ggplot(aes(proportion, velocity_abs, colour = c2_phonation, linetype = c2_phonation)) +
  geom_smooth() +
  facet_grid(vowel ~ c2_place)
```

```{r velocity-abs-place-vow-0.8}
velocity %>%
  filter(proportion < 0.8) %>%
  ggplot(aes(proportion, velocity_abs, colour = c2_phonation, linetype = c2_phonation)) +
  geom_smooth() +
  facet_grid(vowel ~ c2_place)
```

```{r velocity-abs-vow}
velocity %>%
  ggplot(aes(proportion, velocity_abs, colour = vowel, linetype = vowel)) +
  geom_smooth(method = "loess") +
  facet_grid(. ~ c2_place)
```

# Modelling

```{r vel-gam}
vel_gam <- bam(
  velocity_abs ~
    place_vow_voi +
    s(proportion) +
    s(proportion, by = place_vow_voi) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = velocity
)
```

```{r vel-gam-summary}
summary(vel_gam)
```

```{r vel-gam-plot}
plot_smooths(vel_gam, proportion, comparison = voicing, facet_terms = place + vowel, split = list(place_vow_voi = c("place", "vowel", "voicing")))
```

```{r vel-gam-2}
vel_gam_2 <- bam(
  velocity_abs ~
    voicing +
    s(proportion) +
    s(speech_rate_c) +
    s(proportion, by = voicing) +
    ti(proportion, speech_rate_c) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = velocity
)
```

```{r vel-gam-2-summary}
summary(vel_gam_2)
```

```{r vel-gam-2-plot}
plot_smooths(vel_gam_2, proportion, comparison = voicing)
```

## Interpolation

```{r interpolate}
vel_25 <- NULL

for (traj in 1:length(levels(velocity$rec_date))) {
  rec <- levels(velocity$rec_date)[traj]
  
  traj_xy <- velocity %>%
    filter(rec_date == rec)
  
  interp_xy <- aspline(traj_xy$proportion, traj_xy$velocity_abs, 0.25)

  vel_25 <- c(vel_25, interp_xy$y)
}

velocity_25 <- velocity %>%
  group_by(rec_date) %>%
  filter(seconds == min(seconds)) %>%
  ungroup() %>%
  unique() %>%
  mutate(vel_25 = vel_25)
```

```{r}
velocity_25 %>%
  ggplot(aes(vel_25, fill = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r}
velocity_25 %>%
  ggplot(aes(c2_phonation, vel_25, fill = c2_phonation)) +
  geom_boxplot()
```

```{r}
vel_25_lm <- lmer(
  vel_25 ~
    c2_phonation *
    c2_place *
    vowel +
    (1|speaker) +
    (1|item),
  data = velocity_25
)

summary(vel_25_lm)
```

