---
title: "A new method for modelling electroglottographic data"
author: "Stefano Coretta"
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
bibliography: linguistics
biblio-style: unified
mainfont: Lato
fontsize: 12pt
papersize: a4
indent: true
header-includes:
- \usepackage{cleveref}
params:
  version: 0.1
  version-date: "2019/04/30"
---

```{r setup, include=FALSE}
library(here)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here())
library(tidyverse)
theme_set(theme_minimal())
library(coretta2017egg)
data("wavegram_p")
library(coretta2018itapol)
data("wavegram")
```

# Pilot study

Synchronised audio and electroglottographic (EGG) data were obtained from 5 trained phoneticians, who were asked to produce sustained tokens of /a/ with modal and breathy voice.
The data was collected using a Glottal Enterprises EG2-PCX2 electroglottograph and a Movo LV4-O2 Lavalier microphone, at a sample rate of 44100 Hz (16-bit).
The acquisition of the signals was controlled with Audacity running on a MacBook Pro (Retina, 13-inch, Mid 2014).
The placement of the electrodes strap was checked with the height indicator on the EGG unit.
Each participant uttered 10 consecutive tokens of a sustained /a/ in modal voice, followed by 10 tokens of a sustained breathy /a/.
All subsequent data processing was performed in Praat \citep{boersma2018}.
The onset and offset of each token were detected with an automatic procedure which finds voiced and unvoiced intervals (`To TextGrid (vuv)`).
The dEGG wavegram data was extracted from the first 8 glottal cycles of a 500 ms window centred around the mid-point of each token.
From each glottal cycle, the relative amplitude of the dEGG signal was extracted every 10 samples.

A generalised additive mixed model (GAMM) was fitted to the data to statistically assess differences in vocal fold activity between modal and breathy voicing.
The following terms were included: the amplitude of the dEGG signal as the outcome variable, a factor with language and phonation as a parametric term, a smooth over the normalised time of the beginning of the glottal cycle (as the proportion of the time relative to the entire token duration) and one over the normalised time of the sample within the glottal cycle (as the proportion of the time relative to the duration of the glottal cycle), two difference smooth over normalised time of the glottal cycle onset and normalised sample time using a by-variable with the language/phonation factor, a tensor product interaction between normalised cycle time and normalised sample time and the same tensor product interaction with a language/phonation by-variable.
Finally, by-speaker differences were modelled with a by-speaker factor smooth over normalised cycle time.
A first-order autoregressive (AR1) model was included to deal with the relatively high auto-correlation in the residuals.

\Cref{f:xxx} shows the modelled wavegrams of the modal and breathy tokens.
Since the tokens were produced with sustained phonation, no appreciable change within each wavegram can be observed.
However, the comparison of the wavegram of modal voice with that of breathy voice reveals clear differences.
As a general trend, the dEGG maximum is achieved later within the glottal cycle in breathy voicing relative to modal voicing.
This is compatible with the lower CQ values observed in breathy voicing.
Moreover, differences in velocity of closing and opening movements of the folds are signalled by the relative widths of the red-coloured (around the dEGG maximum) and the blue-coloured bands (around the dEGG minimum).
While in modal voicing the blue band is wider, the red band is in breathy voice, indicating that the velocity into and out of the beginning of the closed phase is slower in breathy voicing.

# Wavegram of vowels followed by voiceless vs. voiced stops

This section further illustrates the use of wavegram GAMs by discussing a dynamic analysis of changes in vocal folds activity during the production of vowels followed by voiceless vs. voiced stops in Italian and Polish.
EGG data was obtained from 9 Italian speakers and 6 Polish speakers.
<!-- experimental info on material -->
The procedures for data processing and analysis were the same as with the pilot study, with the exception that data was extracted from every glottal cycle within the whole duration of the vowel.
The vowel onset and offset were identified as the appearance and disappearance of higher formant structure respectively \citep{machac2009}.

\Cref{f:xxx} shows the modelled wavegrams of vowels followed by voiceless (left) and voiced stops (right), in Italian (top) and Polish (bottom).
The wavegrams indicate that vocal folds activity changes towards the end of the vowel if the following consonant is voiceless, both in Italian and Polish.
The glottal activity along the second half of vowels followed by voiced stops is, on the other hand, more stable.
Moreover, the change in activity is initiated earlier in Italian (at around 60% into the vowel) than in Polish (at about 80%).
What the wavegrams show is that glottal opening increases towards the end of the vowel, in anticipation of the open glottis typical of voiceless stops (and consonants more in general).

Another difference between the two languages concerns the initial voiceless stop (/p/).
The change observed between 50 and 70% into the glottal cycle at the beginning of the vowel, which indicates a transition from a more spread glottis, is more extreme in Polish than in Italian.
This means that phonation at vowel onset is slightly breathier in the former.
Such difference is compatible with the finding that Polish voiceless stops have on average a longer VOT than Italian stops.
<!-- include reference!!! -->

The observation of increased glottal opening in the production of vowels followed by voiceless stops in Italian is further compatible with the reported presence of pre-aspiration (breathy or voiceless) in Italian geminate stops \citep{stevens2004, stevens2004a, stevens2010, stevens2010b, stevens2014a}.
Increased glottal spreading during vocal fold vibration is the logical precursor of voiceless pre-aspiration.
The fact that voiceless pre-aspiration is not fully developed in Italian singleton voiceless stops offers interesting insights concerning the duration of voiceless stops and the emergence of pre-aspiration.

It is known that voiceless stops have longer closure durations than voiced stops.
\citet{lisker1974} argues that, in English voiceless stops, closure occurs not long after the spreading gesture is initiated in order to avoid the emergence of full pre-aspiration.
There are, however, varieties of English with pre-aspiration in stops and fricatives \citep{gordeeva2007, nance2013, hejna2015a}.
The question arises as to how glottal spreading in vowels in the context of voiceless stops can lead to the emergence of pre-aspiration in some cases.
One of the common conceptions is that pre-aspiration arises when closure duration decreases while glottal spread remains.
<!-- references in Stevens 2014 -->
\citet{nichasaide1985}, however, claims that the appearance of pre-aspiration (in the form of glottal spread before stop closure) diachronically precedes closure shortening.
\citet{stevens2014} further present experimental evidence from Italian that pre-aspiration and closure shorting are independent.
Moreover, the presence of pre-aspiration increased the total duration of the VC sequence.

What can be learnt from this is that, once breathyness/pre-aspiration arises, there are two possible scenarios: according to one possible path, as noted by \citet{lisker1974}, pre-aspiration is prevented by achieving stop closure earlier (thus increasing the stop closure duration); according to the other path, pre-aspiration can be enhanced, with subsequent closure shortening, as in the arguments by \citet{nichasaide1985} and \citet{stevens2014}.
