---
title: "Icelandic data"
author: "Stefano Coretta"
date: "29/07/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_bw())
```

# Read data

```{r read-data, message=FALSE}
words <- read_csv("./icelandic/data/datasets/words.csv")

is_durations <- read_csv("./icelandic/data/datasets/measurements.csv") %>%
  inner_join(y = words) %>%
  mutate(
    aspiration = factor(aspiration, levels = c("non-aspirated", "aspirated")),
    syllables = factor(syllables, levels = c("mono", "di")),
    height = factor(height, levels = c("low", "mid", "high", "diphthong")),
    syl_rate = ifelse(
      syllables == "mono",
      5 / sentence_duration,
      6 / sentence_duration
    )
  ) %>%
  mutate_if(is.character, as.factor)
```

# Summaries

```{r count}
is_durations %>%
  ggplot(aes(sequence, fill = aspiration)) +
  geom_bar(position = position_dodge()) +
  facet_grid(syllables ~ .)
```

```{r count-x-stop}
is_durations %>%
  filter(x_stop == "yes") %>%
  ggplot(aes(sequence, fill = aspiration)) +
  geom_bar(position = position_dodge()) +
  facet_grid(syllables ~ .)
```

# Descriptive statistics

```{r rr-density}
is_durations %>%
  ggplot(aes(rr)) +
  geom_density() +
  geom_rug()
```

```{r rr-density-vow}
is_durations %>%
  ggplot(aes(rr, fill = vowel)) +
  geom_density(alpha = 0.5) +
  geom_rug() +
  facet_grid(vowel ~ .)
```

```{r rr-box-vowel}
is_durations %>%
  ggplot(aes(vowel, rr, fill = vowel)) +
  geom_boxplot()
```

```{r rr-box-height}
is_durations %>%
  ggplot(aes(height, rr, fill = height)) +
  geom_boxplot()
```

```{r rr-box-frontness}
is_durations %>%
  ggplot(aes(frontness, rr, fill = frontness)) +
  geom_boxplot()
```

```{r rr-box-roundness}
is_durations %>%
  ggplot(aes(roundness, rr, fill = roundness)) +
  geom_boxplot()
```

```{r rr-box-place}
is_durations %>%
  ggplot(aes(place, rr, fill = place)) +
  geom_boxplot()
```

```{r rr-box-c1}
is_durations %>%
  ggplot(aes(c1_manner, rr, fill = c1_manner)) +
  geom_boxplot()
```

```{r rr-box-c1-x-stop}
is_durations %>%
  filter(x_stop == "yes") %>%
  ggplot(aes(c1_manner, rr, fill = c1_manner)) +
  geom_boxplot()
```

```{r rr-box-c1-x-stop-2}
is_durations %>%
  filter(x_stop == "yes", height != "diphthong") %>%
  ggplot(aes(c1_manner, rr, fill = c1_manner)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.2, width = 0.3)
```

```{r rr-aspiration}
is_durations %>%
  filter(x_stop == "yes") %>%
  ggplot(aes(rr, fill = aspiration)) +
  geom_density(alpha = 0.5) +
  geom_rug()
```

```{r rr-aspiration-all}
is_durations %>%
  filter(x_stop == "yes") %>%
  ggplot(aes(rr, fill = aspiration)) +
  geom_density(alpha = 0.5) +
  facet_grid(syllables ~ sequence) +
  geom_rug()
```

```{r rr-box}
is_durations %>%
  filter(x_stop == "yes") %>%
  ggplot(aes(aspiration, rr)) +
  geom_boxplot() +
  facet_grid(syllables ~ sequence)
```

```{r rr-box-jit}
is_durations %>%
  filter(x_stop == "yes") %>%
  ggplot(aes(aspiration, rr, fill = aspiration)) +
  geom_boxplot(alpha = 0.6) +
  geom_jitter(alpha = 0.2, width = 0.3) +
  facet_grid(syllables ~ sequence)
```

```{r rr-stop}
is_durations %>%
  filter(x_stop == "yes", c1_manner == "stop") %>%
  ggplot(aes(aspiration, rr, fill = aspiration)) +
  geom_boxplot(alpha = 0.6) +
  geom_jitter(alpha = 0.2, width = 0.3) +
  facet_grid(syllables ~ sequence)
```

