---
title: "English Release-to-Release"
author: "Stefano Coretta"
date: "13/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(brms)
library(bayesplot)
library(tidybayes)
library(broom.mixed)
library(coretta2019eng)
data("eng_durations")
```

```{r remove-na}
eng_durations_rr <- na.omit(eng_durations)
```

# Plot data

```{r rr-dens}
eng_durations %>%
  ggplot(aes(rel_rel)) +
  geom_density()
```

```{r rr}
eng_durations %>%
  ggplot(aes(rel_rel, fill = voicing)) +
  geom_density(alpha = 0.5, color = NA) +
  facet_grid(num_syl ~ .) +
  scale_x_continuous(breaks = seq(100, 450, 50))
```

```{r rr-box}
eng_durations %>%
  ggplot(aes(num_syl, rel_rel, fill = voicing)) +
  geom_boxplot()
```

```{r rr-vowel}
eng_durations %>%
  ggplot(aes(rel_rel, fill = vowel)) +
  geom_density(alpha = 0.5, color = NA) +
  facet_grid(num_syl ~ .) +
  scale_x_continuous(breaks = seq(100, 450, 50))
```

```{r rr-place}
eng_durations %>%
  ggplot(aes(rel_rel, fill = place)) +
  geom_density(alpha = 0.5, color = NA) +
  facet_grid(num_syl ~ .) +
  scale_x_continuous(breaks = seq(100, 450, 50))
```

# Bayesian modelling

## Phonation

```{r rr-1}
priors <- c(
  set_prior("normal(200, 50)", class = "Intercept"),
  set_prior("normal(0, 25)", class = "b", coef = "voicingvoiced"),
  set_prior("normal(50, 25)", class = "b", coef = "num_sylmono"),
  set_prior("normal(50, 25)", class = "b", coef = "voicingvoiced:num_sylmono"),
  set_prior("normal(-25, 10)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("lkj(2)", class = "cor"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

rr_1 <- brm(
  rel_rel ~
    voicing +
    num_syl +
    voicing:num_syl +
    speech_rate_c +
    (1 + voicing | speaker) +
    (1 | word),
  family = gaussian(),
  data = eng_durations_rr,
  prior = priors,
  cores = 4,
  seed = 1234,
  file = "./english/data/cache/rr_1"
)
```

```{r rr-1-sum}
summary(rr_1, prob = 0.95)
```

```{r rr-1-pp-check}
pp_check(rr_1, nsamples = 50)
```

```{r rr-1-int}
mcmc_intervals(as.array(rr_1), regex_pars = "^b_[^I]", prob = 0.99, prob_outer = 0.8)
```

## Vowel, place

```{r rr-2}
priors <- c(
  set_prior("normal(200, 50)", class = "Intercept"),
  set_prior("normal(0, 30)", class = "b", coef = "voweler"),
  set_prior("normal(0, 30)", class = "b", coef = "vowelee"),
  set_prior("normal(0, 30)", class = "b", coef = "placelabial"),
  set_prior("normal(-25, 10)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

rr_2 <- brm(
  rel_rel ~
    vowel +
    place +
    speech_rate_c +
    (1 | speaker) +
    (1 | word),
  family = gaussian(),
  data = eng_durations_rr,
  prior = priors,
  cores = 4,
  seed = 1234,
  file = "./english/data/cache/rr_2"
)
```

```{r rr-2-sum}
summary(rr_2, prob = 0.95)
```

# Exploratory

```{r rr-3}
priors <- c(
  set_prior("normal(200, 50)", class = "Intercept"),
  set_prior("normal(0, 25)", class = "b", coef = "voicingvoiced"),
  set_prior("normal(50, 25)", class = "b", coef = "num_sylmono"),
  set_prior("normal(50, 25)", class = "b", coef = "voicingvoiced:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "voweler"),
  set_prior("normal(0, 30)", class = "b", coef = "vowelee"),
  set_prior("normal(0, 30)", class = "b", coef = "placelabial"),
  set_prior("normal(-25, 10)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("lkj(2)", class = "cor"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

rr_3 <- brm(
  rel_rel ~
    voicing +
    num_syl +
    voicing:num_syl +
    vowel +
    place +
    speech_rate_c +
    (1 + voicing | speaker) +
    (1 | word),
  family = gaussian(),
  data = eng_durations_rr,
  prior = priors,
  cores = 4,
  seed = 1234,
  file = "./english/data/cache/rr_3"
)
```

```{r rr-3-sum}
summary(rr_3, prob = 0.95)
```

```{r rr-3-pp-check}
pp_check(rr_3, nsamples = 50)
```

```{r rr-3-int}
mcmc_intervals(as.array(rr_3), regex_pars = "^b_[^I]", prob = 0.99, prob_outer = 0.8)
```

```{r rr-3-areas}
mcmc_areas(as.array(rr_3), regex_pars = "^b_[^I]", prob = 0.5)
```

```{r rr-3-draws}
rr_3_draws <- rr_3 %>%
  gather_draws(b_voicingvoiced, b_num_sylmono, `b_voicingvoiced:num_sylmono`)

rr_3_draws_2 <- rr_3 %>%
  gather_draws(b_voweler, b_vowelee, b_placelabial)
```

```{r rr-3-draws-interval}
rr_3_draws %>%
  ungroup() %>%
  mutate(.variable = factor(.variable, levels = c("b_voicingvoiced:num_sylmono", "b_num_sylmono", "b_voicingvoiced"))) %>%
  ggplot(aes(.value, .variable)) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(position = position_nudge(y = -0.15), .width = c(0.66, 0.98)) +
  scale_x_continuous(breaks = seq(-15, 25, 5)) +
  scale_color_brewer()
```

```{r rr-3-draws-halfeye}
rr_3_draws %>%
  ungroup() %>%
  mutate(.variable = factor(.variable, levels = c("b_voicingvoiced:num_sylmono", "b_num_sylmono", "b_voicingvoiced"))) %>%
  ggplot(aes(.value, .variable)) +
  geom_vline(xintercept = 0) +
  geom_halfeyeh(fill = "#9ecae1") +
  stat_intervalh(position = position_nudge(y = -0.15)) +
  scale_x_continuous(breaks = seq(-15, 25, 5)) +
  scale_color_brewer()
```

```{r rr-3-draws-interval-2}
rr_3_draws_2 %>%
  ggplot(aes(.value, .variable)) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(position = position_nudge(y = -0.15), .width = c(0.66, 0.98)) +
  scale_x_continuous(breaks = seq(-50, 25, 5)) +
  scale_color_brewer()
```

```{r rr-3-fixed}
rr_3_fixed <- tidy(rr_3, effects = "fixed", conf.level = 0.95, fix.intercept = FALSE) %>%
  mutate(
    ci_width = abs(conf.low - conf.high),
    is_rope = ifelse(ci_width <= 20, "*", "")
  )
rr_3_fixed
```

## Plot predicted posterior distributions

```{r rr-3-post}
rr_3_post <- posterior_samples(rr_3, pars = "b_Intercept") %>%
  bind_cols(
    (c(posterior_samples(rr_3, pars = "b_Intercept")) +
    posterior_samples(rr_3, pars = "b_voicingvoiced", exact_match = TRUE))
  ) %>%
  bind_cols(
    (c(posterior_samples(rr_3, pars = "b_Intercept")) +
    posterior_samples(rr_3, pars = "b_num_sylmono", exact_match = TRUE))
  ) %>%
  bind_cols(
    (c(posterior_samples(rr_3, pars = "b_Intercept")) +
    posterior_samples(rr_3, pars = "b_voicingvoiced", exact_match = TRUE) +
    posterior_samples(rr_3, pars = "b_num_sylmono", exact_match = TRUE) +
    posterior_samples(rr_3, pars = "b_voicingvoiced:num_sylmono", exact_match = TRUE))
  ) %>%
  rename(
    di_voiceless = b_Intercept,
    di_voiced = b_voicingvoiced,
    mono_voiceless = b_num_sylmono,
    mono_voiced = b_voicingvoiced1
  ) %>%
  gather(context, rr_duration) %>%
  mutate(context = factor(context, levels = c("di_voiceless", "di_voiced", "mono_voiceless", "mono_voiced")))
```

```{r rr-post-dens}
rr_3_post %>%
  ggplot(aes(rr_duration, fill = context)) +
  geom_density(alpha = 0.5, colour = NA) +
  theme(legend.position = "top")
```

```{r rr-post-dens-2}
rr_3_post %>%
  ggplot(aes(rr_duration, fill = context)) +
  geom_density(alpha = 0.5, colour = NA, bw = 3) +
  theme(legend.position = "top")
```

```{r rr-post-box}
rr_3_post %>%
  ggplot(aes(context, rr_duration)) +
  geom_violin() +
  geom_boxplot(width = 0.2, outlier.alpha = 0.1) +
  scale_y_continuous(breaks = seq(240, 340, 10))
```

```{r rr-post-box-2}
rr_3_post %>%
  ggplot(aes(context, rr_duration)) +
  geom_violin(bw = 3) +
  geom_boxplot(width = 0.2, outlier.alpha = 0.1) +
  scale_y_continuous(breaks = seq(240, 340, 10))
```
