---
title: "English vowel duration"
author: "Stefano Coretta"
date: "18/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(brms)
library(bayesplot)
library(tidybayes)
library(broom.mixed)
library(coretta2019eng)
data("eng_durations")

scale_fill_discrete <- function(...) scale_fill_brewer(..., type = "qual")
scale_colour_discrete <- function(...) scale_fill_brewer(..., type = "qual")
```

# Plot data

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration)) +
  geom_density(fill = "blue", alpha = 0.5, colour = NA)
```

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration, fill = vowel)) +
  geom_density(alpha = 0.5, colour = NA)
```

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration, fill = place)) +
  geom_density(alpha = 0.5, colour = NA)
```

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration, fill = num_syl)) +
  geom_density(alpha = 0.5, colour = NA)
```

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration, fill = voicing)) +
  geom_density(alpha = 0.5, colour = NA)
```

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration, fill = voicing)) +
  geom_density(alpha = 0.5, colour = NA) +
  facet_grid(num_syl ~ .)
```

```{r v-dens}
eng_durations %>%
  ggplot(aes(v1_duration, fill = voicing)) +
  geom_density(alpha = 0.5, colour = NA) +
  facet_grid(num_syl ~ place)
```

```{r v-jitter}
eng_durations %>%
  ggplot(aes(voicing, v1_duration)) +
  geom_jitter(width = 0.2, alpha = 0.2) +
  scale_y_continuous(breaks = seq(0, 300, 50))
```

```{r v-box}
eng_durations %>%
  ggplot(aes(voicing, v1_duration)) +
  geom_boxplot() +
  scale_y_continuous(breaks = seq(0, 300, 50))
```

```{r v-box}
eng_durations %>%
  ggplot(aes(voicing, v1_duration)) +
  geom_boxplot() +
  facet_grid(. ~ num_syl) +
  scale_y_continuous(breaks = seq(0, 300, 50))
```

# Bayesian analysis

```{r vow-1}
priors <- c(
  set_prior("normal(145, 30)", class = "Intercept"),
  set_prior("normal(50, 20)", class = "b", coef = "voicingvoiced"),
  set_prior("normal(0, 30)", class = "b", coef = "voweler"),
  set_prior("normal(0, 30)", class = "b", coef = "vowelee"),
  set_prior("normal(50, 25)", class = "b", coef = "num_sylmono"),
  set_prior("normal(0, 20)", class = "b", coef = "voicingvoiced:voweler"),
  set_prior("normal(0, 20)", class = "b", coef = "voicingvoiced:vowelee"),
  set_prior("normal(50, 25)", class = "b", coef = "voicingvoiced:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "voweler:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "vowelee:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "voicingvoiced:voweler:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "voicingvoiced:vowelee:num_sylmono"),
  set_prior("normal(-25, 10)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("lkj(2)", class = "cor"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

vow_1 <- brm(
  v1_duration ~
    voicing +
    vowel +
    num_syl +
    voicing:vowel +
    voicing:num_syl +
    vowel:num_syl +
    voicing:vowel:num_syl +
    speech_rate_c +
    (1 + voicing | speaker) +
    (1 | word),
  family = gaussian(),
  data = eng_durations,
  prior = priors,
  file = "./english/analysis/cache/vow_1",
  cores = 4
)
```

```{r vow-1-sum}
summary(vow_1, prob = 0.95)
```

```{r vow-1-fixed}
vow_1_fixed <- tidy(vow_1, effects = "fixed", conf.level = 0.95, fix.intercept = FALSE) %>%
  mutate(
    ci_width = abs(conf.low - conf.high),
    is_rope = ifelse(ci_width <= 20, "*", "")
  )
vow_1_fixed
```

```{r vow-1-sensitivity}
vow_1_fixed %>%
  mutate(
    theta = c(145, 50, 0, 0, 50, -25, 0, 0, 50, 0, 0, 0, 0),
    sigma_prior = c(30, 20, 30, 30, 25, 10, 20, 20, 25, 30, 30, 30, 30),
    z = abs((estimate - theta) / std.error), # it's called here std.error but is the standard deviation
    s = 1 - (std.error^2 / sigma_prior^2)
  ) %>%
  ggplot(aes(s, z, label = term)) +
  geom_point(alpha = 0.2) +
  geom_text(size = 3) +
  xlim(0, 1)
```

```{r vow-1-check}
pp_check(vow_1, nsamples = 50)
```

```{r vow-1-draws}
vow_1_draws <- vow_1 %>%
  gather_draws(`b_.*`, regex = TRUE) %>%
  filter(.variable != "b_Intercept")
```

```{r vow-1-intervals}
vow_1_draws %>%
  filter(.variable %in% c("b_voicingvoiced", "b_num_sylmono", "b_voicingvoiced:num_sylmono")) %>%
  ggplot(aes(.value, .variable)) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(position = position_nudge(y = -0.15), .width = c(0.66, 0.98)) +
  scale_color_brewer()
```

## Plot predicted posterior distributions

```{r vow-1-post}
vow_1_post <- posterior_samples(vow_1, pars = "b_") %>%
  mutate(
    di_ar_voiceless = b_Intercept,
    di_ar_voiced = b_Intercept + b_voicingvoiced,
    mono_ar_voiceless = b_Intercept + b_num_sylmono,
    mono_ar_voiced = b_Intercept + b_num_sylmono + b_voicingvoiced,
    di_er_voiceless = b_Intercept + b_voweler,
    di_er_voiced = b_Intercept + b_voicingvoiced + b_voweler + `b_voicingvoiced:voweler`,
    mono_er_voiceless = b_Intercept + b_num_sylmono + b_voweler + `b_voweler:num_sylmono`,
    mono_er_voiced = b_Intercept + b_num_sylmono + b_voicingvoiced + b_voweler + `b_voicingvoiced:voweler` + `b_voweler:num_sylmono` + `b_voicingvoiced:voweler:num_sylmono`,
    di_ee_voiceless = b_Intercept + b_vowelee,
    di_ee_voiced = b_Intercept + b_voicingvoiced + b_vowelee + `b_voicingvoiced:vowelee`,
    mono_ee_voiceless = b_Intercept + b_num_sylmono + b_vowelee + `b_vowelee:num_sylmono`,
    mono_ee_voiced = b_Intercept + b_num_sylmono + b_voicingvoiced + b_vowelee + `b_voicingvoiced:vowelee` + `b_vowelee:num_sylmono` + `b_voicingvoiced:vowelee:num_sylmono`
  ) %>%
  select(di_ar_voiceless:mono_ee_voiced) %>%
  gather(context, vow_duration) %>%
  separate(context, c("num_syl", "vowel", "voicing")) %>%
  mutate(
    voicing = factor(voicing, levels = c("voiceless", "voiced")),
    vowel = factor(vowel, levels = c("ar", "er", "ee"))
  )
```

```{r vow-post-dens}
vow_1_post %>%
  ggplot(aes(vow_duration, fill = voicing)) +
  geom_density(alpha = 0.8, colour = NA, bw = 2.5) +
  theme(legend.position = "top") +
  facet_grid(vowel ~ num_syl) +
  scale_x_continuous(breaks = seq(50, 200, 25))
```

# Exploratory

```{r vow-2}
priors <- c(
  set_prior("normal(145, 30)", class = "Intercept"),
  set_prior("normal(50, 20)", class = "b", coef = "voicingvoiced"),
  set_prior("normal(0, 30)", class = "b", coef = "voweler"),
  set_prior("normal(0, 30)", class = "b", coef = "vowelee"),
  set_prior("normal(50, 25)", class = "b", coef = "num_sylmono"),
  set_prior("normal(50, 25)", class = "b", coef = "voicingvoiced:num_sylmono"),
  set_prior("normal(-25, 10)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("lkj(2)", class = "cor"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

vow_2 <- brm(
  v1_duration ~
    voicing +
    vowel +
    num_syl +
    voicing:num_syl +
    speech_rate_c +
    (1 + voicing | speaker) +
    (1 | word),
  family = gaussian(),
  data = eng_durations,
  prior = priors,
  file = "./english/analysis/cache/vow_2",
  cores = 4
)
```

```{r vow-2-sum}
summary(vow_2, prob = 0.95)
```

```{r vow-2-fixed}
vow_2_fixed <- tidy(vow_2, effects = "fixed", conf.level = 0.95, fix.intercept = FALSE) %>%
  mutate(
    ci_width = abs(conf.low - conf.high),
    is_rope = ifelse(ci_width <= 20, "*", "")
  )
vow_2_fixed
```
