---
title: "English closures"
author: "Stefano Coretta"
date: "18/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(brms)
library(bayesplot)
library(tidymv)
library(coretta2019eng)
data("eng_durations")

scale_fill_discrete <- function(...) scale_fill_brewer(..., type = "qual")
scale_colour_discrete <- function(...) scale_fill_brewer(..., type = "qual")
```

```{r remove-na}
eng_clos <- na.omit(eng_durations)
```

# Bayesian analysis

```{r clos-1}
priors <- c(
  set_prior("normal(90, 20)", class = "Intercept"),
  set_prior("normal(-20, 10)", class = "b", coef = "voicingvoiced"),
  set_prior("normal(-15, 10)", class = "b", coef = "placelabial"),
  set_prior("normal(0, 25)", class = "b", coef = "num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "voicingvoiced:placelabial"),
  set_prior("normal(0, 30)", class = "b", coef = "voicingvoiced:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "placelabial:num_sylmono"),
  set_prior("normal(0, 30)", class = "b", coef = "voicingvoiced:placelabial:num_sylmono"),
  set_prior("normal(-25, 10)", class = "b", coef = "speech_rate_c"),
  set_prior("cauchy(0, 25)", class = "sd"),
  set_prior("lkj(2)", class = "cor"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

clos_1 <- brm(
  c2_clos_duration ~
    voicing +
    place +
    num_syl +
    voicing:place +
    voicing:num_syl +
    place:num_syl +
    voicing:place:num_syl +
    speech_rate_c +
    (1 + voicing | speaker) +
    (1 | word),
  family = gaussian(),
  data = eng_clos,
  prior = priors,
  cores = 4,
  file = "./english/data/cache/clos_1"
)
```

```{r clos-1-check}
pp_check(clos_1, nsamples = 50)
```

```{r clos-1-sum}
summary(clos_1, prob = 0.95)
```

```{r clos-1-draws}
clos_1_draws <- clos_1 %>%
  gather_draws(`b_.*`, regex = TRUE) %>%
  filter(.variable != "b_Intercept")
```

```{r clos-1-intervals}
clos_1_draws %>%
  filter(.variable %in% c("b_voicingvoiced", "b_num_sylmono", "b_voicingvoiced:num_sylmono")) %>%
  ggplot(aes(.value, .variable)) +
  geom_vline(xintercept = 0) +
  stat_intervalh() +
  stat_pointintervalh(.width = c(0.66, 0.98)) +
  scale_color_brewer()
```

## Plot predicted posterior distributions

```{r clos-1-post}
clos_1_post <- posterior_samples(clos_1, pars = "b_") %>%
  mutate(
    di_velar_voiceless = b_Intercept,
    di_velar_voiced = b_Intercept + b_voicingvoiced,
    mono_velar_voiceless = b_Intercept + b_num_sylmono,
    mono_velar_voiced = b_Intercept + b_num_sylmono + b_voicingvoiced,
    di_labial_voiceless = b_Intercept + b_placelabial,
    di_labial_voiced = b_Intercept + b_voicingvoiced + b_placelabial + `b_voicingvoiced:placelabial`,
    mono_labial_voiceless = b_Intercept + b_num_sylmono + b_placelabial + `b_placelabial:num_sylmono`,
    mono_labial_voiced = b_Intercept + b_num_sylmono + b_voicingvoiced + b_placelabial + `b_voicingvoiced:placelabial` + `b_placelabial:num_sylmono` + `b_voicingvoiced:placelabial:num_sylmono`
  ) %>%
  select(di_velar_voiceless:mono_labial_voiced) %>%
  gather(context, clos_duration) %>%
  separate(context, c("num_syl", "place", "voicing")) %>%
  mutate(
    voicing = factor(voicing, levels = c("voiceless", "voiced")),
    place = factor(place, levels = c("velar", "labial"))
  )
```

```{r clos-post-dens}
clos_1_post %>%
  ggplot(aes(clos_duration, fill = voicing)) +
  geom_density(alpha = 0.8, colour = NA, bw = 2.5) +
  theme(legend.position = "top") +
  facet_grid(place ~ num_syl) +
  scale_x_continuous(breaks = seq(40, 90, 10))
```

