---
title: "Meta-analysis of the voicing effect in English"
author: "Stefano Coretta"
date: "07/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(brms)
library(bayesplot)
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r data, message=FALSE}
estimates <- read_csv("./english/data/estimates.csv") %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    voice = factor(voice, levels = c("voiceless", "voiced")),
    n_syl = factor(n_syl, levels = c("mono", "di"))
  ) %>%
  na.omit()

davis1989 <- read_csv("./english/data/davis1989.csv") %>%
  gather("voice_stat", "value", voiced_mean:voiceless_sd) %>%
  separate(voice_stat, c("voice", "stat")) %>%
  spread(stat, value) %>%
  rename(v_duration =  "mean") %>%
  mutate(
    voice = factor(voice, levels = c("voiceless", "voiced")),
    speaker = as.factor(speaker),
    place = factor(place, levels = c("labial", "alveolar", "velar"))
  )

davis1989_red <- filter(davis1989, v_context == "reduced")
davis1989_unr <- filter(davis1989, v_context == "unreduced")
```

# Estimate of the voicing effect

```{r}
estimates %>%
  ggplot(aes(v_duration)) + geom_density()
```

The duration of vowels is bimodally distributed...

```{r}
estimates %>%
  ggplot(aes(v_duration, fill = word_pos)) + geom_density(alpha = 0.5) +
  scale_fill_manual(values = cbbPalette)
```

```{r}
estimates %>%
  ggplot(aes(n_syl, v_duration, fill = voice)) +
  geom_boxplot()
```

```{r}
estimates %>%
  ggplot(aes(v_duration, fill = word_pos, linetype = n_syl)) + geom_density(alpha = 0.8) +
  facet_wrap(~study) +
  scale_fill_manual(values = cbbPalette)
```

```{r}
get_prior(v_duration ~ voice * n_syl + word_pos + (1|study), data = estimates)
```

```{r}
priors <- c(
  set_prior("normal(200, 100)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "b", coef = "n_syldi"),
  set_prior("normal(100, 50)", class = "b", coef = "voicevoiced"),
  set_prior("normal(0, 50)", class = "b", coef = "voicevoiced:n_syldi"),
  set_prior("normal(0, 100)", class = "b", coef = "word_posisolation"),
  set_prior("normal(0, 100)", class = "b", coef = "word_posmean"),
  set_prior("normal(0, 100)", class = "b", coef = "word_posmedial"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

ve_brm <- brm(
  v_duration ~
    voice *
    n_syl +
    word_pos +
    (1|study),
  data = estimates,
  prior = priors,
  cores = 2,
  seed = 8788
)
```

```{r}
summary(ve_brm)
```

```{r}
brms::pp_check(ve_brm, nsamples = 100)
```

```{r}
mcmc_trace(as.array(ve_brm), pars = "b_voicevoiced")
```

```{r}
mcmc_intervals(as.array(ve_brm), regex_pars = "b_")
```

```{r}
mcmc_areas(as.array(ve_brm), regex_pars = "b_")
```

# Estimate of voicing effect in unstressed vowels

```{r unstr-priors}
get_prior(
  v_duration | se(sd) ~ voice + place + (1| speaker),
  data = davis1989_red,
  family = gaussian()
)
```

```{r unstr-bm}
priors <- c(
  set_prior("normal(50, 25)", class = "Intercept"),
  set_prior("normal(0, 20)", class = "b", coef = "voicevoiced"),
  set_prior("normal(0, 20)", class = "b", coef = "placealveolar"),
  set_prior("normal(0, 20)", class = "b", coef = "placevelar"),
  set_prior("normal(0, 25)", class = "sd")
)

unstr_bm <- brm(
  v_duration | se(sd, sigma = TRUE) ~ voice + place + (1| speaker),
  data = davis1989_red,
  family = gaussian(),
  prior = priors,
  cores = 4,
  seed = 1989,
  control = list(adapt_delta = 0.99)
)
```

```{r unstr-bm-summary}
summary(unstr_bm, prob = 0.9)
```

```{r unstr-bm-pp}
brms::pp_check(unstr_bm, nsamples = 100)
```

```{r unstr-bm-intervals}
mcmc_intervals(as.array(unstr_bm), regex_pars = "b_")
```

```{r unstr-bm-intervals-2}
mcmc_intervals(as.array(unstr_bm), pars = c("b_voicevoiced", "b_placealveolar", "b_placevelar"))
```

```{r unstr-bm-areas}
mcmc_areas(as.array(unstr_bm), pars = c("b_voicevoiced", "b_placealveolar", "b_placevelar"))
```

```{r unred-priors}
get_prior(
  v_duration | se(sd) ~ voice + place + (1| speaker),
  data = davis1989_unr,
  family = gaussian()
)
```

```{r unred-bm}
priors_unr <- c(
  set_prior("normal(70, 25)", class = "Intercept"),
  set_prior("normal(0, 20)", class = "b", coef = "voicevoiced"),
  set_prior("normal(0, 20)", class = "b", coef = "placealveolar"),
  set_prior("normal(0, 20)", class = "b", coef = "placevelar"),
  set_prior("normal(0, 25)", class = "sd")
)

unred_bm <- brm(
  v_duration | se(sd, sigma = TRUE) ~ voice + place + (1| speaker),
  data = davis1989_unr,
  family = gaussian(),
  prior = priors_unr,
  cores = 4,
  seed = 9891,
  control = list(adapt_delta = 0.9999)
)
```

```{r unred-bm-summary}
summary(unred_bm, prob = 0.9)
```

```{r unred-bm-areas}
mcmc_areas(as.array(unred_bm), pars = c("b_voicevoiced", "b_placealveolar", "b_placevelar"))
```
