---
title: "Italian UTI"
author: "Stefano Coretta"
date: "15/06/2017"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath("../../../"))
library(tidyverse)
library(stringr)
library(cowplot)
theme_set(theme_bw())
library(rticulate)
library(gamm4)
library(itsadug)
library(tidymv)
```

# Read data

```{r}
columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
    )

languages <- read_csv("./voicing-effect/stimuli/languages.csv")
words <- read_csv("./voicing-effect/stimuli/nonce.csv")

splines.it <- list.files(
    path = "./voicing-effect/results/ultrasound",
    pattern = "*-tongue-cart.tsv",
    full.names = TRUE
    ) %>%
    read_aaa(., columns) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    filter(language == "italian") %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    droplevels()

splines.clos.it <- list.files(
    path = "./voicing-effect/results/ultrasound",
    pattern = "*-tongue-clos-cart.tsv",
    full.names = TRUE
    ) %>%
    read_aaa(., columns) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    filter(language == "italian") %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)
```

# Data exploration

## Maximum constriction

```{r point-coronal}
filter(splines.it, label == "max_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_point(alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ speaker) +
    scale_colour_discrete(name = "Phonation of C2") +
    theme(legend.position = "top")
```

```{r path-coronal}
filter(splines.it, label == "max_TT") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_path(alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ speaker) +
    xlim(-40, 40) +
    scale_colour_discrete(name = "Phonation of C2") +
    theme(legend.position = "top")
```

```{r point-velar}
filter(splines.it, label == "max_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_point(alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ speaker) +
    scale_colour_discrete(name = "Phonation of C2") +
    theme(legend.position = "top")
```

```{r path-velar}
filter(splines.it, label == "max_TD") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_path(alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ speaker) +
    xlim(-40, 40) +
    scale_colour_discrete(name = "Phonation of C2") +
    theme(legend.position = "top")
```

## Closure

```{r point-coronal-closure}
splines.clos.it %>%
    filter(c2place == "coronal") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_point(alpha = 0.1) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ speaker) +
    scale_colour_discrete(name = "Phonation of C2") +
    theme(legend.position = "top")
```

```{r point-velar-closure}
splines.clos.it %>%
    filter(c2place == "velar") %>%
    ggplot(aes(X, Y, colour = c2phonation, group = rec.date)) +
    geom_point(alpha = 0.1) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ speaker) +
    scale_colour_discrete(name = "Phonation of C2") +
    theme(legend.position = "top")
```

# Data cleaning

Given the spurious spline data after 5 on the x axis in it02, let's filter the data.

```{r filter-data}
splines.it <- splines.it %>%
    filter(X < 50)
```

For the closure data, 40 is better.

```{r filter-clos-data}
splines.clos.it <- splines.clos.it %>%
    filter(X < 40)
```

# Statistical analysis

```{r preparation}
splines.it <- splines.it %>%
    mutate(
        c2phonation.ord = as.ordered(c2phonation),
        c2place.ord = as.ordered(c2place),
        vowel.ord = as.ordered(vowel)
    )

contrasts(splines.it$c2phonation.ord) <- "contr.treatment"
contrasts(splines.it$c2place.ord) <- "contr.treatment"
contrasts(splines.it$vowel.ord) <- "contr.treatment"

max.it <- splines.it %>%
    filter(label %in% c("max_TT", "max_TD")) %>%
    na.omit() %>%
    arrange(rec.date, fan) %>%
    create_event_start(event.col = "rec.date")

splines.clos.it <- splines.clos.it %>%
    mutate(
        c2phonation.ord = as.ordered(c2phonation),
        c2place.ord = as.ordered(c2place),
        vowel.ord = as.ordered(vowel)
    )

contrasts(splines.clos.it$c2phonation.ord) <- "contr.treatment"
contrasts(splines.clos.it$c2place.ord) <- "contr.treatment"
contrasts(splines.clos.it$vowel.ord) <- "contr.treatment"

clos.it <- splines.clos.it %>%
    na.omit() %>%
    arrange(rec.date, fan) %>%
    create_event_start(event.col = "rec.date")
```

## Tongue contour at maximum displacement

```{r max-it-gamm}
max.it.gamm <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
#        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=4) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr"),
    data = max.it,
    method = "fREML"
)

summary(max.it.gamm)

max.it.gamm.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = max.it,
    method = "fREML"
)

compareML(max.it.gamm, max.it.gamm.null)
```

```{r max-it-gamm-acf}
acf_plot(resid(max.it.gamm), split_by=list(max.it$rec.date))
```

```{r max-it-gamm-ar}
r1.max.it <- start_value_rho(max.it.gamm)

max.it.gamm.ar <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
#        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr"),
    data = max.it,
    method = "ML",
    rho = r1.max.it,
    AR.start = max.it$start.event
)

summary(max.it.gamm.ar)

max.it.gamm.ar.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
#        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr"),
    data = max.it,
    method = "ML",
    rho = r1.max.it,
    AR.start = max.it$start.event
)

compareML(max.it.gamm.ar, max.it.gamm.ar.null)
```

```{r max-it-gamm-ar-acf}
acf_plot(resid(max.it.gamm.ar), split_by=list(max.it$rec.date))

acf_resid(max.it.gamm.ar, split_pred = "AR.start")
```

```{r max-it-gamm-plot}
plot_smooth(
    max.it.gamm.ar, view = "X",
    plot_all= "c2phonation.ord", 
    cond = list(
        vowel.ord = "a",
        c2place.ord = "coronal",
        speaker = "it01"
    ),
    rug = FALSE,
    rm.ranef = T
)

plot_diff(
    max.it.gamm.ar, view = "X",
    comp = list(
        c2phonation.ord = c("voiceless", "voiced")
        ),
    cond = list(
        vowel.ord = "a",
        c2place.ord = "coronal",
        speaker = "it01"
        ),
    rm.ranef = T
)
```

## Tongue contour at closure

```{r clos-it-gamm}
clos.it.gamm <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr"),
    data = clos.it,
    method = "fREML"
)

summary(clos.it.gamm)

clos.it.gamm.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord), bs = "cr",
    data = clos.it,
    method = "fREML"
)

compareML(clos.it.gamm, clos.it.gamm.null)
```

```{r clos-it-gamm-acf}
acf_plot(resid(max.it.gamm), split_by=list(max.it$rec.date))
```

```{r clos-it-gamm-ar}
r1.clos.it <- start_value_rho(clos.it.gamm)

clos.it.gamm.ar <- bam(
    Y ~
        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
        s(X, by = c2phonation.ord, bs = "cr") +
#        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr"),
    data = clos.it,
    method = "fREML",
    rho = r1.clos.it,
    AR.start = clos.it$start.event
)

summary(clos.it.gamm.ar)

clos.it.gamm.ar.null <- bam(
    Y ~
#        c2phonation.ord +
        c2place.ord +
        vowel.ord +
        s(X, bs = "cr") +
#        s(X, by = c2phonation.ord, bs = "cr") +
#        s(X, rec.date, bs="fs", xt="cr", m=1, k=5) +
        s(X, speaker, bs="fs", xt="cr", m=1, k=5) +
        s(X, by = c2place.ord, bs = "cr") +
        s(X, by = vowel.ord, bs = "cr"),
    data = clos.it,
    method = "fREML",
    rho = r1.clos.it,
    AR.start = clos.it$start.event
)

compareML(clos.it.gamm.ar, clos.it.gamm.ar.null)
```

```{r clos-it-gamm-ar-acf}
acf_plot(resid(clos.it.gamm.ar), split_by=list(clos.it$rec.date))

acf_resid(clos.it.gamm.ar, split_pred = "AR.start")
```

    ```{r clos-it-gamm-plot}
plot_smooth(
    clos.it.gamm.ar, view = "X",
    plot_all= "c2phonation.ord", 
    cond = list(
        vowel.ord = "a",
        c2place.ord = "coronal",
        speaker = "it01"
    ),
    rug = FALSE
)

plot_diff(
    clos.it.gamm.ar, view = "X",
    comp = list(
        c2phonation.ord = c("voiceless", "voiced")
        ),
    cond = list(
        vowel.ord = "a",
        c2place.ord = "coronal",
        speaker = "it01"
        )
)
```
