---
title: "Power analysis"
author: "Stefano Coretta"
date: "04/11/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lmerTest)
library(simr)
library(brms)
library(bayesplot)
```

# Simulate data

```{r sim-data}
set.seed(8788)

gons <- NULL

for (i in 1:30) {
  b_speaker <- rnorm(1, 0, 55)
  gons <- c(gons, rnorm(10, 90 + b_speaker, 70), rnorm(10, 90 + b_speaker, 70) + 5)
}

sim_data <- tibble(
  gons = gons,
  part = rep(rep(c("root", "dorsum"), each = 10), 30),
  subject = rep(1:30, each = 20)
) %>%
  mutate(
    part = factor(part),
    subject = factor(subject)
  )
```

```{r plot}
sim_data %>%
  ggplot(aes(part, gons)) +
  geom_boxplot() +
  facet_wrap(~ subject)
```

```{r gons-lm}
gons_sim_lm <- lmer(
  gons ~
    part +
    (1|subject),
  data = sim_data
)
summary(gons_sim_lm)
```

# Power analyses

```{r sim-1, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
fixef(gons_sim_lm)["partroot"] <- 5

gons_1_lm <- extend(gons_sim_lm, along = "subject", n = 40)

gons_1_sim <- powerCurve(gons_1_lm, along = "subject", seed = 8788)
```

```{r sim-1-plot}
plot(gons_1_sim)
```

```{r sim-2, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
fixef(gons_sim_lm)["partroot"] <- 10

gons_2_lm <- extend(gons_sim_lm, along = "subject", n = 40)

gons_2_sim <- powerCurve(gons_2_lm, along = "subject", seed = 8788)
```

```{r sim-2-plot}
plot(gons_2_sim)
```

```{r sim-3, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
fixef(gons_sim_lm)["partroot"] <- 15

gons_3_lm <- extend(gons_sim_lm, along = "subject", n = 40)

gons_3_sim <- powerCurve(gons_3_lm, along = "subject", seed = 8788)
```

```{r sim-3-plot}
plot(gons_3_sim)
```

```{r sim-4, message=FALSE, warning=FALSE, cache=TRUE, include=FALSE}
fixef(gons_sim_lm)["partroot"] <- 20

gons_4_lm <- extend(gons_sim_lm, along = "subject", n = 40)

gons_4_sim <- powerCurve(gons_4_lm, along = "subject", seed = 8788)
```

```{r sim-4-plot}
plot(gons_4_sim)
```

# Bayesian

```{r sim-data-2}
set.seed(8788)

gons_diff <- NULL

n_subjects <- 20
mean_diff <- 5

for (i in 1:n_subjects) {
  gons_diff <- c(gons_diff, rnorm(20, mean_diff, 70))
}

sim_data_2 <- tibble(
  gons_diff,
  subject = rep(1:n_subjects, each = 20),
  word = rep(c("cock", "cog", "cocker", "cogger"), 5 * n_subjects)
) %>%
  mutate(
    subject = factor(subject)
  )
```

```{r plot-2}
sim_data_2 %>%
  ggplot(aes(gons_diff)) +
  geom_density()
```

```{r plot-2-speakers}
sim_data_2 %>%
  ggplot(aes(gons_diff)) +
  geom_density() +
  facet_wrap(~ subject)
```

```{r diff-brm}
priors <- c(
  set_prior("normal(0, 50)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("normal(0, 50)", class = "sigma") # sigma is the standard deviation of the error term
)

diff_brm <- brm(
  gons_diff ~
    1 +
    (1|subject) +
    (1|word),
  data = sim_data_2,
  family = gaussian(),
  prior = priors,
  iter = 20000,
  chains = 4,
  control = list(adapt_delta = 0.999),
  save_all_pars = TRUE
)
```

```{r summary-brm}
summary(diff_brm)
```

```{r intercept-interval}
color_scheme_set("red")
mcmc_intervals(as.array(diff_brm), pars = c("b_Intercept"), prob_outer = 0.95) +
  theme_minimal()
```

```{r intercept-area}
mcmc_areas(as.array(diff_brm), pars = c("b_Intercept"))
```

```{r random-intervals}
mcmc_intervals(as.array(diff_brm), pars = c("sd_subject__Intercept", "sd_word__Intercept", "sigma"))
```

```{r sim-data-3}
set.seed(8788)

gons_diff <- NULL

n_subjects <- 20
mean_diff <- 0

for (i in 1:n_subjects) {
  gons_diff <- c(gons_diff, rnorm(20, mean_diff, 70))
}

sim_data_3 <- tibble(
  gons_diff,
  subject = rep(1:n_subjects, each = 20),
  word = rep(c("cock", "cog", "cocker", "cogger"), 5 * n_subjects)
) %>%
  mutate(
    subject = factor(subject)
  )
```

```{r diff-brm-3}
priors <- c(
  set_prior("normal(0, 50)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("normal(0, 50)", class = "sigma") # sigma is the standard deviation of the error term
)

diff_brm_3 <- brm(
  gons_diff ~
    1 +
    (1|subject) +
    (1|word),
  data = sim_data_3,
  family = gaussian(),
  prior = priors,
  iter = 20000,
  chains = 4,
  control = list(adapt_delta = 0.999),
  save_all_pars = TRUE
)
```

```{r summary-brm-3}
summary(diff_brm_3)
```

```{r intercept-interval-3}
color_scheme_set("red")
mcmc_intervals(as.array(diff_brm_3), pars = c("b_Intercept"), prob_outer = 0.95) +
  theme_minimal()
```

```{r sim-data-3}
set.seed(8788)

gons_diff <- NULL

n_subjects <- 10
mean_diff <- 0

for (i in 1:n_subjects) {
  gons_diff <- c(gons_diff, rnorm(20, mean_diff, 70))
}

sim_data_4 <- tibble(
  gons_diff,
  subject = rep(1:n_subjects, each = 20),
  word = rep(c("cock", "cog", "cocker", "cogger"), 5 * n_subjects)
) %>%
  mutate(
    subject = factor(subject)
  )
```

```{r diff-brm-4}
priors <- c(
  set_prior("normal(0, 50)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("normal(0, 50)", class = "sigma") # sigma is the standard deviation of the error term
)

diff_brm_4 <- brm(
  gons_diff ~
    1 +
    (1|subject) +
    (1|word),
  data = sim_data_4,
  family = gaussian(),
  prior = priors,
  iter = 20000,
  chains = 4,
  control = list(adapt_delta = 0.999),
  save_all_pars = TRUE
)
```

```{r summary-brm-4}
summary(diff_brm_4)
```

```{r intercept-interval-4}
color_scheme_set("red")
mcmc_intervals(as.array(diff_brm_4), pars = c("b_Intercept"), prob_outer = 0.95) +
  theme_minimal()
```
