---
title: "Vowel duration as a function of consonant gestural timing in Italian and Polish:
  Evidence from acoustic, ultrasound tongue imaging, and electroglottography"
author: "Stefano Coretta"
date: "05/08/2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(lmerTest)
library(effects)
library(broom)
library(broom.mixed)
library(itsadug)
library(tidymv)
data("kinematics_series", "kinematics", package = "coretta2018itapol")
kinematics_s <- kinematics_series %>%
  filter(c1_phonation == "voiceless") %>%
  mutate(
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))
  )
kine_s <- kinematics_s %>%
  filter(TR_displacement_sm > 10, proportion < 1) %>%
  group_by(speaker) %>%
  mutate(
    trp = -TR_displacement_sm + max(TR_displacement_sm),
    c2_phonation_o = ordered(c2_phonation, levels = c("voiceless", "voiced")),
    place_vow_voi_o = as.ordered(interaction(c2_place, vowel, c2_phonation)),
    language_voi_o = as.ordered(interaction(language, c2_phonation))
  ) %>%
  ungroup() %>%
  mutate_if(is.character, as.factor)
contrasts(kine_s$c2_phonation_o) <-  "contr.treatment"
contrasts(kine_s$place_vow_voi_o) <-  "contr.treatment"
contrasts(kine_s$language_voi_o) <-  "contr.treatment"
```

```{r read-data, message=FALSE}
speakers <- read_csv("./datasets/speakers.csv")
stimuli <- read_csv("./datasets/stimuli.csv")

durations <- list.files(
  path = "./datasets",
  pattern = "*-durations.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--")) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced")),
    language = recode(language, italian = "Italian", polish = "Polish"),
    syl_rate = ifelse(
      language == "Italian",
      8 / sentence_duration,
      6 / sentence_duration
    )
  ) %>%
  filter(c1_phonation == "voiceless")

durations_filtered <- durations %>%
  group_by(speaker) %>%
  mutate(
    vowel_duration_z = scale(vowel_duration),
    closure_duration_z = scale(closure_duration)
  ) %>%
  filter(
    vowel_duration_z < 3, vowel_duration_z > -3,
    closure_duration_z < 3, closure_duration_z > -3
  )

word_filtered <- durations %>%
    group_by(speaker) %>%
  mutate(
    word_duration_z = scale(word_duration)
  ) %>%
  filter(
    word_duration_z < 3, word_duration_z > -3
  )

rel_filtered <- durations %>%
    group_by(speaker) %>%
  mutate(
    rel_rel_z = scale(rel_rel)
  ) %>%
  filter(
    rel_rel_z < 3, rel_rel_z > -3
  )

kine_clos <- kinematics  %>%
  filter(
    c1_phonation == "voiceless",
    label == "closure_"
    ) %>%
  group_by(speaker) %>%
  mutate(
    trp = -TR_displacement_sm + max(TR_displacement_sm),
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))
  ) %>%
  ungroup() %>%
  mutate_if(is.character, as.factor)

# filtered kinematics
kine_clos_f <- kine_clos %>%
  filter(
    TR_displacement_sm > 10
  )
```

```{r vow-lm}
vow_lm <- lmer(
  vowel_duration ~
    c2_phonation *
    vowel *
    language +
    c2_place +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)
```

```{r vowels-plot}
durations_filtered %>%
  ggplot(aes(vowel, vowel_duration, fill = c2_phonation)) +
  geom_boxplot(alpha = 0.5) +
  geom_point(position = position_jitterdodge(), alpha = 0.1) +
  facet_grid(~ language) +
  labs(x = "Vowel", y = "Vowel duration (ms)") +
  scale_fill_brewer(name = "C2 voicing", type = "qual", palette = "Dark2")

ggsave("./fig/vowel-plot.pdf", width = 7, height = 5)
```

```{r clo-lm}
clo_lm <- lmer(
  closure_duration ~
    c2_phonation *
    vowel *
    language +
    c2_place +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered
)
```

```{r closure-plot}
durations_filtered %>%
  ggplot(aes(vowel, closure_duration, fill = c2_phonation)) +
  geom_boxplot(alpha = 0.5) +
  geom_point(position = position_jitterdodge(), alpha = 0.1) +
  facet_grid(~ language) +
  labs(x = "Vowel", y = "Closure duration (ms)") +
  scale_fill_brewer(name = "C2 voicing", type = "qual", palette = "Dark2")

ggsave("./fig/closure-plot.pdf", width = 7, height = 5)
```

```{r vow-clo-lm}
vow_clo_lm <- lmer(
  vowel_duration ~
    closure_duration *
    vowel +
    syl_rate +
    (1+closure_duration|speaker) +
    (1|item),
  data = durations_filtered
)
summary(vow_clo_lm)
```

```{r vow-clo-plot}
as_tibble(effect("closure_duration:vowel", vow_clo_lm)) %>%
  ggplot(aes(closure_duration, fit)) +
  geom_point(data = durations_filtered, aes(y = vowel_duration), alpha = 0.1) +
  geom_line(aes(colour = vowel)) +
  geom_ribbon(aes(ymax = upper, ymin = lower, fill = vowel), alpha = 0.2) +
  geom_rug(data = durations_filtered, aes(y = vowel_duration), alpha = 0.1) +
  facet_grid(~ vowel) +
  labs(x = "Closure duration (ms)", y = "Vowel duration (ms)") +
  theme(legend.position = "none") +
  scale_fill_brewer(type = "qual", palette = "Dark2") +
  scale_colour_brewer(type = "qual", palette = "Dark2")

ggsave("./fig/vow-clo-plot.pdf", width = 7, height = 5)
```

```{r rr-plot-1}
ggplot(rel_filtered) +
  geom_density(aes(rel_rel, fill = c2_phonation), colour = NA, alpha = 0.5) +
  geom_rug(aes(rel_rel)) +
  facet_grid(~ language) +
  scale_fill_brewer(name = "C2 voicing", type = "qual", palette = "Dark2") +
  labs(
    x = "Release to Release duration (ms)"
  )

ggsave("./fig/rr-plot-1.pdf", width = 7, height = 5)
```

```{r rr-plot-2}
rel_filtered %>%
  ggplot(aes(c2_phonation, rel_rel)) +
  geom_boxplot(aes(fill = c2_phonation), alpha = 0.5) +
  geom_jitter(alpha = 0.1, width = 0.3) +
  facet_grid(~ language) +
  labs(x = "C2 voicing", y = "Release to Release duration (ms)") +
  scale_fill_brewer(name = "C2 voicing", type = "qual", palette = "Dark2")

ggsave("./fig/rr-plot-2.pdf", width = 7, height = 5)
```

```{r rr-bf}
rr_lm <- lme4::lmer(
  rel_rel ~
    c2_phonation +
    vowel +
    c2_place +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

rr_lm_null <- lme4::lmer(
  rel_rel ~
    # c2_phonation +
    vowel +
    c2_place +
    language +
    syl_rate +
    (1+c2_phonation|speaker) +
    (1|item),
  data = durations_filtered,
  REML = FALSE
)

rr_bf <- round(exp((BIC(rr_lm) - BIC(rr_lm_null)) / 2))
```

```{r trp-gam-3}
trp_gam_3  <- bam(
  trp ~
    c2_phonation_o +
    s(proportion) +
    s(proportion, by = c2_phonation_o) +
    s(vowel_duration) +
    ti(proportion, vowel_duration) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = kine_s
)
```

```{r trp-gam-3-plot}
plot_smooths(trp_gam_3, proportion, c2_phonation_o) + scale_y_continuous(breaks = seq(1, 30, 1)) + scale_color_brewer(type = "qual", palette = "Dark2") + scale_fill_brewer(type = "qual", palette = "Dark2")

ggsave("./fig/trp-gam-3.pdf", width = 7, height = 5)
```

```{r trp-gam}
trp_gam  <- bam(
  trp ~
    place_vow_voi_o +
    s(proportion) +
    s(proportion, by = place_vow_voi_o) +
    # s(vowel_duration) +
    # ti(proportion, vowel_duration) +
    s(proportion, speaker, bs = "fs", m = 1),
  data = kine_s
)
```

```{r trp-gam-plot}
plot_smooths(trp_gam, proportion, voicing, facet_terms = place + vowel, split = list(place_vow_voi_o = c("place", "vowel", "voicing"))) +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  scale_fill_brewer(type = "qual", palette = "Dark2") +
  labs(
    x = "Vowel proportion",
    y = "Tongue root position (mm)"
  )

ggsave("./fig/trp-gam.pdf", width = 7, height = 5)
```

```{r trp-vow-lm}
trp_vow_lm <- lmer(
  trp ~
    vowel_duration *
    vowel *
    c2_phonation +
    syl_rate +
    (1+vowel_duration|speaker) +
    (1|item),
  data = kine_clos_f
)
```

```{r trp-vow-plot}
as_tibble(effect("vowel_duration:vowel:c2_phonation", trp_vow_lm)) %>%
  mutate(c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))) %>%
  ggplot(aes(vowel_duration, fit)) +
  geom_point(data = kine_clos_f, aes(y = trp), alpha = 0.1) +
  geom_line(aes(colour = c2_phonation)) +
  geom_ribbon(aes(ymax = upper, ymin = lower, fill = c2_phonation), alpha = 0.2) +
  geom_rug(data = kine_clos_f, aes(y = trp), alpha = 0.1) +
  facet_grid(~ vowel) +
  labs(x = "Vowel duration (ms)", y = "Tongue root position (mm)") +
  scale_fill_brewer(name = "C2 voicing", type = "qual", palette = "Dark2") +
  scale_colour_brewer(name = "C2 voicing", type = "qual", palette = "Dark2") +
  theme(legend.position = "top")

ggsave("./fig/trp-vow-plot.pdf", width = 7, height = 3)
```
