---
title: "Bayesian modelling of vowel duration"
author: "Stefano Coretta"
date: "15/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
library(brms)
library(bayesplot)
library(coretta2018itapol)
data("token_measures")
seed <- 9375

token_measures <- token_measures %>%
  filter(c1_phonation == "voiceless", file != "it07-048") %>%
  mutate(
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))
  ) %>%
  mutate_if(is.character, as.factor)
```

# Vowel duration

```{r vdur_bm}
priors <- c(
  set_prior("normal(150, 50)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 25)", class = "b", coef = "languagePolish"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_placevelar"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced:languagePolish"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced:vowelo"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced:vowelu"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced:vowelo:languagePolish"),
  set_prior("normal(0, 25)", class = "b", coef = "c2_phonationvoiced:vowelu:languagePolish"),
  set_prior("normal(0, 100)", class = "b", coef = "speech_rate_c"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma"),
  set_prior("lkj(2)", class = "cor")
)

vdur_bm <- brm(
  v1_duration ~
    c2_phonation +
    vowel +
    language +
    c2_place +
    c2_phonation:vowel +
    c2_phonation:language +
    c2_phonation:vowel:language +
    speech_rate_c +
    (1 + c2_phonation|speaker) +
    (1|item),
  data = token_measures,
  prior = priors,
  cores = 4,
  file = "./italian-polish/analysis/cache/vdur_bm"
)
```

```{r vdur-bm-summary}
summary(vdur_bm)
```

```{r vdur-bm-interval-intercept}
mcmc_intervals(as.array(vdur_bm), pars = c("b_Intercept"))
```

```{r vdur-bm-intervals}
mcmc_intervals(as.array(vdur_bm), pars = c("b_c2_phonationvoiced", "b_c2_phonationvoiced:languagePolish", "b_languagePolish", "b_vowelo", "b_vowelu", "b_c2_phonationvoiced:vowelo", "b_c2_phonationvoiced:vowelu", "b_c2_phonationvoiced:vowelo:languagePolish", "b_c2_phonationvoiced:vowelu:languagePolish", "b_c2_placevelar"))
```

```{r vdur-bm-areas}
mcmc_areas(as.array(vdur_bm), pars = c("b_c2_phonationvoiced", "b_c2_phonationvoiced:languagePolish", "b_languagePolish", "b_vowelo", "b_vowelu", "b_c2_phonationvoiced:vowelo", "b_c2_phonationvoiced:vowelu", "b_c2_phonationvoiced:vowelo:languagePolish", "b_c2_phonationvoiced:vowelu:languagePolish", "b_c2_placevelar"))
```

# Vowel and closure durations

```{r}
priors <- c(
  set_prior("normal(150, 50)", class = "Intercept"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration"),
  set_prior("normal(0, 20)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 5)", class = "b", coef = "closure_duration:c2_phonationvoiced"),
  set_prior("normal(0, 5)", class = "b", coef = "closure_duration:vowelo"),
  set_prior("normal(0, 5)", class = "b", coef = "closure_duration:vowelu"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 100)", class = "b", coef = "syl_rate_c"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

vclos_bm <- brm(
  vowel_duration ~
    closure_duration *
    c2_phonation +
    vowel +
    closure_duration:vowel +
    syl_rate_c +
    (1|speaker) +
    (1|item),
  data = token_measures,
  prior = priors,
  cores = 2,
  seed = seed
)
```

```{r}
summary(vclos_bm)
```

```{r}
mcmc_intervals(as.array(vclos_bm), pars = c("b_closure_duration", "b_closure_duration:c2_phonationvoiced", "b_closure_duration:vowelo", "b_closure_duration:vowelu"), prob_outer = 0.89) + theme_minimal() + geom_vline(aes(xintercept = 0))
```

```{r}
priors <- c(
  set_prior("normal(150, 50)", class = "Intercept"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:syl_rate_c"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:vowelo"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:vowelu"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 100)", class = "b", coef = "syl_rate_c"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

vclos_bm_2 <- brm(
  vowel_duration ~
    closure_duration +
    vowel +
    closure_duration:vowel +
    closure_duration:syl_rate_c +
    syl_rate_c +
    (1|speaker) +
    (1|item),
  data = token_measures,
  prior = priors,
  cores = 2
)
```

```{r}
summary(vclos_bm_2)
```

```{r}
priors_3 <- c(
  set_prior("normal(150, 50)", class = "Intercept"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:syl_rate_c"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:vowelo"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:vowelu"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 25)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 25)", class = "b", coef = "languagePolish"),
  set_prior("normal(0, 100)", class = "b", coef = "syl_rate_c"),
  set_prior("normal(0, 2)", class = "b", coef = "closure_duration:languagePolish"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

vclos_bm_3 <- brm(
  vowel_duration ~
    closure_duration +
    vowel +
    closure_duration:vowel +
    closure_duration:syl_rate_c +
    syl_rate_c +
    language +
    closure_duration:language +
    (1|speaker) +
    (1|item),
  data = token_measures,
  prior = priors,
  cores = 2
)
```

```{r}
summary(vclos_bm_3)
```

