---
title: "Vowel formants and fundamental frequency"
author: "Stefano Coretta"
date: "12/02/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(effects)
library(sjPlot)
```

# Data import

```{r}
speakers <- read_csv("./italian-polish/data/datasets/speakers.csv")
stimuli <- read_csv("./italian-polish/data/datasets/stimuli.csv")

durations <- list.files(
  path = "italian-polish/data/datasets/acoustics",
  pattern = "*-durations.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--"))

vowels <- list.files(
  path = "italian-polish/data/datasets/acoustics",
  pattern = "*-formants.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--")) %>%
  left_join(y = durations, by = c("speaker", "file", "word")) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  mutate(
    v1_duration = (c2_ons - v1_ons) * 1000,
    sentence_duration = sentence_off - sentence_ons,
    speech_rate = ifelse(
      language == "Italian",
      8 / sentence_duration,
      6 / sentence_duration
    ),
    speech_rate_c = speech_rate - mean(speech_rate, na.rm = TRUE)
  ) %>%
  mutate_if(is.character, as.factor)

f1_dur <- vowels %>%
  filter(time.x == 5)
```

# Exploration

```{r}
vowels %>%
  filter(language == "italian") %>%
  ggplot(aes(time.x, f1, colour = c2_phonation)) +
  geom_smooth(method = "loess") +
  facet_grid(c2_place ~ vowel)
```

```{r}
vowels %>%
  filter(language == "italian") %>%
  ggplot(aes(time.x, f2, colour = c2_phonation)) +
  geom_smooth(method = "loess") +
  facet_grid(c2_place ~ vowel)
```

```{r}
formants %>%
  filter(language == "italian") %>%
  ggplot(aes(time, f3, colour = c2_phonation)) +
  geom_smooth() +
  facet_grid(c2_place ~ vowel)
```

```{r}
formants %>%
  filter(language == "italian") %>%
  ggplot(aes(x = time, colour = c2_phonation)) +
  geom_smooth(aes(y = f1)) +
  geom_smooth(aes(y = f2)) +
  facet_grid(c2_place ~ vowel)
```

```{r}
vowels %>%
  filter(language == "polish") %>%
  ggplot(aes(x = time.x, colour = c2_phonation)) +
  geom_smooth(aes(y = f1)) +
  geom_smooth(aes(y = f2)) +
  facet_grid(. ~ vowel)
```

```{r}
for (i in 1:9) {
  print(vowels %>%
  filter(time.x == i, language == "italian", vowel != "u") %>%
  ggplot(aes(f2, f1, colour = c2_phonation)) +
  geom_point() +
  facet_grid(c2_place ~ vowel) +
  scale_x_reverse(lim = c(max(vowels$f2), min(vowels$f2))) +
  scale_y_reverse(lim = c(max(vowels$f1), min(vowels$f1)))
  )
}
```

```{r}
for (i in 1:9) {
  print(formants %>%
  filter(time == i, language == "polish", vowel != "u") %>%
  ggplot(aes(f2, f1, colour = c2_phonation)) +
  geom_point() +
  facet_grid(c2_place ~ vowel) +
  scale_x_reverse(lim = c(max(formants$f2), min(formants$f2))) +
  scale_y_reverse(lim = c(max(formants$f1), min(formants$f1)))
  )
}
```

```{r height-duration}
vowels %>%
  group_by(file, item) %>%
  summarise(
    f1 = mean(f1),
    vowel_duration = mean(vowel_duration)
  ) %>%
  ggplot(aes(f1, vowel_duration)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm")
```

```{r}
f1_dur_lm <- lmer(
  v1_duration ~
    f1 *
    vowel +
    speech_rate_c +
    (1|speaker) +
    (1|item),
  data = f1_dur
)
summary(f1_dur_lm)
```

```{r}
plot(allEffects(f1_dur_lm))
```

```{r}
plot_model(f1_dur_lm, order.terms = 1:6)
```

```{r}
plot_model(f1_dur_lm, type = "pred", terms = c("f1", "vowel"))
```

