---
title: "3D tongue"
author: "Stefano Coretta"
date: "12/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(mgcv)
library(itsadug)
library(tidymv)
library(akima)
library(TTR)
library(plotly)
```

# Read data

```{r data, message=FALSE}
read_tongue <- function(file) {
  tibble <- read_csv(file, col_names = c("X", "Y", "Z")) %>%
    mutate(file = substr(file, 26, 42))
  
  tibble <- mutate(tibble, index = seq(1, nrow(tibble)))
  
  return(tibble)
}

stimuli <- read_csv("italian-sz/data/stimuli.csv")

tongue <- list.files(
  path = "italian-sz/data/datasets",
  pattern = "*.csv",
  full.names = TRUE
) %>%
  map_df(~read_tongue(.)) %>%
  left_join(y = stimuli) %>%
  mutate(phone = ordered(phone, levels = c("s", "z"))) %>%
  mutate_if(is.character, as.factor) %>%
  create_event_start("file")

contrasts(tongue$phone) <- "contr.treatment"
```

# 3D tongue modelling with GAMs

## Tongue GAM

```{r tongue-gam, eval=FALSE}
tongue_gam <- bam(
  Z ~
    s(X, Y),
  data = tongue
)
```

```{r tongue-gam-plot, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam, theta = -35, phi = 40, scale = FALSE, xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), color = "terrain")
```

## Tongue GAM 2

```{r tongue-gam_2, eval=FALSE}
tongue_gam_2 <- bam(
  Z ~
    s(X, Y, by = phone),
  data = tongue
)
```

```{r tongue-gam-2-plot, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam_2, theta = -35, phi = 40, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain")
vis.gam(tongue_gam_2, theta = -35, phi = 40, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain")
```

```{r tongue-gam-2-plot-2, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam_2, theta = -35, phi = 40, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", se = 1.96)
vis.gam(tongue_gam_2, theta = -35, phi = 40, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", se = 1.96)
```

## Tongue GAM 3

```{r tongue-gam-3, cache=TRUE}
tongue_gam_3 <- bam(
  Z ~
    phone +
    s(X, Y) +
    s(X, Y, by = phone),
  data = tongue
)
```

```{r tongue-gam-3-plot, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = -35, phi = 50, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", too.far = .01)
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = -35, phi = 50, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", too.far = .01)
```

```{r tongue-gam-3-plot-2, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = -35, phi = 50, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", se = 1.96, too.far = .01)
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = -35, phi = 50, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", se = 1.96, too.far = .01)
```

```{r tongue-gam-3-plot-3, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = -90, phi = 0, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", too.far = .01)
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = -90, phi = 0, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", too.far = .01)
```

```{r tongue-gam-3-plot-4, warning=FALSE, eval=FALSE}
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = 90, phi = 0, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", too.far = .01)
vis.gam(tongue_gam_3, view = c("X", "Y"), theta = 90, phi = 0, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", too.far = .01)
```

## Tongue GAM with AR1

```{r gam-ar, cache=TRUE, dependson="tongue-gam-3"}
rho <- start_value_rho(tongue_gam_3)

gam_ar <- bam(
  Z ~
    phone +
    s(X, Y) +
    s(X, Y, by = phone),
  data = tongue,
  AR.start = tongue$start.event,
  rho = rho
)
```

```{r gam-ar-acf-plot}
acf_resid(gam_ar, split_pred = "AR.start")
```

```{r gam-ar-plot, warning=FALSE}
vis.gam(gam_ar, view = c("X", "Y"), theta = -35, phi = 50, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", too.far = .05)
vis.gam(gam_ar, view = c("X", "Y"), theta = -35, phi = 50, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", too.far = .05)
```

```{r gam-ar-plot-2, warning=FALSE}
vis.gam(gam_ar, view = c("X", "Y"), theta = 0, phi = 50, scale = FALSE, cond = list(phone = "s"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[s]", color = "terrain", too.far = .05)
vis.gam(gam_ar, view = c("X", "Y"), theta = 0, phi = 50, scale = FALSE, cond = list(phone = "z"), ticktype = "detailed", xlim = c(1, 13), ylim = c(3, 10), zlim = c(3, 8), main = "[z]", color = "terrain", too.far = .05)
```

# Volume increase

```{r volume-increase}
x_min <- 1.8
x_max <- 11.8
y_min <- 3.6
y_max <- 9.9

# File is needed in the grid for midsagittal data (it groups by file)
grid <- expand.grid(X = seq(x_min, x_max, length = 100), Y = seq(y_min, y_max, length = 100), file = levels(tongue$file))
grid <- cbind(grid, phone = rep(rep(c("s", "z"), each = 10000), 5))

predicted <- predict(gam_ar, newdata = grid)
predicted_df <- cbind(grid, predicted) %>%
  dplyr::select(-file) %>%
  unique() %>%
  spread(phone, predicted) %>%
  mutate(
    difference = s - z
  )

sum_diff <- sum(predicted_df$difference)
volume_diff <- sum_diff * (x_max - x_min)/100 * (y_max - y_min)/100
cat("The volume increase for [z] over [s] is", round(volume_diff, 2), "cm^3 (= ml)")
```

```{r masked-volume-increase}
interp_data <- interp(tongue$X, tongue$Y, tongue$Z, xo = seq(x_min, x_max, length = 100), yo = seq(y_min, y_max, length = 100), duplicate = "mean")

interp_m <- interp_data$z
interp_m <- ifelse(!is.na(interp_m), 1, 0)

predicted_df_2 <- predicted_df
predicted_df_2$mask <- as.vector(t(interp_m))

predicted_df_2 <- predicted_df_2 %>%
  mutate(diff_2 = difference * mask)

sum_diff_2 <- sum(predicted_df_2$diff_2)
volume_diff_2 <- sum_diff_2 * (x_max - x_min)/100 * (y_max - y_min)/100
cat("The volume increase for [z] over [s] is", round(volume_diff_2, 2), "cm^3 (= ml)")
```

```{r}
predicted_se <- as_tibble(predict(gam_ar, newdata = grid, se = TRUE))

predicted_df_se <- cbind(grid, predicted_se) %>%
  dplyr::select(-file) %>%
  unique() %>%
  mutate(
    CI_up = fit + se.fit * 1.96,
    CI_lo = fit - se.fit * 1.96
  )
  
predicted_ci_up <- dplyr::select(predicted_df_se, X, Y, CI_up, phone) %>%
  spread(phone, CI_up) %>%
  mutate(
    CI_up_diff = s - z
  ) %>%
  dplyr::select(-s , -z)

predicted_ci_lo <- dplyr::select(predicted_df_se, X, Y, CI_lo, phone) %>%
  spread(phone, CI_lo) %>%
  mutate(
    CI_lo_diff = s - z
  ) %>%
  dplyr::select(-s , -z)

predicted_ci <- full_join(predicted_ci_up, predicted_ci_lo)

predicted_ci$mask <- as.vector(t(interp_m))

predicted_ci_2 <- predicted_ci %>%
  mutate(
    CI_up_diff_2 = CI_up_diff * mask,
    CI_lo_diff_2 = CI_lo_diff * mask
    )

sum_ci_up_diff_2 <- sum(predicted_ci_2$CI_up_diff_2)
sum_ci_lo_diff_2 <- sum(predicted_ci_2$CI_lo_diff_2)
volume_up_diff_2 <- sum_ci_up_diff_2 * (x_max - x_min)/100 * (y_max - y_min)/100
volume_lo_diff_2 <- sum_ci_lo_diff_2 * (x_max - x_min)/100 * (y_max - y_min)/100
cat("The volume increase for [z] over [s] is", round(volume_up_diff_2, 2), "cm^3 (= ml)\n")
cat("The volume increase for [z] over [s] is", round(volume_lo_diff_2, 2), "cm^3 (= ml)")
```


# Token variation

```{r prep-token-variation}
files_interp <- NULL

for (file in 1:length(levels(tongue$file))) {
  file_data <- tongue[tongue$file == levels(tongue$file)[file],]
  
  file_interp_data <- interp(file_data$X, file_data$Y, file_data$Z, xo = seq(x_min, x_max, length = 100), yo = seq(y_min, y_max, length = 100))
  
  files_interp <- c(files_interp, as.vector(t(file_interp_data$z)))
}

tongue_interp <- cbind(grid, interp = files_interp) %>%
  group_by(phone, X, Y) %>%
  summarise(min = min(interp, na.rm = TRUE), max = max(interp, na.rm = TRUE)) %>%
  mutate(
    min = ifelse(min == Inf, NA, min),
    max = ifelse(max == -Inf, NA, max)
  )

s_interp <- filter(tongue_interp, phone == "s")
s_min_m <- matrix(s_interp$min, 100, 100)

z_interp <- filter(tongue_interp, phone == "z")
z_max_m <- matrix(z_interp$max, 100, 100)

color <- rep(0, length(s_min_m))
dim(color) <- dim(s_min_m)

color2 <- rep(1, length(z_max_m))
dim(color2) <- dim(z_max_m)
```

```{r plot-min-max}
plot_ly(colors = c("black", "orange")) %>%
  add_surface(
    z = ~s_min_m,
    surfacecolor = color,
    cauto = F,
    cmax = 1,
    cmin = 0,
    opacity = 0.8
  ) %>%
  add_surface(
    z = ~z_max_m,
    surfacecolor = color2,
    cauto = F,
    cmax = 1,
    cmin = 0,
    opacity = 0.8
  ) %>%
  layout(scene = list(aspectmode = "manual", aspectratio = list(x = 0.6, y = 1, z = 0.5)))
```

```{r frankestein-volume}
f_sum_diff <- sum(s_interp$min - z_interp$max, na.rm = TRUE)
f_volume_diff <- f_sum_diff * (x_max - x_min)/100 * (y_max - y_min)/100
cat("The volume increase for [z] over [s] is", round(f_volume_diff, 2), "cm^3 (= ml)")
```

```{r frankestein-volume-no-outlier}
tongue_2 <- filter(tongue, file != "20181011121440_10") %>%
  droplevels()

files_interp_2 <- NULL

for (file in 1:length(levels(tongue_2$file))) {
  file_data_2 <- tongue[tongue$file == levels(tongue$file)[file],]
  
  file_interp_data_2 <- interp(file_data_2$X, file_data_2$Y, file_data_2$Z, xo = seq(x_min, x_max, length = 100), yo = seq(y_min, y_max, length = 100))
  
  files_interp_2 <- c(files_interp_2, as.vector(t(file_interp_data_2$z)))
}

grid_2 <- filter(grid, file != "20181011121440_10")

tongue_interp_2 <- cbind(grid_2, interp = files_interp_2) %>%
  group_by(phone, X, Y) %>%
  summarise(min = min(interp, na.rm = TRUE), max = max(interp, na.rm = TRUE)) %>%
  mutate(
    min = ifelse(min == Inf, NA, min),
    max = ifelse(max == -Inf, NA, max)
  )

s_interp_2 <- filter(tongue_interp_2, phone == "s")
s_min_m_2 <- matrix(s_interp_2$min, 100, 100)

z_interp_2 <- filter(tongue_interp_2, phone == "z")
z_max_m_2 <- matrix(z_interp_2$max, 100, 100)

f_sum_diff_2 <- sum(s_interp_2$min - z_interp_2$max, na.rm = TRUE)
f_volume_diff_2 <- f_sum_diff_2 * (x_max - x_min)/100 * (y_max - y_min)/100
cat("The volume increase for [z] over [s] is", round(f_volume_diff_2, 2), "cm^3 (= ml)")
```

```{r plot-min-max}
plot_ly(colors = c("black", "orange")) %>%
  add_surface(
    z = ~s_min_m_2,
    surfacecolor = color,
    cauto = F,
    cmax = 1,
    cmin = 0,
    opacity = 1
  ) %>%
  add_surface(
    z = ~z_max_m_2,
    surfacecolor = color2,
    cauto = F,
    cmax = 1,
    cmin = 0,
    opacity = 1
  ) %>%
  layout(scene = list(aspectmode = "manual", aspectratio = list(x = 0.6, y = 1, z = 0.5)))
```

# Midsagittal

```{r prep-saggital}
midsagittal <- cbind(grid, interp = files_interp) %>%
  filter(X > 6.8 & X < 6.9) %>%
  na.omit() %>%
  group_by(file) %>%
  mutate(smoothed = WMA(interp)) # smoothed with a weighted moving

parasaggital_l <- cbind(grid, interp = files_interp) %>%
  filter(X > 3 & X < 3.1) %>%
  na.omit() %>%
  group_by(file) %>%
  mutate(smoothed = WMA(interp)) # smoothed with a weighted moving

parasaggital_r <- cbind(grid, interp = files_interp) %>%
  filter(X > 10.2 & X < 10.3) %>%
  na.omit() %>%
  group_by(file) %>%
  mutate(smoothed = WMA(interp)) # smoothed with a weighted moving
```

```{r contours, warning=FALSE}
ggplot(midsagittal, aes(Y, interp, colour = phone, group = file)) +
  geom_path()
```

```{r smoothed-contours, warning=FALSE}
ggplot(midsagittal, aes(Y, smoothed, colour = phone, group = file)) +
  geom_path()
```

```{r contour-smooths, warning=FALSE}
ggplot(midsagittal, aes(Y, interp, colour = phone, linetype = phone)) +
  geom_smooth(method = "loess")
```


```{r parasaggital-l-contours, warning=FALSE}
ggplot(parasaggital_l, aes(Y, interp, colour = phone, group = file)) +
  geom_path()
```

```{r parasaggital-l-smooth, warning=FALSE}
ggplot(parasaggital_l, aes(Y, interp, colour = phone)) +
  geom_smooth()
```

```{r parasaggital-r-contours, warning=FALSE}
ggplot(parasaggital_r, aes(Y, interp, colour = phone, group = file)) +
  geom_path()
```
