---
title: "Durations"
author: "Stefano Coretta"
date: "09/03/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(lme4)
library(effects)
```

# Data import

```{r}
speakers <- read_csv("./voicing-effect/data/datasets/speakers.csv")
stimuli <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

duration <- list.files(
  path = "voicing-effect/data/datasets/acoustics/",
  pattern = "*-durations.csv",
  full.names = TRUE
) %>%
  map_df(~read_csv(., na = "--undefined--")) %>%
  left_join(y = speakers) %>%
  left_join(y = stimuli) %>%
  filter(c1_phonation == "voiceless") %>%
  mutate(c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced"))) %>%
  mutate_if(is.character, as.factor)
```

# Plotting data

```{r}
duration %>%
  group_by(speaker) %>%
  mutate(vowel_duration = scale(vowel_duration)) %>%
  ggplot(aes(vowel, vowel_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

```{r}
duration %>%
  ggplot(aes(vowel, vowel_duration, fill = c2_phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
duration %>%
  filter(vowel == "a") %>%
  ggplot(aes(speaker, vowel_duration, fill = c2_phonation)) +
  geom_boxplot()
```

```{r}
duration %>%
  filter(speaker == "pl05") %>%
  ggplot(aes(vowel, vowel_duration, fill = c2_phonation)) +
  geom_boxplot() +
  facet_grid(~ c2_place)
```

```{r}
duration %>%
  filter(speaker == "pl05") %>%
  ggplot(aes(vowel_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5, linetype = 0) +
  facet_grid(~ c2_place)
```

```{r}
duration %>%
  ggplot(aes(vowel_duration, colour = c2_phonation, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(vowel ~ c2_place)
```

```{r}
duration %>%
  ggplot(aes(vowel, c1_rvot, fill = c2_phonation)) +
  geom_boxplot()
```

```{r}
duration %>%
  ggplot(aes(vowel, c1_closure, fill = c2_phonation)) +
  geom_boxplot()
```

## Closure duration

```{r}
duration %>%
  group_by(speaker) %>%
  mutate(closure_duration = scale(closure_duration)) %>%
  ggplot(aes(vowel, closure_duration)) +
  geom_boxplot()
```

```{r}
duration %>%
  ggplot(aes(c2_phonation, closure_duration)) +
  geom_boxplot() +
  facet_grid(~ language)
```

## Release to release

```{r rr-density}
duration %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(rel_rel, fill = c2_phonation, colour = c2_phonation)) +
  geom_density(alpha = 0.5)
```

```{r rr-density-lang}
duration %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(rel_rel, fill = c2_phonation, colour = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(~ language)
```

```{r rr-density-vow-c2_place}
duration %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(rel_rel, fill = c2_phonation, colour = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(c2_place ~ vowel)
```

```{r rr-box}
duration %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(vowel, rel_rel, fill = c2_phonation)) +
  geom_boxplot()
```

```{r rr-box-lang}
duration %>%
  group_by(speaker) %>%
  mutate(rel_rel = scale(rel_rel)) %>%
  ggplot(aes(vowel, rel_rel, fill = c2_phonation)) +
  geom_boxplot() +
  facet_grid(~ language)
```

The Release-Release interval duration does not seem to be affected by the voicing of C2.

## Vowel duration ~ Closure

```{r}
vow_clos_lm <- lmer(
  vowel_duration ~
    closure_duration +
    sentence_duration +
    vowel +
    c2_place +
    (1|speaker) +
    (1|item),
  data = duration,
  REML = FALSE
)
summary(vow_clos_lm)
```

```{r}
plot(allEffects(vow_clos_lm))
```


## Word durations

```{r word-dur-density}
duration %>%
  ggplot(aes(word_duration, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(~ language)
```

```{r word-dur-density}
duration %>%
  group_by(speaker) %>%
  mutate(word_duration_z = scale(word_duration)) %>%
  ggplot(aes(word_duration_z, fill = c2_phonation)) +
  geom_density(alpha = 0.5) +
  facet_grid(~ language)
```

```{r}
duration %>%
  group_by(speaker) %>%
  mutate(word_duration_z = scale(word_duration)) %>%
  ggplot(aes(c2_phonation, word_duration_z, fill = c2_phonation)) +
  geom_boxplot() +
  facet_wrap(~ speaker)
```

```{r}
duration %>%
  group_by(speaker) %>%
  mutate(word_duration_z = scale(word_duration)) %>%
  ggplot(aes(c2_phonation, word_duration_z, fill = c2_phonation)) +
  geom_boxplot() +
  facet_wrap(~ language)
```

# Analysis

```{r vowdur-lm}
vowdur_lm <- lmer(
  vowel_duration ~
    c2_phonation +
#    language +
    c2_place +
    vowel +
    c2_phonation:vowel +
#    language:vowel +
    sentence_duration +
    (1+c2_phonation|speaker) +
    (1|item),
  REML = FALSE,
  data = duration
)
summary(vowdur_lm)
```

```{r vowdur-lm-plot}
plot(allEffects(vowdur_lm))
```

```{r vowdur-ranef}
round(ranef(vowdur_lm)$speaker)
```

```{r vowdur-lm-ranef-condmodes}
as_tibble(ranef(vowdur_lm)$speaker[2], rownames = "speaker") %>%
  mutate(language = c(rep("Italian", 11), rep("Polish", 6))) %>%
  ggplot(aes(speaker, c2_phonationvoiced, fill = language)) +
  geom_bar(stat = "identity") +
  labs(title = "By-speaker conditional means for phonation", y = "Vowel duration (msec)")
```

```{r vowdur-lm-ranef-intercept}
as_tibble(ranef(vowdur_lm)$speaker[1], rownames = "speaker") %>%
  mutate(language = c(rep("Italian", 11), rep("Polish", 6))) %>%
  ggplot(aes(speaker, `(Intercept)`, fill = language)) +
  geom_bar(stat = "identity") +
  labs(title = "By-speaker conditional means for vowel duration (intercept)", y = "Vowel duration (msec)")
```

```{r corr-ranef}
as_tibble(ranef(vowdur_lm)$speaker, rownames = "speaker") %>%
  filter(c2_phonationvoiced < 10) %>%
  ggplot(aes(`(Intercept)`, c2_phonationvoiced)) +
  geom_point() +
  geom_smooth(method = "lm")
```

No correlation between vowel duration and phonation conditional means.

```{r vowdur-lm-coeff-phonation}
as_tibble(coef(vowdur_lm)$speaker[2], rownames = "speaker") %>%
  mutate(language = c(rep("Italian", 11), rep("Polish", 6))) %>%
  ggplot(aes(speaker, c2_phonationvoiced, fill = language)) +
  geom_bar(stat = "identity") +
  labs(title = "By-speaker coefficients for phonation", y = "msec")
```

```{r vowdur-lm-coeff-intercept}
as_tibble(coef(vowdur_lm)$speaker[1], rownames = "speaker") %>%
  mutate(language = c(rep("Italian", 11), rep("Polish", 6))) %>%
  ggplot(aes(speaker, `(Intercept)`, fill = language)) +
  geom_bar(stat = "identity") +
  labs(title = "By-speaker coefficients for vowel duration", y = "Vowel duration (msec)")
```

