---
title: "Release to release"
author: "Stefano Coretta"
date: "15/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
library(brms)
library(bayesplot)
library(lmerTest)
library(coretta2018itapol)
data("token_measures")

token_measures <- token_measures %>%
  filter(c1_phonation == "voiceless") %>%
  mutate(
    rel_rel = (c2_rel - c1_rel) * 1000,
    c2_phonation = factor(c2_phonation, levels = c("voiceless", "voiced")),
    vor = (c2_rel - v1_ons) * 1000
  ) %>%
  filter(!is.na(rel_rel))
```

```{r rr-bm}
priors <- c(
  set_prior("normal(200, 5)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 50)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 50)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_placevelar"),
  set_prior("normal(0, 100)", class = "b", coef = "speech_rate_c"),
  set_prior("normal(0, 100)", class = "sd"),
  set_prior("lkj(2)", class = "cor"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

rr_mb <- brm(
  rel_rel ~
    c2_phonation +
    vowel +
    c2_place +
    speech_rate_c +
    (c2_phonation|speaker) +
    (1|item),
  data = token_measures,
  prior = priors,
  cores = 4,
  seed = 8788
)
```

```{r rr-bm-summary}
summary(rr_mb)
```

```{r rr-bm-intervals}
mcmc_intervals(as.array(rr_mb), pars = c("b_c2_phonationvoiced", "b_vowelo", "b_vowelu", "b_c2_placevelar", "b_speech_rate_c"))
```

```{r rr-bm-areas}
mcmc_areas(as.array(rr_mb), pars = c("b_c2_phonationvoiced", "b_vowelo", "b_vowelu", "b_c2_placevelar", "b_speech_rate_c"))
```

```{r}
mcmc_areas(as.array(rr_mb), pars = c("sd_speaker__c2_phonationvoiced"))
```

```{r rr-bm-2}
priors_2 <- c(
  set_prior("normal(200, 50)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 50)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 50)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_placevelar"),
  set_prior("normal(0, 20)", class = "b", coef = "c2_phonationvoiced:vowelo"),
  set_prior("normal(0, 20)", class = "b", coef = "c2_phonationvoiced:vowelu"),
  set_prior("normal(0, 20)", class = "b", coef = "c2_phonationvoiced:c2_placevelar"),
  set_prior("normal(0, 20)", class = "b", coef = "c2_phonationvoiced:vowelo:c2_placevelar"),
  set_prior("normal(0, 20)", class = "b", coef = "c2_phonationvoiced:vowelu:c2_placevelar"),
  set_prior("normal(0, 100)", class = "b", coef = "speech_rate_c"),
  set_prior("normal(0, 100)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

rr_bm_2 <- brm(
  rel_rel ~
    c2_phonation *
    vowel *
    c2_place +
    speech_rate_c +
    (1|speaker) +
    (1|item),
  data = token_measures,
  prior = priors_2,
  cores = 4,
  seed = 8788,
  control = list(adapt_delta = 0.99),
  file = "./italian-polish/data/cache/rr_bm_2"
)
```

```{r rr-bm-2-summary}
summary(rr_bm_2)
```

```{r rr-bm-2-intervals}
mcmc_intervals(as.array(rr_bm_2), pars = c("b_c2_phonationvoiced", "b_vowelo", "b_vowelu", "b_c2_placevelar", "b_speech_rate_c"))
```

```{r rr-bm-2-intervals-1}
mcmc_intervals(as.array(rr_bm_2), pars = c("b_c2_phonationvoiced"), prob = 0.6)
```

```{r rr-bm-2-intervals-2}
mcmc_intervals(as.array(rr_bm_2), pars = c("b_c2_phonationvoiced:vowelo", "b_c2_phonationvoiced:vowelu", "b_c2_phonationvoiced:c2_placevelar", "b_c2_phonationvoiced:vowelo:c2_placevelar", "b_c2_phonationvoiced:vowelu:c2_placevelar"))
```

```{r rr-bm-2-pp-check}
pp_check(rr_bm_2, nsamples = 100)
```

```{r rr-bm-2a}
priors_2a <- c(
  set_prior("normal(200, 50)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "b", coef = "vowelo"),
  set_prior("normal(0, 50)", class = "b", coef = "vowelu"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_placevelar"),
  set_prior("normal(0, 100)", class = "b", coef = "speech_rate_c"),
  set_prior("normal(0, 100)", class = "sd"),
  set_prior("cauchy(0, 50)", class = "sigma")
)

rr_bm_2a <- brm(
  rel_rel ~
    vowel +
    c2_place +
    speech_rate_c +
    (1|speaker) +
    (1|item),
  data = token_measures,
  prior = priors_2a,
  cores = 4,
  seed = 8788,
  control = list(adapt_delta = 0.99),
  file = "./italian-polish/data/cache/rr_bm_2a"
)
```

```{r rr-bm-2a}
summary(rr_bm_2a)
```

```{r rr-bm-3}
priors_3 <- c(
  set_prior("normal(200, 25)", class = "Intercept"),
  set_prior("normal(0, 50)", class = "b", coef = "c2_phonationvoiced"),
  set_prior("normal(0, 50)", class = "b", coef = "speech_rate_c"),
  set_prior("normal(0, 50)", class = "b", coef = "languagePolish"),
  set_prior("normal(0, 50)", class = "sd"),
  set_prior("cauchy(0, 25)", class = "sigma")
)

rr_bm_3 <- brm(
  rel_rel ~
    c2_phonation +
    speech_rate_c +
    language +
    (1|speaker) +
    (1|item),
  data = token_measures,
  prior = priors_3,
  cores = 4,
  chains = 4,
  iter = 4000,
  warmup = 1000,
  seed = 8788,
  control = list(adapt_delta = 0.99),
  file = "./italian-polish/data/cache/rr_bm_3"
)
```

```{r}
summary(rr_bm_3)
```

## VOR

```{r}
vor_lm <- lmer(
  vor ~
    c2_phonation +
    vowel +
    c2_place +
    language +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  REML = FALSE,
  data = token_measures
)

summary(vor_lm)

vor_lm_null <- lmer(
  vor ~
    # c2_phonation +
    vowel +
    c2_place +
    language +
    speech_rate_c +
    (1+c2_phonation|speaker) +
    (1|item),
  REML = FALSE,
  data = token_measures
)

exp((BIC(vor_lm) - BIC(vor_lm_null)) / 2)
```

