---
title: "Comparison of cartesian and polar coordinates"
author: "Stefano Coretta"
date: "19/06/2017"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
library(cowplot)
theme_set(theme_minimal())
library(rticulate)
library(mgcv)
library(itsadug)
library(tidymv)
library(plotrix)
```

# Read data

```{r}
columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs"
    )

languages <- read_csv("./voicing-effect/stimuli/languages.csv")
words <- read_csv("./voicing-effect/stimuli/nonce.csv")

splines.it <- list.files(
    path = "./voicing-effect/results/ultrasound",
    pattern = "*-tongue-cart.tsv",
    full.names = TRUE
    ) %>%
    map_df(~read_aaa(., columns)) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    filter(language == "italian") %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor)

splines.pol.it <- list.files(
    path = "./voicing-effect/results/ultrasound",
    pattern = "*-tongue-pol.tsv",
    full.names = TRUE
    ) %>%
    map_df(~read_aaa(., columns, coordinates = "polar")) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    filter(language == "italian") %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(X = radius * sin(theta), Y = radius * cos(theta))
```

## Comparison

```{r group-coronal-it}
filter(splines.pol.it, label == "max_TT") %>%
    ggplot(aes(theta, radius, colour = c2phonation)) +
    # geom_line(stat = "smooth", method = "loess") +
    geom_point(alpha = 0.5) +
    facet_grid(. ~ vowel) +
    scale_colour_discrete(name = "Phonation of C2") + coord_polar(start = 1) + xlim(0, 4) + ylim(0, 60)
```

```{r group-coronal-it}
filter(splines.pol.it, label == "max_TT", vowel == "u") %>%
    ggplot(aes(Y, X, colour = c2phonation)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    geom_point(alpha = 0.1) +
    scale_colour_discrete(name = "Phonation of C2") + coord_polar(start = pi) + xlim(-pi, pi) + ylim(0, 60)
```

```{r group-coronal-it, eval = FALSE}
filter(splines.pol.it, label == "max_TT") %>%
    ggplot(aes(Y.car, X.car, colour = c2phonation, group = rec.date)) +
#    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    geom_point(alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(vowel ~ .) +
    scale_colour_discrete(name = "Phonation of C2")
```

```{r}
filter(splines.it, label == "max_TT", speaker == "it01", vowel == "a") %>%
        ggplot(aes(X, Y, group = rec.date)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    geom_point(alpha = 0.1, aes(group = rec.date)) +
    coord_fixed(ratio = 1) +
    facet_grid(. ~ c2phonation) +
    geom_path(aes(group = rec.date), alpha = 0.1) +
    scale_colour_discrete(name = "Phonation of C2")
```

```{r eval = FALSE}
filter(splines.pol.it, label == "max_TT", speaker == "it01", vowel == "u") %>%
        ggplot(aes(Y.car, X.car)) +
    geom_line(stat = "smooth", method = "loess", alpha = 0.5) +
    geom_point(alpha = 0.1, aes(group = rec.date)) +
    coord_fixed(ratio = 1) +
    facet_grid(. ~ c2phonation) +
    geom_path(aes(group = rec.date), alpha = 0.1) +
    scale_colour_discrete(name = "Phonation of C2")
```

```{r eval = FALSE}
filter(splines.pol.it, label == "max_TT", speaker == "it01", vowel == "u") %>%
        ggplot(aes(Y.car, X.car)) +
    geom_line(stat = "smooth", method = "gam", formula = y ~ s(x, k = 3), alpha = 0.5) +
    coord_fixed(ratio = 1) +
    facet_grid(. ~ c2phonation) +
    scale_colour_discrete(name = "Phonation of C2")
```

```{r}
splines.pol.it.u <- splines.pol.it %>%
    filter(label == "max_TT", speaker == "it01", vowel == "a") 

radial.plot(na.omit(splines.pol.it.u$X), na.omit(splines.pol.it.u$Y), rp.type="s", labels = "", clockwise = T, start = pi/2, radial.labels = "", xlim = c(-pi, pi))
```


```{r}
filter(splines.pol.it, label == "max_TT") %>%
    ggplot(aes(theta, radius, colour = c2phonation)) +
    geom_point(alpha = 0.5) +
    facet_grid(. ~ vowel)
```

```{r}
filter(splines.pol.it, label == "max_TT") %>%
    ggplot(aes(theta, radius, colour = c2phonation)) +
    geom_smooth(method = "loess") +
    facet_grid(. ~ vowel)
```

```{r}
splines.pol.it %>%
    filter(label == "max_TT", speaker == "it01", vowel == "a") %>%
    ggplot(aes(-X, -Y, colour = c2phonation)) +
    geom_point()
```

```{r}
splines.it %>%
    filter(label == "max_TT", speaker == "it01", vowel == "a") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_point()
```

```{r}
coord <- splines.it %>%
    filter(rec.date %in% c("29/11/2016 15:10:47", "29/11/2016 15:10:57"))

x_1 <- c(coord$X[coord$fan_line == 20][1], coord$X[coord$fan_line == 20][2])
y_1 <- c(coord$Y[coord$fan_line == 20][1], coord$Y[coord$fan_line == 20][2])

x_2 <- c(coord$X[coord$fan_line == 21][1], coord$X[coord$fan_line == 21][2])
y_2 <- c(coord$Y[coord$fan_line == 21][1], coord$Y[coord$fan_line == 21][2])

x <- ((x_1[1]*y_1[2] - y_1[1]*x_1[2]) * (x_2[1] - x_2[2]) - (x_1[1] - x_1[2]) * (x_2[1] * y_2[2] - y_2[1] * x_2[2])) / ((x_1[1] - x_1[2]) * (y_2[1] - y_2[2]) - (y_1[1] - y_1[2]) * (x_2[1] - x_2[2]))

y <- ((x_1[1]*y_1[2] - y_1[1]*x_1[2]) * (y_2[1] - y_2[2]) - (y_1[1] - y_1[2]) * (x_2[1] * y_2[2] - y_2[1] * x_2[2])) / ((x_1[1] - x_1[2]) * (y_2[1] - y_2[2]) - (y_1[1] - y_1[2]) * (x_2[1] - x_2[2]))
```

Using equations leads to more consistent results.

```{r get-origin-eq}
for (i in 1:10) {
    m1 <- lm(Y ~ X, data = filter(coord, fan_line == i))
    m2 <- lm(Y ~ X, data = filter(coord, fan_line == i + 20))

    cm <- rbind(coef(m1),coef(m2)) # Coefficient matrix
    print(c(-solve(cbind(cm[,2],-1)) %*% cm[,1]))
}

x <- c(-solve(cbind(cm[,2],-1)) %*% cm[,1])[1]
y <- c(-solve(cbind(cm[,2],-1)) %*% cm[,1])[2]
```


```{r}
splines.it %>%
    filter(label == "max_TT", speaker == "it01", vowel == "a") %>%
    ggplot(aes(X, Y)) +
    geom_point(aes(colour = c2phonation)) +
    geom_point(data = tibble(X = x, Y = y), colour = "blue", size = 2, shape = 4)
```

```{r}
splines.it %>%
    filter(label == "max_TT", speaker == "it01", vowel == "a") %>%
    ggplot(aes(fan_line, Y)) +
    geom_point(aes(colour = c2phonation)) +
    geom_smooth(aes(colour = c2phonation))
```

```{r}
polar_data <- splines.it %>%
    filter(speaker == "it01") %>%
    mutate(
        radius = sqrt((X - x) ^ 2 + (Y - y) ^ 2),
        theta = pi + atan2(Y - y, X - x)
    )
```

```{r}
polar_data %>%
    filter(label == "max_TT", vowel == "a") %>%
    ggplot(aes(theta, radius, colour = c2phonation)) +
    geom_point() +
    geom_smooth(method = "loess")
```

```{r}
polar_data %>%
    mutate(
        X = x - radius * cos(theta),
        Y = -radius * sin(theta) - y
    ) %>%
    filter(label == "max_TT", vowel == "a") %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_point()
```

# Convert to polar and back

```{r}
polar <- splines.it %>%
    filter(speaker == "it01") %>%
    transform_coord()
```

```{r}
polar %>%
    filter(label %in% c("max_TT", "max_TD")) %>%
    ggplot(aes(theta, radius, colour = c2phonation)) +
    geom_point() +
    facet_wrap(~ c2place + vowel)
```

```{r}
polar %>%
    filter(label %in% c("max_TT", "max_TD")) %>%
    ggplot(aes(theta, radius, colour = c2phonation)) +
    geom_smooth() +
    facet_wrap(~ c2place + vowel)
```

```{r}
cartesian <- polar %>%
    filter(speaker == "it01") %>%
    transform_coord(to = "cartesian", origin = c(14.3900792705248, -65.231492830589))
```

```{r}
cartesian %>%
    filter(label %in% c("max_TT", "max_TD")) %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_point() +
    facet_wrap(~ c2place + vowel)
```

Compare the above with the one below.

```{r}
splines.it %>%
    filter(speaker == "it01", label %in% c("max_TT", "max_TD")) %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_point() +
    facet_wrap(~ c2place + vowel)
```

# Polar GAM

```{r}
it01 <- polar %>%
    mutate(
        vowel = ordered(vowel, levels = c("a", "o", "u")),
        c2place = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation = ordered(c2phonation, levels = c("voiceless", "voiced")),
        vow_phon = ordered(interaction(vowel, c2phonation), levels = c("a.voiceless", "a.voiced", "o.voiceless", "o.voiced", "u.voiceless", "u.voiced")),
        place_phon = ordered(interaction(c2place, c2phonation), levels = c("coronal.voiceless", "coronal.voiced", "velar.voiceless", "velar.voiced"))
    ) %>%
    arrange(rec.date, fan_line) %>%
    create_event_start("rec.date") %>%
    droplevels() %>%
    filter(theta > 3.7, theta < 5.8)
```

```{r}
it01_gam <- bam(
    radius ~
        c2phonation +
        c2place +
        vowel +
        s(theta, bs = "cr") +
        s(theta, by = c2phonation,  bs = "cr") +
        s(theta, by = c2place,  bs = "cr") +
        s(theta, by = vowel,  bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = filter(it01, vowel != "u")
)

summary(it01_gam)
```

```{r}
plot_smooths(
    it01_gam,
    theta,
    c2phonation,
    c2place + vowel
)
```

```{r}
it01_gam_null <- bam(
    radius ~
#        c2phonation +
        c2place +
        vowel +
        s(theta) +
#        s(theta, by = c2phonation) +
        s(theta, by = c2place) +
        s(theta, by = vowel) +
        s(theta, rec.date, bs = "fs", k = 5),
    data = filter(it01, vowel != "u")
)

compareML(it01_gam_null, it01_gam)
```

```{r}
it01_gam_2 <- bam(
    radius ~
        c2phonation +
        c2place +
        vowel +
        s(theta, bs = "cr") +
        s(theta, by = c2phonation, bs = "cr") +
        s(theta, by = c2place, bs = "cr") +
        s(theta, by = vowel, bs = "cr") +
        s(theta, by = vow_phon, bs = "cr") +
        s(theta, by = place_phon, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = filter(it01, vowel != "u")
)

summary(it01_gam_2)

it01_gam_2_null <- bam(
    radius ~
#        c2phonation +
        c2place +
        vowel +
        s(theta, bs = "cr") +
#        s(theta, by = c2phonation, bs = "cr") +
        s(theta, by = c2place, bs = "cr") +
        s(theta, by = vowel, bs = "cr") +
        s(theta, by = vow_phon, bs = "cr") +
        s(theta, by = place_phon, bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = filter(it01, vowel != "u")
)

compareML(it01_gam_2_null, it01_gam_2)
```

```{r}
plot_smooths(
    it01_gam_2,
    theta,
    c2phonation,
    c2place + vowel
)
```

```{r}
polar_pred <- get_gam_predictions(it01_gam_2, theta)
```

```{r}
polar_pred <- transform_coord(polar_pred, to = "cartesian", origin = c(14.3900792705248, -65.231492830589))

ggplot(polar_pred, aes(X, Y, colour = c2phonation)) +
    geom_path() +
    facet_wrap(~ c2place + vowel)
```


```{r}
it01_cart <- splines.it %>%
    filter(speaker == "it01") %>%
    mutate(
        vowel = ordered(vowel, levels = c("a", "o", "u")),
        c2place = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation = ordered(c2phonation, levels = c("voiceless", "voiced")),
        vow_phon = ordered(interaction(vowel, c2phonation)),
        place_phon = ordered(interaction(c2place, c2phonation))
    ) %>%
    arrange(rec.date, fan_line) %>%
    create_event_start("rec.date") %>%
    droplevels()
```

```{r}
it01_gam_cart <- bam(
    Y ~
        c2phonation +
        c2place +
        vowel +
        s(X, bs = "cr") +
        s(X, by = c2phonation,  bs = "cr") +
        s(X, by = c2place,  bs = "cr") +
        s(X, by = vowel,  bs = "cr") +
        s(X, rec.date, bs = "fs", xt = "cr", k = 5),
    data = filter(it01_cart, vowel != "u")
)

summary(it01_gam_cart)
```

```{r}
plot_smooths(
    it01_gam_cart,
    X,
    c2phonation,
    c2place + vowel
)
```

# Polar GAM of a coronal using Mielke's origing

Mielke's origin is: -1.11658857142857, -43.447776

```{r it01-polar-mielke}
polar_m <- splines.it %>%
    filter(
        speaker == "it01",
        label == "max_TT",
        vowel == "a"
    ) %>%
    transform_coord(origin = c(-0.800933928571429, -43.434646))
```

```{r plot-it01-polar-mielke}
ggplot(polar_m, aes(theta, radius, colour = c2phonation)) +
    geom_point(alpha = 0.5)
```


```{r prepare-gam-data-mielke}
it01_m <- polar_m %>%
    mutate(
        vowel = ordered(vowel, levels = c("a", "o", "u")),
        c2place = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation = ordered(c2phonation, levels = c("voiceless", "voiced")),
        vow_phon = ordered(interaction(vowel, c2phonation), levels = c("a.voiceless", "a.voiced", "o.voiceless", "o.voiced", "u.voiceless", "u.voiced")),
        place_phon = ordered(interaction(c2place, c2phonation), levels = c("coronal.voiceless", "coronal.voiced", "velar.voiceless", "velar.voiced"))
    ) %>%
    arrange(rec.date, fan_line) %>%
    create_event_start("rec.date") %>%
    droplevels()
```

```{r it01-gam-mielke}
it01_gam_m <- bam(
    radius ~
        c2phonation +
#        c2place +
#        vowel +
        s(theta, bs = "cr") +
        s(theta, by = c2phonation,  bs = "cr") +
#        s(theta, by = c2place,  bs = "cr") +
#        s(theta, by = vowel,  bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = it01_m,
    method = "ML"
)

summary(it01_gam_m)
```

```{r}
plot_smooths(
    it01_gam_m,
    theta,
    c2phonation
)
```

# Polar GAM of a coronal using real origin

```{r it01-polar-real}
polar_r <- splines.it %>%
    filter(
        speaker == "it01",
        label == "max_TT",
        vowel == "a"
    ) %>%
    transform_coord()
```

```{r plot-it01-polar-real}
ggplot(polar_r, aes(theta, radius, colour = c2phonation)) +
    geom_point(alpha = 0.5)
```

```{r prepare-gam-data-real}
it01_r <- polar_r %>%
    mutate(
        vowel = ordered(vowel, levels = c("a", "o", "u")),
        c2place = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation = ordered(c2phonation, levels = c("voiceless", "voiced")),
        vow_phon = ordered(interaction(vowel, c2phonation), levels = c("a.voiceless", "a.voiced", "o.voiceless", "o.voiced", "u.voiceless", "u.voiced")),
        place_phon = ordered(interaction(c2place, c2phonation), levels = c("coronal.voiceless", "coronal.voiced", "velar.voiceless", "velar.voiced"))
    ) %>%
    arrange(rec.date, fan_line) %>%
    create_event_start("rec.date") %>%
    droplevels()
```

```{r it01-gam-real}
it01_gam_r <- bam(
    radius ~
        c2phonation +
#        c2place +
#        vowel +
        s(theta, bs = "cr") +
        s(theta, by = c2phonation,  bs = "cr") +
#        s(theta, by = c2place,  bs = "cr") +
#        s(theta, by = vowel,  bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = it01_r,
    method = "ML"
)

summary(it01_gam_r)
```

```{r plot-it01-gam-real}
plot_smooths(
    it01_gam_r,
    theta,
    c2phonation
)
```

# Polar GAM of all with real origin

```{r it01-polar-all-real}
polar_all_r <- splines.it %>%
    filter(
        speaker == "it01",
        label %in% c("max_TT", "max_TD")
    ) %>%
    transform_coord()
```

```{r plot-it01-polar-all-real}
ggplot(polar_all_r, aes(theta, radius, colour = c2phonation)) +
    geom_point(alpha = 0.5) +
    geom_smooth() +
    facet_grid(vowel ~ c2place)
```

```{r prepare-gam-data-real}
it01_all_r <- polar_all_r %>%
    mutate(
        vowel = ordered(vowel, levels = c("a", "o", "u")),
        c2place = ordered(c2place, levels = c("coronal", "velar")),
        c2phonation = ordered(c2phonation, levels = c("voiceless", "voiced")),
        vow_phon = ordered(interaction(vowel, c2phonation), levels = c("a.voiceless", "a.voiced", "o.voiceless", "o.voiced", "u.voiceless", "u.voiced")),
        place_phon = ordered(interaction(c2place, c2phonation), levels = c("coronal.voiceless", "coronal.voiced", "velar.voiceless", "velar.voiced"))
    ) %>%
    arrange(rec.date, fan_line) %>%
    create_event_start("rec.date") %>%
    droplevels()
```

```{r it01-gam-real}
it01_gam_all_r <- bam(
    radius ~
        c2phonation +
        c2place +
        vowel +
        s(theta, bs = "cr") +
        s(theta, by = c2phonation,  bs = "cr") +
        s(theta, by = c2place,  bs = "cr") +
        s(theta, by = vowel,  bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = it01_all_r,
    method = "ML"
)

summary(it01_gam_all_r)
```

```{r plot-it01-gam-real}
plot_smooths(
    it01_gam_all_r,
    theta,
    c2phonation,
    vowel + c2place
)
```

```{r}
it01_gam_all_r_null <- bam(
    radius ~
#        c2phonation +
        c2place +
        vowel +
        s(theta, bs = "cr") +
#        s(theta, by = c2phonation,  bs = "cr") +
        s(theta, by = c2place,  bs = "cr") +
        s(theta, by = vowel,  bs = "cr") +
        s(theta, rec.date, bs = "fs", xt = "cr", k = 5),
    data = it01_all_r,
    method = "ML"
)

compareML(it01_gam_all_r_null, it01_gam_all_r)
```


```{r}
it01_gam_all_r_pred <- get_gam_predictions(
    it01_gam_all_r,
    theta,
    series_length = 100
) %>%
    transform_coord(
        to = "cartesian",
        origin = c(14.3901026453293, -65.2314764646618)
    )
```

```{r}
it01_gam_all_r_pred %>%
    ggplot(aes(X, Y, colour = c2phonation)) +
    geom_path() +
    facet_grid(c2place ~ vowel) +
    coord_fixed(ratio = 1)
```

