---
title: "TRA and vowel duration"
author: "Stefano Coretta"
date: "20/12/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = normalizePath("../../../"))
library(tidyverse)
theme_set(theme_minimal())
library(lmerTest)
library(effects)
```

```{r read-data}
columns <- c(
    "speaker",
    "seconds",
    "rec.date",
    "prompt",
    "label",
    "TT.displacement.sm",
    "TT.velocity",
    "TT.velocity.abs",
    "TD.displacement.sm",
    "TD.velocity",
    "TD.velocity.abs",
    "TR.displacement.sm",
    "TR.velocity",
    "TR.velocity.abs"
)

languages <- read_csv("./voicing-effect/data/datasets/languages.csv")
words <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

vowels <- list.files(path = "./voicing-effect/data/datasets/acoustics",
                   pattern = "*-durations.csv",
                   full.names = TRUE) %>%
    map_df(~read_csv(., na = "--undefined--"))

tongue_root <- list.files(path = "./voicing-effect/data/datasets/ultrasound/",
                   pattern = "*-tra-cart.tsv",
                   full.names = TRUE) %>%
    map_df(~read_tsv(., col_names = columns)) %>%
    mutate(word = word(prompt, 2)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    left_join(y = vowels) %>%
    mutate_if(is.character, as.factor) %>%
    # filter clear outlier
    filter(TR.displacement.sm > 40) %>%
    group_by(speaker) %>%
    mutate(
        vowel_duration_z = scale(vowel.duration),
        TR_displacement_z = scale(TR.displacement.sm)
    )
```

Vowel duration and tongue root displacement are normalised within each speaker using z-scores.

```{r tr-density}
tongue_root %>%
    ggplot(aes(TR_displacement_z, colour = c2phonation)) +
    geom_density() +
    facet_grid(. ~ language)
```

```{r tr-vowel-duration}
tongue_root %>%
    ggplot(aes(TR_displacement_z, vowel_duration_z, colour = c2phonation)) +
    geom_point() +
    geom_smooth(method = "lm")
```

```{r tr-vowel-duration-vowel}
tongue_root %>%
    ggplot(aes(TR_displacement_z, vowel_duration_z, colour = c2phonation)) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid(. ~ vowel)
```

```{r tr-vowel-duration-place}
tongue_root %>%
    ggplot(aes(TR_displacement_z, vowel_duration_z, colour = c2phonation)) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid( ~ c2place)
```

```{r tr-vowel-duration-vowel-place}
tongue_root %>%
    ggplot(aes(TR_displacement_z, vowel_duration_z, colour = c2phonation)) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid(c2place ~ vowel)
```

It does not seem to be a correlation. Maybe I should check TRA not at maximum TT/TD displacement?

```{r tr-phonation}
tongue_root %>%
    ggplot(aes(c2phonation, TR_displacement_z)) +
    geom_boxplot() +
    facet_grid(language ~ vowel)
```

/a/ and /o/ show more advancement in the voiced condition (lower TR_displacement).

```{r tra-lm-it}
tra_lm_it <- lmer(
    vowel_duration_z ~
        TR_displacement_z +
        c2place +
        vowel *
        c2phonation +
        (1+TR_displacement_z|speaker) +
        (1|word),
    data = filter(tongue_root, language == "italian")
)

summary(tra_lm_it)
```

```{r}
plot(allEffects(tra_lm_it))
```

```{r}
coef(tra_lm_it)$speaker
```

The lmer detects a correlation, but I need to be cautious.

```{r}
mean_tra_lm <- lmer(
    TR_displacement_z ~
        c2phonation +
        vowel +
        c2place +
        (1|speaker) +
        (1|word),
    data = tongue_root
)
summary(mean_tra_lm)
```

```{r}
plot(allEffects(mean_tra_lm))
```

```{r tra-lm}
tra_lm <- lmer(
    vowel_duration_z ~
        TR_displacement_z *
        c2phonation *
        language *
        c2place *
        vowel +
        (1+TR_displacement_z|speaker) +
        (1|word),
    data = tongue_root
)

summary(tra_lm)
```

```{r tra-lm-effects}
plot(allEffects(tra_lm))
```

```{r tra-lm-pl}
tra_lm_pl <- lmer(
    vowel_duration_z ~
        TR_displacement_z +
        c2place +
        vowel *
        c2phonation +
        (1|speaker) +
        (1|word),
    data = filter(tongue_root, language == "polish")
)

summary(tra_lm_pl)

tra_lm_pl_null <- lmer(
    vowel_duration_z ~
#        TR_displacement_z *
        c2phonation +
        vowel +
        c2place +
        (1|speaker) +
        (1|word),
    data = filter(tongue_root, language == "polish")
)

anova(tra_lm_pl_null, tra_lm_pl)
```

```{r}
plot(allEffects(tra_lm_pl))
```

