---
title: "Vowel duration"
author: "Stefano Coretta"
date: \today
output: 
  pdf_document: 
    fig_caption: yes
    latex_engine: xelatex
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir=normalizePath("../../"))
library(readr)
library(dplyr)
library(tidyr)
library(purrr)
library(lme4)
library(afex)
library(effects)
library(ggplot2)
theme_set(theme_bw())
```

# Import data

Let's read the files.

```{r read-files}
vowels <- list.files(path = "pilot/results",
                   pattern = "*-vowel-durations.csv",
                   full.names = TRUE) %>%
    map_df(~read_csv(., na = "--undefined--"))

languages <- read_csv("./pilot/stimuli/languages.csv")
words <- read_csv("./pilot/stimuli/nonce.csv")


vowels <- left_join(vowels, languages) %>%
    left_join(y = words) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(duration.norm = (vowel.duration - mean(vowel.duration)) /
               sd(vowel.duration),
           consonant.duration = closure.duration + vot
           )
```

# Italian

Fit a mixed effect linear model for Italian.

```{r lmer-it}
vowels.it <- filter(vowels, language == "italian")

model.it <- lmer(vowel.duration ~ c2phonation * vowel + c1phonation + c2place +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.it
              )

summary(model.it)

mixed(vowel.duration ~ c2phonation * vowel + c1phonation + c2place +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.it)
```

```{r italian-effects-plot}
plot(allEffects(model.it))
```

## Vowel duration and consonant closure duration

```{r lmer-closure-it}
vowels.closure.it <- filter(vowels, language == "italian")

model.closure.it <- lmer(vowel.duration ~ closure.duration * vowel + 
                             c1phonation + c2place + c2place:vowel +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.closure.it
              )

summary(model.closure.it)

mixed(vowel.duration ~ closure.duration * vowel + 
                             c1phonation + c2place + c2place:vowel +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.closure.it
      )
```

```{r closure-italian-effects-plot}
plot(allEffects(model.closure.it))
```

## Vowel duration and consonant duration

```{r lmer-consonants-it}
vowels.consonants.it <- filter(vowels, language == "italian")

model.consonants.it <- lmer(vowel.duration ~ consonant.duration * vowel + 
                             c1phonation + c2place + c2place:vowel +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.consonants.it
              )

summary(model.consonants.it)

mixed(vowel.duration ~ consonant.duration * vowel + 
                             c1phonation + c2place + c2place:vowel +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.consonants.it
      )
```

```{r consonant-italian-effects-plot}
plot(allEffects(model.consonants.it))
```

## Consonant closure duration and voicing

```{r lmer-closure-voicing-it}
vowels.closvoic.it <- filter(vowels, language == "italian")

model.closvoic.it <- lmer(closure.duration ~ c2phonation +  vowel + 
                             c1phonation + c2place +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.closvoic.it
              )

summary(model.closvoic.it)

mixed(closure.duration ~ c2phonation * vowel + 
                             c1phonation + c2place + c2place:vowel +
                  sentence.duration + (1 | word) + (1|speaker),
              data = vowels.closvoic.it
      )
```

```{r closure-voicing-italian-effects-plot}
plot(allEffects(model.closvoic.it))
```

# Polish

Fit a mixed effect linear model for Polish

```{r pl-vowel-phonation}
vowels.pl <- filter(vowels, language == "polish", closure.duration < 90)

model.pl <- lmer(vowel.duration ~ c2phonation * vowel + c2place +
                  sentence.duration + (1 | word),
              data = vowels.pl
              )

summary(model.pl)

mixed(vowel.duration ~ c2phonation * vowel + c2place +
                  sentence.duration + (1 | word),
              data = vowels.pl)
```

```{r polish-effects-plot}
plot(allEffects(model.pl))
```

```{r pl-closure}
closure.pl <- lmer(
    closure.duration ~
        c2phonation +
        vowel +
        sentence.duration +
        (1|word),
    data = vowels.pl
)

summary(closure.pl)
plot(allEffects(closure.pl))

mixed(
    closure.duration ~
        c2phonation +
        vowel +
        sentence.duration +
        (1|word),
    data = vowels.pl
)
```


```{r pl-vowel-closure}
vowels.closure.pl <- lmer(
    vowel.duration ~
        closure.duration +
        vowel +
        c2phonation +
        sentence.duration +
        (1|word),
    data = vowels.pl
)

summary(vowels.closure.pl)
plot(allEffects(vowels.closure.pl))

mixed(
    vowel.duration ~
        closure.duration +
        vowel +
        c2phonation +
        sentence.duration +
        (1|word),
    data = vowels.pl
)
```


# Inter-speaker variation

```{r variation}
dodge <- position_dodge(width = 0.5)

ggplot(filter(vowels.it, c2place == "velar"), aes(c2phonation, vowel.duration, colour = speaker)) +
    facet_grid(. ~ vowel) +
    geom_violin(position = dodge) +
    geom_boxplot(width=0.1, position = dodge)

ggplot(filter(vowels.it, c2place == "coronal"), aes(c2phonation, vowel.duration, colour = speaker)) +
    facet_grid(. ~ vowel) +
    geom_violin(position = dodge) +
    geom_boxplot(width=0.1, position = dodge)

ggplot(vowels.pl, aes(c2phonation, vowel.duration)) +
    facet_grid(. ~ vowel + c2place) +
    geom_violin() +
    geom_boxplot(width=0.2)
```

# Proportions

```{r proportions}
proportions <- vowels %>%
    group_by(c2phonation, language) %>%
    summarise(
        total = mean(vowel.duration, na.rm = TRUE) +
            mean(closure.duration, na.rm = TRUE),
        vowel = mean(vowel.duration, na.rm = TRUE) / total,
        closure = mean(closure.duration, na.rm = TRUE) / total
    ) %>%
    gather(segment, duration, vowel:closure)
```

```{r plot-proportions}
ggplot(proportions, aes(c2phonation, duration, fill = segment)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    facet_grid(language ~ .)
```

