---
title: "Wavegram"
author: "Stefano Coretta"
date: "10/01/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(itsadug)
library(tidymv)
```

# Data import

```{r import}
languages <- read_csv("./voicing-effect/data/datasets/languages.csv")
words <- read_csv("./voicing-effect/data/datasets/stimuli.csv")

wavegram <- list.files(path = "./voicing-effect/data/datasets/egg",
                   pattern = "*-wavegram.csv",
                   full.names = TRUE) %>%
    map_df(~read_csv(.)) %>%
    left_join(y = languages) %>%
    left_join(y = words) %>%
    filter(c1phonation == "voiceless") %>%
    mutate_if(is.character, as.factor)
```

# Exploration

```{r it01-gam}
it01_gam <- bam(
    amplitude ~
        c2phonation +
        s(sequence) + s(sample) +
        s(sequence, by = c2phonation) + s(sample, by = c2phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = c2phonation),
    data = filter(wavegram, speaker == "it01")
)
```

```{r it01-gam-plot}
fvisgam(
    it01_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiceless"),
    zlim = c(0, 1)
)

fvisgam(
    it01_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiced"),
    zlim = c(0, 1)
)
```

```{r pl05-gam}
pl05_gam <- bam(
    amplitude ~
        c2phonation +
        s(sequence) + s(sample) +
        s(sequence, by = c2phonation) + s(sample, by = c2phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = c2phonation),
    data = filter(wavegram, speaker == "pl05")
)
```

```{r pl05-gam-plot}
fvisgam(
    pl05_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiceless"),
    zlim = c(0, 1)
)

fvisgam(
    pl05_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiced"),
    zlim = c(0, 1)
)
```

```{r pl04-gam}
pl04_gam <- bam(
    amplitude ~
        c2phonation +
        s(sequence) + s(sample) +
        s(sequence, by = c2phonation) + s(sample, by = c2phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = c2phonation),
    data = filter(wavegram, speaker == "pl04")
)
```

```{r pl04-gam-plot}
fvisgam(
    pl04_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiceless"),
    zlim = c(0, 1)
)

fvisgam(
    pl04_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiced"),
    zlim = c(0, 1)
)
```

```{r italian-gam}
italian_gam <- bam(
    amplitude ~
        c2phonation +
        s(sequence) + s(sample) +
        s(sequence, by = c2phonation) + s(sample, by = c2phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = c2phonation) +
        s(sequence, speaker, bs = "fs"),
    data = filter(wavegram, language == "italian")
)
```

```{r italian-gam-plot}
fvisgam(
    italian_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiceless"),
#    zlim = c(0, 1),
    rm.ranef = TRUE
)

fvisgam(
    italian_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiced"),
#    zlim = c(0, 1),
    rm.ranef = TRUE
)

plot_diff2(
    italian_gam,
    view = c("sequence","sample"),
    comp = list(c2phonation = c("voiced", "voiceless")),
    rm.ranef = TRUE
)
```

```{r polish-gam}
polish_gam <- bam(
    amplitude ~
        c2phonation +
        s(sequence) + s(sample) +
        s(sequence, by = c2phonation) + s(sample, by = c2phonation) +
        ti(sequence, sample) +
        ti(sequence, sample, by = c2phonation) +
        s(sequence, speaker, bs = "fs"),
    data = filter(wavegram, language == "polish")
)
```

```{r polish-gam-plot}
fvisgam(
    polish_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiceless"),
#    zlim = c(0, 1),
    rm.ranef = TRUE
)

fvisgam(
    polish_gam,
    view = c("sequence","sample"),
    cond = list(c2phonation = "voiced"),
#    zlim = c(0, 1),
    rm.ranef = TRUE
)

plot_diff2(
    polish_gam,
    view = c("sequence","sample"),
    comp = list(c2phonation = c("voiced", "voiceless")),
    rm.ranef = TRUE
)
```
