---
title: "Pre-registration of a study on tongue root advancement"
author: "Stefano Coretta, Steven M. Lulich"
date: "05/10/2018"
output:
  pdf_document:
    citation_package: natbib
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
bibliography: linguistics.bib
biblio-style: unified.bst
mainfont: DejaVu Sans
fontsize: 11pt
header-includes:
- \usepackage{cleveref}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Study information

## Title



## Authorship

Stefano Coretta (The University of Manchester, UK), Steven M. Lulich (Indiana University, USA).

## Research questions

An exploratory study of articulatory properties of link between consonant voicing and vowel duration [@coretta2018f; @coretta2018d] showed that tongue root advancement is initiated and executed during the production of vowels preceding both voiced and voiceless stops in Italian and Polish.\footnote{Tongue root displacement data was gathered from the stressed vowel in CV́CV words. C1 is /p/, C2 is either /t, d, k, g/, and V1 = V2 = /a, o, u/.}
@coretta2018d proposes that root advancement might have originally been a mechanical consequence of tongue body (dorsum/tip) raising, then evolutionarily coopted for cavity enlargement in the context of voiced stops.

It is also known that during the production of labial stops (both voiceless and voiced) the tongue body lowers [@vazquez-alvarez2007].
A cooptation mechanism parallel to that of tongue root advancement might have operated with tongue body lowering in the context of voiced labial stops.

The following research questions derive from the cooptation hypothesis:

1. Does the tongue root advances during vowels before voiceless and voiced velar stops?
2. Does the tongue body lowers during vowels before voiceless and voiced labial stops?
3. Are tongue root advancement and tongue body dorsum mechanically linked?
4. What is the relationship of timing and velocity of the advancing gesture in vowels before voiceless and voiced velar stop contexts?

## Hypotheses

The following specific hypotheses are tested:

1. The tongue root advances during the production of vowels before voiceless and voiced velar stops.
2. The tongue body lowers during the production of vowels before voiceless and voiced velar stops.
3. Tongue root advancement and tongue dorsum raising are synchronous.
4.

# Sampling plan

## Existing data

## Explanation of existing data

## Data collection procedures

### Participants

Inclusion rule: Native speakers of American English, 18+ yo, with no reported hearing or speaking disorders, with normal or corrected to normal vision.

### Procedure

Ultrasound data will be collected with a Philips EPIQ 7G system using an xMatrix 117 x6-1 digital 3D/4D transducer.
An Articulate Instrument headset will be used for probe stabilisation.
Audio data will be recorded with a SHURE KSM32 microphone (sample rate 48 kHz, 16-bit).
The participant will read the target words (\Cref{s:manipulated}) embedded in a frame sentence (*I said a "X" again*).

## Sample size

20 participants, 8 words, 10 repetitions.
Grand total: 1600 observations.

## Sample size rationale

There is a general consensus in ultrasound tongue imaging studies that a number of participants between 10 and 20 is acceptable, given the time resources necessary for processing the data.

## Stopping rule

Data collection will be terminated if the 20 participants target is not reached by the October 29th 2018.

# Variables

## Manipulated variables
\label{s:manipulated}

* **Place of articulation**: velar (/k, g/), labial (/p, b/)
* **Voicing**: voiceless (/k, p/), voiced (/g, b/)

The word stimuli:

\begin{tabular}{ll}
pop & pob  \\
caulk & cog \\
popper & pobber \\
cocker & cogger \\
\end{tabular}

## Measured variables

* **Tongue root displacement** during the vowel (TRD)
* **Tongue dorsum displacement** during the vowel (TDD)
* **Tongue body displacement** during the vowel (TBD)
* **Gesture onset of tongue root advancement** (TR-GONS)
* **Gesture onset of tongue dorsum raising** (TD-GONS)
* **Maximum displacement of tongue dorsum raising** (TD-MAX)
* **TD-MAX to TR/TD-GONS**
* **TRA velocity**

## Indices

NA.

# Design plan

## Study type

Experiment---A researcher randomly assigns treatments to study subjects, this includes field or lab experiments.
This is also known as an intervention experiment and includes randomized controlled trials.

## Blinding

No blinding is involved in this study.

## Study design

Repeated measures, mixed design.

## Randomisation

The word stimuli will be randomised across each block and across speakers.

# Analysis plan

## Statistical models
\label{s:stats}

Five statistical models will be fit to test the hypothesis in ...

1. A generalised additive mixed model with tongue root

## Transformations

NA.

## Follow-up analyses

NA.

## Inference criteria

*P*-values will be used for the effect of vowel height on vowel duration, VOT, and RVoffT, with $\alpha$ = 0.05.
*P*-values below 0.05 will be deemed significant.
Bayes factors will be employed for the effect of vowel height on voicing interval duration, since I am interested in testing both the null and the alternative hypotheses.
The recommendations in \citet[139]{raftery1995} for the interpretation of the Bayes factors will be followed.

## Data exclusion


## Missing data

NA.

## Exploratory analysis



# Script (Optional)

## Analysis scripts (Optional)

See \Cref{s:stats}.

# Other
\label{s:other}
