---
title: "Compensatory aspects of the effect of voicing on vowel duration in English"
author: "Stefano Coretta"
output:
  pdf_document:
    citation_package: natbib
    latex_engine: xelatex
    number_sections: yes
bibliography: linguistics
biblio-style: unified
mainfont: Tinos
fontsize: 12pt
indent: true
header-includes:
- \usepackage{cleveref}
- \usepackage{ctable}
- \usepackage{enumerate}
- \usepackage{lineno}
- \linenumbers
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
```

# Introduction

Consonants and vowels are known to excise a reciprocal influence in a variety of ways.
One such way is the well-established tendency for vowels to have shorter durations when followed by voiceless stops and longer durations when followed by voiced stops.
This so-called 'voicing effect' has been long recognised in a plethora of languages across different linguistic families.
English is possibly by far the most investigated language in relation to the voicing effect.
Several hypotheses have been proposed as to the origin of this phenomenon, however no one particular hypothesis has gained unequivocal consensus.

\citet{coretta2018j} proposes to seek the source of the voicing effect in a compensatory mechanism between vowel and consonant closure duration.
In an exploratory study of acoustic durations in 17 Italian and Polish speakers, Coretta finds that the duration of the interval between two consecutive consonant releases is not affected by the voicing status of the second consonants.
In particular, Coretta investigated disyllabic words of the form CV́CV (with lexical stress on the first syllable), where the second consonant was either voiceless or voiced.
The results of that study suggest that, for example, the duration of the release-to-release interval in a word like /pata/ is non-significantly different from that in /pada/.

\citet{coretta2018j} argues that the temporal stability of the release-to-release interval is compatible with a compensatory temporal adjustment account of the voicing effect, which states that vowels are shorter when followed by voiceless stops because the latter have long closure durations, and vice versa with voiced stops, which have shorter closure durations \citep{lindblom1967, slis1969a, slis1969, lehiste1970, lehiste1970a}.
Coretta also reviews some of the shortcomings of the compensatory account and concludes that the release-to-release invariance offers a resolution to those.
In particular, previous versions of the account are not clear on within which speech interval the compensation is implemented.
Both the syllable \citep{lindblom1967, farnetani1986} and the word \citep{slis1969a, slis1969, lehiste1970, lehiste1970a} have been proposed but subsequently criticised on empirical grounds \citet{chen1970, jacewicz2009, maddieson1976}.

Given the temporal stability of the release-to-release interval and the differential closure duration in voiceless vs. voiced stops \citep{lisker1957, van-summers1987, davis1989, de-jong1991}, it follows that the timing of the consonant closure onset within that interval will decide on the respective durations of vowel and consonant closure.
\citet{coretta2018j} thus proposes that the source of the voicing effect can be seen in the temporal stability of the release-to-release interval in relation to the voicing of the second consonant and the effect of voicing on closure duration.
Other properties of speech production and perception can of course further contribute to the emergence and enhancement of the voicing effect (see \citealt{begus2017} for an overview).

English is generally the language given as an example in which the voicing effect has a big magnitude.
This fact is normally attributed to phonologisation of the voicing effect in this language \citet{sharf1964, de-jong2004}.
Indeed, previous studies on English report a difference in vowel duration before voiceless vs. voiced stops which ranges between 20 and 150 ms.
<!-- update estimates based on analysis in the supplement -->
A Bayesian meta-analysis of the English voicing effect (See Supplemental materials) indicates that 95% credible interval for the effect of voicing in monosyllabic words is between 55 and 95 ms.
This means that, based on the data, the true effect lies within that interval at a probability of 95%, on in other words we can be 95% sure that the effect is between 55-95 ms.

## Research hypotheses

The principal aim of this study is to test whether the same temporal stability observed for the release-to-release interval in Italian and Polish disyllabic words can be observed in English.
\citet{jacewicz2009} report that monosyllabic words in American English are longer when the second consonant is voiced.
Based on this finding, it is expected that the duration of the release-to-release interval will differ in monosyllabic words depending on C2 voicing.
More specifically, the release-to-release duration should be longer when C2 is voiced.
\citet{jacewicz2009} attribute the difference in word duration to the difference in vowel duration before voiceless vs. voiced stops.
Thus, we can expect the magnitude of the difference in release-to-release duration to be close to the difference in vowel duration.

The data in \citet{coretta2018j} suggest that the intrinsic duration of vowels and consonants can contribute to the duration of the release-to-release interval.
In particular, release-to-release intervals containing a high vowel have shorter durations than those with a low vowel in \citet{coretta2018j}.
This is not surprising, given that a well known cross-linguistic tendency is that high vowels are shorter than low vowels \citep{hertrich1997, esposito2002, mortensen2013, toivonen2015, kawahara2017}.
As for the consonant place of articulation, the interval is shorter in Italian and Polish if the second consonant is velar compared to when it is coronal.
The closure of velar stops is shorter than that of other stops (see for example \citealt{sharf1962}).
It can thus be expected that intervals with a velar stop in English will be shorter than intervals with consonants of other places of articulation.

To summarise, the following research questions and respective hypotheses were formulated:

* Q1: Is the duration of the interval between two consecutive stop releases (the release to release interval) in monosyllabic and disyllabic words affected by the voicing of C2 in English?
  * H1a: The duration of the release to release interval is not affected by C2 voicing in disyllabic words.
  * H1b: The release to release interval is longer in monosyllabic words with a voiced C2 than in monosyllabic words with a voiceless C2.
* Q2: Is the duration of the release to release interval affected by (a) the number of syllables of the word, (b) the quality of V1, and (c) the place of C2?
  * H2a: The release to release interval is longer in monosyllabic than in disyllabic words.
  * H2b: The duration of the release to release interval decreases according to the hierarchy /ɑː/, /əː/, /iː/.
  * H2c: The release to release interval is shorter when C2 is velar.
* Q3: What is the estimated difference in the effect of voicing on vowel and stop closure duration between monosyllabic and disyllabic words?
  * H3: The effect of voicing on vowel duration is greater in monosyllabic than in disyllabic words.

# Methods

The research design and data analyses of this study has been pre-registered at the Open Science Framework.

## Participants

The participants of this study were 15 native speakers of British English, who were born and brought up in the Greater Manchester area.
All the speakers were undergraduate students at the University of Manchester with no reported hearing or speaking disorders, and with normal or corrected to normal vision.
The participants signed a written consent form and received £5 for participation.

Sample size and stopping rule were determined prior to data collection by the Region Of Practical Equivalence (ROPE) method \citet{kruschke2015, vasisht2018a}.
A 'no-effect' region of values around 0 is first identified.
The null region (the ROPE) can be thought of as the Bayesian 95% credible interval from a distribution, the values within which can be interpreted as a null effect.
For this study, a ROPE between −10 and +10 ms has been chosen.
The width of 20 ms is based on the estimates of the just noticeable difference in \citet{huggins1972} and \citet{nooteboom1980}.

<!-- explain why 20 ms -->

Once a ROPE width is set, the goal is to collect data until the width of the 95% credible interval of the tested effect is equal to or less than the ROPE width (in this study, 20 ms).
Due to resource and time constraints specific to this particular study, a second condition had to be included in the stopping rule such that data collection would be have to stop on April 5th 2019, independent of the the ROPE condition.

## Equipment

Audio recordings were obtained in a sound-attenuated room in the Phonetics Laboratory of the University of Manchester, with a Zoom H4n Pro recorder and a RØDE Lavalier microphone, at a sample rate of 44100 Hz (16-bit, downsampled to 22050 Hz for analysis).
The Lavalier microphone was clipped on the participants cloths, about 20 cm under their mouth, displaced a few centimetres on one side.

## Materials

<!-- explain why only velars and labials and why diagonal vowels -->

The test words were C\textsubscript{1}V\textsubscript{1}C\textsubscript{2}(VC) words, where C\textsubscript{1} = /t/, V\textsubscript{1} = /iː, əː, ɑː/, C\textsubscript{2} = /p, b, k, g/, and (VC) = /əs/.
This structure specification generates 24 test words, shown in \Cref{t:words}.
Each word was embedded in the following frame sentences: *I'll say X this Thursday*, *You'll say X this Monday*, *She'll say X this Sunday*, *We'll say X this Friday*, *They'll say X this Tuesday*.
Each word + frame combination was included once in the stimuli list, so that each speaker would read 120 sentence stimuli (24 words × 5 frames).

## Procedure

The participants were first debriefed on the experimental procedure.
Prior to recording, the participants familiarised themselves with the materials by reading them aloud and were instructed not to insert pauses anywhere within the sentence stimuli and to try and keep a similar intonation contour for the total duration of the experiment.
They were also given the change to take any number of breaks at any point during recording.
Misreadings or speech errors were corrected by letting the participant repeat the stimulus.
The reading task took around 6 to 10 minutes.

## Data processing and measurements

The audio recordings were downsampled to 22050 Hz for analysis.
A forced-aligned transcription was obtained with the SPeech Phonetisation Alignment and Syllabification software (SPPAS, \citealt{bigi2015}).
The automatic annotation was corrected by the author according to the principles of phonetic segmentation detailed in \citet{machac2009}.
A custom Praat script was written to automatically detect the burst onset of the consonants in the test words, using the algorithm in \citet{ananthapadmanabha2014}.
The output was checked and manually corrected by the author when necessary.

The following measures were obtained:

* Duration of the release-to-release interval: from the release of C1 to the release of C2.
* V1 duration: from appearance to disappearance of higher formant structure in the spectrogram in correspondence of V1 \citep{machac2009}.
* C2 closure duration: from disappearance of higher formant structure in the V1C2 sequence to the release of C2 \citep{machac2009}.
* Speech rate: calculated as number of syllables per second (number of syllables in the sentence divided by the sentence duration in seconds, \citealt{plug2018}).

## Statistical analysis

All statistical analyses were performed in R v3.5.2 \citep{r-core-team2018}.
Bayesian regression models were fit with brms \citep{burkner2017, burkner2018}.
All factors were coded using treatment contrasts with the first level as the reference level: number of syllables (disyllabic, monosyllabic), vowel (/ɑː/, /ɜː/, /iː/), C2 voicing (voiceless, voiced), C2 place of articulation (velar, labial).
Speech rate has been centred when included in the models so that the intercept can be interpreted as the mean intercept at mean speech rate.
