---
title: "Meta-analysis of the voicing effect in English"
author: "Stefano Coretta"
date: "07/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
theme_set(theme_minimal())
library(brms)
library(bayesplot)
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
options(mc.cores = parallel::detectCores())
```

```{r data, message=FALSE}
stressed <- read_csv("./english-ve-meta/stressed.csv") %>%
  mutate(
    voice = factor(voice, levels = c("voiceless", "voiced")),
    n_syl = factor(n_syl, levels = c("mono", "di")),
    word_pos_2 = ifelse(word_pos == "medial", "medial", "final"),
    year = str_sub(study, str_length(study) - 3, str_length(study))
  ) %>%
  mutate_if(is.character, as.factor)

unstressed <- read_csv("./english-ve-meta/unstressed.csv") %>%
  gather("voice_stat", "value", voiced_mean:voiceless_sd) %>%
  separate(voice_stat, c("voice", "stat")) %>%
  spread(stat, value) %>%
  rename(v_duration =  "mean") %>%
  mutate(
    voice = factor(voice, levels = c("voiceless", "voiced")),
    speaker = as.factor(speaker),
    place = factor(place, levels = c("labial", "alveolar", "velar"))
  )

unstressed_red <- filter(unstressed, v_context == "reduced")
unstressed_unr <- filter(unstressed, v_context == "unreduced")

studies <- stressed %>% select(study, n_syl:word_pos) %>% unique() %>%
  mutate(word_pos_2 = ifelse(word_pos == "medial", "medial", "final"))
```

# Obtain estimates from previous studies

```{r heffner1937}
h37 <- filter(stressed, study == "heffner1937")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

h37_bm <- brm(
  v_duration ~
    voice,
  data = h37,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/h37_bm"
)
```

```{r housefairbanks1953}
hf53 <- filter(stressed, study == "housefairbanks1953")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

hf53_bm <- brm(
  v_duration ~
    voice,
  data = hf53,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/hf53_bm"
)
```

```{r petersonlehiste1960}
pl60 <- filter(stressed, study == "petersonlehiste1960")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

pl60_bm <- brm(
  v_duration ~
    voice,
  data = pl60,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/pl60_bm"
)
```

```{r sharf1962}
s62_di <- filter(stressed, study == "sharf1962_di")
s62_mono <- filter(stressed, study == "sharf1962_mono")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

s62_di_bm <- brm(
  v_duration ~
    voice,
  data = s62_di,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/s62_di_bm"
)

s62_mono_bm <- brm(
  v_duration ~
    voice,
  data = s62_mono,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/s62_mono_bm"
)
```

```{r chen1970}
c70 <- filter(stressed, study == "chen1970")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

c70_bm <- brm(
  v_duration ~
    voice,
  data = c70,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/c70_bm"
)
```

```{r klatt1973}
k73_di <- filter(stressed, study == "klatt1973_di")
k73_mono <- filter(stressed, study == "klatt1973_mono")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

k73_di_bm <- brm(
  v_duration ~
    voice,
  data = k73_di,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/k73_di_bm",
  control = list(adapt_delta = 0.999)
)

k73_mono_bm <- brm(
  v_duration ~
    voice,
  data = k73_mono,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/k73_mono_bm",
  control = list(adapt_delta = 0.999)
)
```

```{r davis1989}
d89 <- filter(stressed, study == "davis1989")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced)
)

d89_bm <- brm(
  v_duration | se(sd) ~
    voice,
  data = d89,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/d89_bm"
)
```

```{r laeufer1992}
l92 <- filter(stressed, study == "laeufer1992")

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced),
  prior(cauchy(0, 25), class = sigma)
)

l92_bm <- brm(
  v_duration ~
    voice,
  data = l92,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/l92_bm"
)
```

I suspect that the values reported as standard deviations are actually variances.

```{r ko2018}
k18 <- filter(stressed, study == "ko2018") %>%
  mutate(sd = sqrt(sd)) # to get sd from variance

priors <- c(
  prior(normal(0, 300), class = Intercept),
  prior(normal(0, 100), class = b, coef = voicevoiced)
)

k18_bm <- brm(
  v_duration | se(sd) ~
    voice,
  data = k18,
  prior = priors,
  seed = 9899,
  file = "./english-ve-meta/data/cache/k18_bm"
)
```

```{r estimated}
estimated <- list()

estimated[["heffner1937"]] <- fixef(h37_bm)["voicevoiced",]
estimated[["housefairbanks1953"]] <- fixef(hf53_bm)["voicevoiced",]
estimated[["petersonlehiste1960"]] <- fixef(pl60_bm)["voicevoiced",]
estimated[["sharf1962_di"]] <- fixef(s62_di_bm)["voicevoiced",]
estimated[["sharf1962_mono"]] <- fixef(s62_mono_bm)["voicevoiced",]
estimated[["chen1970"]] <- fixef(c70_bm)["voicevoiced",]
estimated[["klatt1973_di"]] <- fixef(k73_di_bm)["voicevoiced",]
estimated[["klatt1973_mono"]] <- fixef(k73_mono_bm)["voicevoiced",]
estimated[["davis1989"]] <- fixef(d89_bm)["voicevoiced",]
estimated[["laeufer1992"]] <- fixef(l92_bm)["voicevoiced",]
estimated[["ko2018"]] <- fixef(k18_bm)["voicevoiced",]

estimated_tbl <- plyr::ldply(estimated, .id = "study") %>%
  mutate(
    year = str_sub(study, str_length(study) - 3, str_length(study)),
    source = "original"
  ) %>%
  left_join(y = studies)
```

```{r estimated_v}
estimated_v <- list()

estimated_v[["heffner1937"]] <- fixef(h37_bm)["Intercept",]
estimated_v[["housefairbanks1953"]] <- fixef(hf53_bm)["Intercept",]
estimated_v[["petersonlehiste1960"]] <- fixef(pl60_bm)["Intercept",]
estimated_v[["sharf1962_di"]] <- fixef(s62_di_bm)["Intercept",]
estimated_v[["sharf1962_mono"]] <- fixef(s62_mono_bm)["Intercept",]
estimated_v[["chen1970"]] <- fixef(c70_bm)["Intercept",]
estimated_v[["klatt1973_di"]] <- fixef(k73_di_bm)["Intercept",]
estimated_v[["klatt1973_mono"]] <- fixef(k73_mono_bm)["Intercept",]
estimated_v[["davis1989"]] <- fixef(d89_bm)["Intercept",]
estimated_v[["laeufer1992"]] <- fixef(l92_bm)["Intercept",]
estimated_v[["ko2018"]] <- fixef(k18_bm)["Intercept",]

estimated_v_tbl <- plyr::ldply(estimated_v, .id = "study") %>%
  mutate(year = str_sub(study, str_length(study) - 3, str_length(study)))
```

# Meta-analysis

```{r meta-bm}
priors <- c(
  prior(normal(0, 100), class = Intercept),
  prior(cauchy(0, 25), class = sd)
)

meta_bm <- brm(
  Estimate | se(`Est.Error`) ~ (1 | study),
  data = estimated_tbl,
  prior = priors,
  control = list(adapt_delta = 0.999),
  seed = 9899,
  file = "./english-ve-meta/data/cache/meta_bm"
)

summary(meta_bm)
```

```{r studies-shrink}
# Code from Nicenboim et al. 2018

post_study <- c(posterior_samples(meta_bm, pars = "b_Intercept")) +
  posterior_samples(meta_bm, pars = "r_study")

studies_shrink <- post_study %>%
  summarise_all(funs(list(c(mean(.), quantile(., probs = c(.025, 0.975)))))) %>%
  unnest %>%
  transpose %>%
  setNames(c("Estimate", "Q2.5", "Q97.5")) %>%
  map_df(unlist) %>%
  mutate(
    study = sort(estimated_tbl$study),
    year = str_sub(study, str_length(study) - 3, str_length(study)),
    source = "meta-analysis"
  ) %>%
  left_join(y = studies)
```

```{r meta-bm-2}
priors <- c(
  prior(normal(0, 100), class = Intercept),
  prior(cauchy(0, 25), class = sd)
)

meta_bm_2 <- brm(
  Estimate | se(`Est.Error`) ~ (1 | study),
  data = filter(estimated_tbl, study != "chen1970"),
  prior = priors,
  control = list(adapt_delta = 0.999),
  seed = 9899,
  file = "./english-ve-meta/data/cache/meta_bm_2"
)
```

```{r meta-bm-3}
priors <- c(
  prior(normal(0, 100), class = Intercept),
  prior(cauchy(0, 25), class = sd)
)

meta_bm_3 <- brm(
  Estimate | se(`Est.Error`) ~ (1 | study),
  data = filter(estimated_tbl, study %in% c("petersonlehiste1960", "klatt1973_di", "klatt1973_mono", "davis1989")),
  prior = priors,
  control = list(adapt_delta = 0.999),
  seed = 9899,
  file = "./english-ve-meta/data/cache/meta_bm_3"
)

summary(meta_bm_3)
```

```{r meta-bm-4}
priors <- c(
  prior(normal(0, 100), class = Intercept),
  prior(normal(0, 50), class = b, coef = syl_posnonMfinal),
  prior(cauchy(0, 25), class = sd)
)

meta_bm_4 <- brm(
  Estimate | se(`Est.Error`) ~ syl_pos + (1 | study),
  data = estimated_tbl,
  prior = priors,
  control = list(adapt_delta = 0.999),
  seed = 9899,
  file = "./english-ve-meta/data/cache/meta_bm_4"
)

summary(meta_bm_4)
```

# Plot estimates

```{r}
estimated_tbl %>%
  ggplot(aes(Estimate, reorder(study, Estimate), colour = syl_pos, linetype = word_pos_2)) +
  geom_vline(aes(xintercept = 0), colour = "grey") +
  geom_vline(aes(xintercept = 35.20), colour = "skyblue4", linetype = "dashed") +
  geom_vline(aes(xintercept = 87.99), colour = "skyblue4", linetype = "dashed") +
  geom_vline(aes(xintercept = 61.35), colour = "skyblue4") +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0) +
  scale_color_brewer(type = "qual", palette = 2) +
  labs(
    x = "Difference in vowel duration (ms)",
    y = "Study",
    colour = "Syllable position",
    linetype = "Word position"
  )
```

```{r}
studies_shrink %>%
  ggplot(aes(Estimate, reorder(study, Estimate), colour = syl_pos, linetype = word_pos_2)) +
  geom_vline(aes(xintercept = 0), colour = "grey") +
  geom_vline(aes(xintercept = 35.20), colour = "skyblue4", linetype = "dashed") +
  geom_vline(aes(xintercept = 87.99), colour = "skyblue4", linetype = "dashed") +
  geom_vline(aes(xintercept = 61.35), colour = "skyblue4") +
  geom_point(size = 2) +
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0) +
  scale_color_brewer(type = "qual", palette = 2) +
  labs(
    x = "Difference in vowel duration (ms)",
    y = "Study",
    colour = "Syllable position",
    linetype = "Word position"
  )
```

```{r}
bind_rows(estimated_tbl, studies_shrink) %>%
  ggplot(aes(reorder(study, Estimate), Estimate, linetype = source, colour = syl_pos)) +
  geom_hline(aes(yintercept = 0), colour = "grey") +
  geom_hline(aes(yintercept = 35.20), colour = "skyblue4", linetype = "dashed") +
  geom_hline(aes(yintercept = 87.99), colour = "skyblue4", linetype = "dashed") +
  geom_hline(aes(yintercept = 61.35), colour = "skyblue4") +
  geom_point(size = 2, position = position_dodge(width = 0.8)) +
  geom_errorbar(aes(ymin = Q2.5, ymax = Q97.5), width = 0, position = position_dodge(width = 0.8)) +
  scale_color_brewer(type = "qual", palette = 2) +
  scale_linetype_discrete(breaks = c("original", "meta-analysis")) +
  scale_x_discrete(labels = c("Davis (1989)", "Klatt (1973) disyllabic", "Sharf (1962) disyllabic", "Ko (2018)", "Sharf (1962) monosyllabic", "Klatt (1973) monosyllabic", "Heffner (1937)", "Laeufer (1992)", "House & Fairbanks (1953)", "Peterson & Lehiste (1960)", "Chen (1970)")) +
  scale_y_continuous(breaks = c(-100, -50, 0, 50, 100, 150, 200)) +
  labs(
    y = "Difference in vowel duration (ms)",
    x = "Study",
    colour = "Syllable position",
    linetype = "Source"
  ) +
  coord_flip() +
  theme(panel.grid.major.y = element_blank(), panel.grid.minor.y = element_blank())
```

```{r}
estimated_v_tbl %>%
  ggplot(aes(Estimate, reorder(study, Estimate))) +
  # geom_vline(aes(xintercept = 34.73), colour = "blue", linetype = "dashed") +
  # geom_vline(aes(xintercept = 94.90), colour = "blue", linetype = "dashed") +
  geom_point() +
  geom_errorbarh(aes(xmin = Q2.5, xmax = Q97.5), height = 0.2)
```

```{r}
post_syl <- c(posterior_samples(meta_bm_4, pars = "b_Intercept")) +
  posterior_samples(meta_bm_4, pars = "b_syl_posnonMfinal")

post_syl <- bind_cols(post_syl, posterior_samples(meta_bm_4, pars = "b_Intercept")) %>%
  gather("coef", "posterior")

post_syl %>%
  ggplot(aes(posterior, fill = coef)) +
  geom_vline(aes(xintercept = 0)) +
  geom_density(colour = NA, alpha = 0.8) +
  scale_fill_manual(
    values = c("skyblue3", "orange3"),
    labels = c("monosyllabic", "disyllabic")
  ) +
  scale_x_continuous(breaks = seq(-60, 100, 20)) +
  labs(
    title = "Meta-analytical estimate of the voicing effect",
    x = "Difference in vowel duration (ms)",
    fill = "Word type",
    y = element_blank()
  ) +
  theme(legend.position = "top")
```

# Estimate of voicing effect in unstressed vowels

## Reduced vowels

```{r unstr-priors}
get_prior(
  v_duration | se(sd) ~ voice + place + (1| speaker),
  data = unstressed_red,
  family = gaussian()
)
```

```{r unstr-bm}
priors <- c(
  set_prior("normal(50, 25)", class = "Intercept"),
  set_prior("normal(0, 20)", class = "b", coef = "voicevoiced"),
  set_prior("normal(0, 20)", class = "b", coef = "placealveolar"),
  set_prior("normal(0, 20)", class = "b", coef = "placevelar"),
  set_prior("normal(0, 25)", class = "sd")
)

unstr_bm <- brm(
  v_duration | se(sd, sigma = TRUE) ~ voice + place + (1| speaker),
  data = unstressed_red,
  family = gaussian(),
  prior = priors,
  cores = 4,
  seed = 1989,
  control = list(adapt_delta = 0.99),
  file = "./english-ve-meta/data/cache/unstr_bm"
)
```

```{r unstr-bm-summary}
summary(unstr_bm, prob = 0.9)
```

```{r unstr-bm-pp}
brms::pp_check(unstr_bm, nsamples = 100)
```

```{r unstr-bm-intervals}
mcmc_intervals(as.array(unstr_bm), regex_pars = "b_")
```

```{r unstr-bm-intervals-2}
mcmc_intervals(as.array(unstr_bm), pars = c("b_voicevoiced", "b_placealveolar", "b_placevelar"))
```

```{r unstr-bm-areas}
mcmc_areas(as.array(unstr_bm), pars = c("b_voicevoiced", "b_placealveolar", "b_placevelar"))
```

## Unreduced vowels

```{r unred-priors}
get_prior(
  v_duration | se(sd) ~ voice + place + (1| speaker),
  data = unstressed_unr,
  family = gaussian()
)
```

```{r unred-bm}
priors_unr <- c(
  set_prior("normal(70, 25)", class = "Intercept"),
  set_prior("normal(0, 20)", class = "b", coef = "voicevoiced"),
  set_prior("normal(0, 20)", class = "b", coef = "placealveolar"),
  set_prior("normal(0, 20)", class = "b", coef = "placevelar"),
  set_prior("normal(0, 25)", class = "sd")
)

unred_bm <- brm(
  v_duration | se(sd, sigma = TRUE) ~ voice + place + (1| speaker),
  data = unstressed_unr,
  family = gaussian(),
  prior = priors_unr,
  cores = 4,
  seed = 9891,
  control = list(adapt_delta = 0.9999),
  file = "./english-ve-meta/data/cache/unred_bm"
)
```

```{r unred-bm-summary}
summary(unred_bm, prob = 0.9)
```

```{r unred-bm-areas}
mcmc_areas(as.array(unred_bm), pars = c("b_voicevoiced", "b_placealveolar", "b_placevelar"))
```
