---
title: "Release to release"
author: "Stefano Coretta"
date: "14/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
theme_set(theme_minimal())
library(coretta2018itaegg)
library(lme4)
library(lmerTest)
library(sjPlot)

data("ita_egg")
ita_egg <- ita_egg %>%
  mutate(
    vowel = factor(vowel, levels = c("a", "o", "e", "i", "u")),
    height = factor(height, levels = c("low", "mid-low", "mid-high", "high"))
  ) %>%
  mutate_if(is.character, as.factor)
```

# Plots

```{r rr}
ita_egg %>%
  ggplot(aes(rel_rel)) +
  geom_density() +
  geom_rug()
```


```{r rr-vow}
ita_egg %>%
  ggplot(aes(rel_rel, fill = vowel)) +
  geom_density(alpha = 0.5, size = 0) +
  geom_rug()
```

```{r rr-vow-box}
ita_egg %>%
  ggplot(aes(vowel, rel_rel, fill = height)) +
  geom_boxplot()
```

```{r rr-place-2}
ita_egg %>%
  ggplot(aes(rel_rel, fill = c2_place)) +
  geom_density(alpha = 0.5, size = 0) +
  geom_rug() +
  facet_grid(c1_place ~ .)
```

```{r rr-place-1}
ita_egg %>%
  ggplot(aes(rel_rel, fill = c1_place)) +
  geom_density(alpha = 0.5, size = 0) +
  geom_rug() +
  facet_grid(c2_place ~ .)
```

```{r rr-place-2-box}
ita_egg %>%
  ggplot(aes(c2_place, rel_rel, fill = c2_place)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.05)
```

```{r rr-place-1-box}
ita_egg %>%
  ggplot(aes(c1_place, rel_rel, fill = c1_place)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.05)
```

Could it be that velar consonants had multiple releases and by chosing the first one the interval is longer?

```{r rr-place-c1-c2-box}
ita_egg %>%
  ggplot(aes(c2_place, rel_rel, fill = c2_place)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.05) +
  facet_grid(~ c1_place)
```


```{r rr-rate}
ita_egg %>%
  ggplot(aes(speech_rate,  rel_rel)) +
  geom_point(alpha = 0.5)
```

```{r rr-place-vow}
ita_egg %>%
  ggplot(aes(vowel, rel_rel, fill = height)) +
  geom_boxplot() +
  facet_grid(c2_place ~ c1_place)
```

```{r rr-place-vow}
ita_egg %>%
  ggplot(aes(height, rel_rel, fill = height)) +
  geom_boxplot() +
  facet_grid(c2_place ~ c1_place)
```

# Modelling

```{r rr-place-lm}
rr_place_lm <- lmer(
  rel_rel ~
    c1_place *
    c2_place *
    speech_rate_c +
    (1|speaker) +
    (1|word),
  data = ita_egg
)

summary(rr_place_lm)
```

```{r rr-place-lm-plot}
plot_model(rr_place_lm, type = "pred", terms = c("c1_place", "c2_place"))
```

```{r rr-place-lm-plot-2}
plot_model(rr_place_lm, type = "pred", terms = "speech_rate_c")
```

```{r rr-vow-place-lm}
rr_vow_place_lm <- lmer(
  rel_rel ~
    c2_place *
    vowel *
    speech_rate_c +
    (1|speaker) +
    (1|word),
  data = ita_egg
)

summary(rr_vow_place_lm)
```

```{r rr-vow-lm}
rr_vow_lm <- lmer(
  rel_rel ~
    vowel *
    speech_rate_c +
    (1|speaker) +
    (1|word),
  data = ita_egg
)

summary(rr_vow_lm)
```

```{r rr-place-lm-plot}
plot_model(rr_vow_lm, order.terms = 1:9)
```

```{r rr-place-lm-plot-2}
plot_model(rr_vow_lm, type = "pred", terms = c("vowel"))
```
