---
title: "Voicing during closure"
author: "Stefano Coretta"
date: "14/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
theme_set(theme_minimal())
library(coretta2018itaegg)
library(lme4)
library(lmerTest)
library(sjPlot)

data("ita_egg")
ita_egg <- ita_egg %>%
  mutate(
    vowel = factor(vowel, levels = c("a", "o", "e", "i", "u")),
    height = factor(height, levels = c("low", "mid-low", "mid-high", "high")),
    c1_place = factor(c1_place, levels = c("labial", "coronal", "velar")),
    c2_place = factor(c2_place, levels = c("labial", "coronal", "velar")),
    von_von = (v1_ons - voice_ons) * 1000
  ) %>%
  mutate_if(is.character, as.factor)
```

# Plots

```{r voi-clo}
ita_egg %>%
  ggplot(aes(voi_clo)) +
  geom_density() +
  geom_rug()
```

```{r voi-clo-box}
ita_egg %>%
  ggplot(aes(y = voi_clo)) +
  geom_boxplot() +
  coord_flip() +
  scale_x_continuous(labels = NULL)
```

```{r voi-clo-vow}
ita_egg %>%
  ggplot(aes(voi_clo, fill = vowel)) +
  geom_density(alpha = 0.5, size = 0)
```

```{r voi-clo-vow-box}
ita_egg %>%
  ggplot(aes(vowel, voi_clo, fill = vowel)) +
  geom_boxplot()
```

```{r voi-clo-height-box}
ita_egg %>%
  ggplot(aes(height, voi_clo, fill = height)) +
  geom_boxplot()
```

```{r voi-clo-place-box}
ita_egg %>%
  ggplot(aes(vowel, voi_clo, fill = height)) +
  geom_boxplot() +
  facet_grid(c2_place ~ c1_place)
```

```{r voi-clo-place2-box}
ita_egg %>%
  ggplot(aes(vowel, voi_clo, fill = height)) +
  geom_boxplot() +
  facet_grid(c2_place ~ .)
```

```{r voi-clo-speaker}
ita_egg %>%
  ggplot(aes(voi_clo)) +
  geom_density() +
  facet_wrap(~ speaker)
```

```{r von-von-box}
ita_egg %>%
  ggplot(aes(vowel, von_von, fill = vowel)) +
  geom_boxplot()
```

```{r von-von-box}
ita_egg %>%
  filter(von_von > 0) %>%
  ggplot(aes(vowel, von_von, fill = vowel)) +
  geom_boxplot()
```

```{r von-von-box}
ita_egg %>%
  filter(von_von > 0) %>%
  ggplot(aes(height, von_von, fill = height)) +
  geom_boxplot()
```

```{r voi-clo-lm}
voi_clo_lm <- lmer(
  voi_clo ~
    height +
    c2_place +
    height:c2_place +
    speech_rate_c +
    (1|speaker) +
    (1|word),
  data = ita_egg,
  control = lmerControl(optimizer = "Nelder_Mead")
)
# https://stats.stackexchange.com/a/243225/128897

summary(voi_clo_lm)
```

```{r plot-voi-clo-lm}
plot_model(voi_clo_lm, show.values = TRUE, value.offset = .3, show.p = FALSE, order.terms = c(1:12))
```

Mid-low vowels induce 8 ms voicing bleed, mid-high induce 4.5 ms, high 7 ms.
The gap between voicing and vowel duration is 9.5 in mid-low, 2 in mid-high, and 5 in high.

```{r plot-voi-clo-lm-2}
plot_model(voi_clo_lm, type = "pred", terms = "height")
```

```{r voi-clo-lm-2}
voi_clo_lm_2 <- lmer(
  voi_clo ~
    vowel *
    speech_rate_c +
    (1|speaker) +
    (1|word),
  data = ita_egg
)

summary(voi_clo_lm_2)
```

The following tests the amount of voicing preceding vowel onset.

```{r von-von-clo-lm}
von_von_lm <- lmer(
  von_von ~
    height +
    (1|speaker) +
    (1|word),
  data = ita_egg
)
# https://stats.stackexchange.com/a/243225/128897

summary(von_von_lm)
```
