---
title: "Pilot study of Lombard voicing"
author: "Stefano Coretta"
date: "20/09/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
theme_set(theme_minimal())
library(speakr)
library(lme4)
library(lmerTest)
library(effects)
```

# Extract data

```{r speakr, eval = FALSE}
lmt("./lombard/code/get-measurements.praat.md")
praat_run("./lombard/code/get-measurements.praat")
```

# Import data

```{r read-data}
stimuli <- read_csv("./lombard/task/prompts.csv")

acoustics <- read_csv("./lombard/results/acoustics.csv", na = "--undefined--") %>%
    left_join(y = stimuli)

durations <- read_csv("./lombard/results/durations.csv", na = "--undefined--") %>%
    left_join(y = stimuli) %>%
    mutate_if(is.character, as.factor) %>%
    mutate(
        voicing = factor(voicing, levels = c("voiceless", "voiced")),
        position = factor(position, levels = c("medial", "final")),
        place = factor(place, levels = c("velar", "coronal", "labial"))
    )
```

# Vowel duration

```{r vowel-duration-speaker-plot}
durations %>%
    ggplot(aes(voicing, vowel_duration, colour = position)) +
    geom_boxplot() +
    facet_grid(speaker ~ vowel)
```

```{r vowel-duration-plot}
durations %>%
    ggplot(aes(voicing, vowel_duration, colour = position)) +
    geom_boxplot() +
    facet_grid( ~ vowel)
```

```{r vowel-duration-plot}
durations %>%
    ggplot(aes(position, vowel_duration, colour = voicing)) +
    geom_boxplot()
```

```{r vowel-duration-plot-speakers}
durations %>%
    ggplot(aes(position, vowel_duration, colour = voicing)) +
    geom_boxplot() +
    facet_grid(. ~ speaker)
```

```{r vowel-duration-lmer}
vowel_dur_lm <- lmer(
    vowel_duration ~
        voicing *
        position +
        manner +
        place +
        (1|speaker) +
        (1|word),
    data = durations
)

summary(vowel_dur_lm)

vowel_dur_lm_null <- lmer(
    vowel_duration ~
        voicing *
#        position +
        manner +
        place +
        (1|speaker) +
        (1|word),
    data = durations
)

anova(vowel_dur_lm_null, vowel_dur_lm)
```

```{r vowel-duration-lmer-effects}
plot(allEffects(vowel_dur_lm))
```

# Consonant duration

```{r consonant-duration-plot}
durations %>%
    ggplot(aes(position, consonant_duration, colour = voicing)) +
    geom_boxplot()
```

```{r consonant-duration-lmer}
c_dur_lm <- lmer(
    consonant_duration ~
        voicing *
        position +
        manner +
        place +
        (1|speaker) +
        (1|word),
    data = durations
)

summary(c_dur_lm)

c_dur_lm_null <- lmer(
    consonant_duration ~
        voicing *
#        position +
        manner +
        place +
        (1|speaker) +
        (1|word),
    data = durations
)

anova(c_dur_lm_null, c_dur_lm)
```

```{r consonant-duration-lmer-effects}
plot(allEffects(c_dur_lm))
```

# Word duration

```{r word-duration-plot}
durations %>%
    ggplot(aes(position, word_duration, colour = voicing)) +
    geom_boxplot() +
    ylab("Word duration (seconds)")
```

# Vowel and consonant duration

```{r vowel-consonant-duration-plot}
durations %>%
    ggplot(aes(consonant_duration, vowel_duration, colour = voicing)) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid(position ~ .)
```


```{r f1-plot}
acoustics %>%
    ggplot(aes(point, f1, colour = voicing)) +
    geom_jitter(alpha = 0.5) +
    geom_smooth() +
    facet_wrap(~ vowel)
```

```{r}
acoustics %>%
    ggplot(aes(time_norm, f1, colour = voicing)) +
    geom_point(alpha = 0.5) +
    geom_smooth() +
    facet_wrap(~ vowel)
```

```{r}
acoustics %>%
    ggplot(aes(point, f2, colour = voicing)) +
    geom_jitter(alpha = 0.5) +
    geom_smooth() +
    facet_wrap(~ vowel)
```

```{r}
acoustics %>%
    filter(pitch < 400) %>%
    ggplot(aes(point, pitch, colour = voicing)) +
    geom_jitter(alpha = 0.5) +
    geom_smooth() +
    facet_wrap(~ speaker)
```

# Proportions

```{r proportions}
proportions <- durations %>%
    group_by(voicing, position) %>%
    summarise(
        total = 
            mean(vowel_duration, na.rm = TRUE) +
            mean(consonant_duration, na.rm = TRUE),
        vowel = mean(vowel_duration, na.rm = TRUE),
        consonant = mean(consonant_duration, na.rm = TRUE)
    ) %>%
    gather(segment, duration, vowel:consonant) %>%
    mutate(segment = factor(segment,
                            levels = c("vowel", "consonant")
                            )
           )
```

```{r plot-proportions}
ggplot(proportions, aes(voicing, duration, fill = segment)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    facet_grid(position ~ .) +
    guides(fill = guide_legend(reverse = TRUE))
```
