---
title: "Make stimuli"
author: "Stefano Coretta"
date: "11/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../../"))
library(tidyverse)
```

```{r read-subtlex, message=FALSE}
subtlex <- read_csv("./english/simuli/subtlex.csv")
```

```{r check}
check <- subtlex %>%
  filter(Spelling %in% c("teep","teak", "teeb", "teab", "turp", "turb", "terp", "terb", "tarp", "tarb", "teek", "teak", "teeg", "teag", "turk", "terk", "turg", "terg", "tark", "targ", "teepus", "teapus", "teebus", "teabus", "turpus", "turbus", "terpus", "terbus", "tarpus", "tarbus", "teekus", "teakus", "teegus", "teagus", "turkus", "terkus", "turgus", "tergus", "tarkus", "targus"))
```

```{r create-stimuli}
frames <- c("I'll say '{word}' this Thursday", "You'll say '{word}' this Monday", "She'll say '{word}' this Sunday", "We'll say '{word}' this Friday", "They'll say '{word}' this Tuesday")
words <- c("teep", "teeb", "terp", "terb", "tarp", "tarb", "teek", "teeg", "terk", "terg", "tark", "targ", "teepus", "teebus", "terpus", "terbus", "tarpus", "tarbus", "teekus", "teegus", "terkus", "tergus", "tarkus", "targus")

write_lines("sentence,frame,word", "./english/simuli/stimuli.csv")

for (frame in 1:length(frames)) {
  sink("./english/simuli/stimuli.csv", append = TRUE)
  cat(
    paste(
      str_glue(frames[frame], word = words),
      paste(frames),
      paste(words),
      sep = ","
    ),
    sep = "\n"
  )
  sink()
}
```

