---
title: "Response to reviews"
date: "21/01/2019"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
header-includes:
- \usepackage{xcolor}
- \definecolor{plum}{HTML}{B93B8F}
mainfont: Brill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Editor

I have one major concern about your paper. In the main part of your paper, you present results pooled across subjects. These results show some agreement with your hypotheses. However, in Section C. Individual differences, you show that several individuals do not follow the general trends that you have found in the pooled results. So, why not only present the individual results, since they suggest variability across subjects?

I also think that you need to say something about the resolution of the ultrasound images, since, as noted by Reviewer 1, some movements are very small. In addition, I would like to see some general comments on tongue movements during speech, in particular when you discuss tongue root movement and vowel duration.

I elaborate on these and other issues below.

Line 17
Fowler, 1992 and Lisker 1974, d not present any data on tongue root movements.

Lines 21 and 24
Here, you make claims about earlier works that need to be referenced.

Line 72
…is generally longer than that of voiceless stops…" > …is generally shorter than that of voiceless stops…"

Page 6, second paragraph
Since you bring up possible voicing differences between Italian and Polish, I think it would help if you made clear whether the voiced stops in your material were actually produced with glottal vibrations., If they were not, there would be no need for tongue movements to maintain voicing. Possibly, some of the individual differences may be due to voicing variability.

Page 11, E, Data processing and statistical analysis.
I would suggest saying something about the spatial resolution of the ultrasound system and the reliability of the splines. From Figure 1, it is not immediately clear that you are actually measuring the tongue root.

Page 17, C. Correlation between tongue rot position and V1 duration
Why is this interesting and relevant? Since the tongue is always moving in speech, would it not move longer during a long vowel? The tongue does not appear to have a point target for vowels.

Line 302
Can you explain wat you mean with "curvature"?

Line 333
"…the onset of the forward gesture of   the root is timed relative to a landmark preceding the closure, independent of the duration of the vowel."
I don’t understand what this means. What kind of landmark are you talking about?

Line 391
The duration of 70-90 ms suggested ny Rothenberg (1967) is not based on actual measurements.

Figure 6
The labels and the y-axis values are identical in the left and right plots. The two plots appear to be identical.

References

Ahn. 2015, is available here: http://www.ultrafest2015.hku.hk/docs/S_Ahn_ultrafest.pdf

Ahn & Davidson, 2016, is an abstract, thus not very useful and should be left out.

Halle & Stevens, 1967, is an abstract, thus not very useful and should be left out,. The

Keating, 1984. Page numbers are 35-49, and the text is available here: https://escholarship.org/uc/item/2497n8jq

Line 567 "English"

Lindblom, 1967, is available here: http://www.speech.kth.se/prod/publications/files/qpsr/1967/1967_8_4_001-029.pdf

Maddieson & Gandor, 1976, is availanlde here: https://escholarship.org/uc/item/31f5j8m7

Malisz & Klessa, 2008, is available here: http://www.isle.illinois.edu/sprosig/sp2008/papers/id182.pdf

Line 624 "Phonetics"


# Reviewer 1

Title: Longer vowel duration correlates with greater tongue root displacement: Acoustic and articulatory data from Italian and Polish

Summary – this is an articulatory (ultrasound tongue imaging) study of tongue-root position in the production of CV.CV nonsense words in Italian and Polish, focusing on tongue-root position during V1 and at the onset of C2, while varying whether C2 is a phonemically voiced or voiceless consonant. The main aim of the study is to determine whether tongue root advancement is more extreme during the vowel and at C2 onset when a C2 is voiced than when it is voiceless. It is hypothesized that presence of increased tongue-root advancement when C2 is voiced is a mechanism for increasing the supraglottal cavity and prolonging the transglottal airflow needed to maintain voicing during the C2 closure. Mixed effects modelling is used to identify the impact of C2 voiced/voiceless status (and other factors) on tongue root position at C2 onset. C2 voicing is found to have a significant effect on tongue-root position at C2 onset, with tongue-root onset 0.77mm fronter when C2 is a voiced consonant. A generalised additive mixed model is used to assess the impact of C2 voicing (and other factors) on tongue-root position across V1. The model shows a significant effect of C2 voicing, particularly during the latter half of the vowel. Root advancement is present during the vowel before both voiced and voiceless C2s, but to a greater degree before voiced C2s. A further mixed effects model showed a significant effect of V1 duration on tongue-root advancement, with longer vowels resulting in greater tongue-root advancement. I think it is argued that having a later voiced C2 onset and, concomitantly, a longer preceding vowel, allows for more extreme tongue-root advancement at C2 onset and that therefore the shorter voiced C2 closed phase permits greater expansion of the supralaryngeal cavity to aid transglottal airflow and maintain voicing, while also ensuring that voicing needs to be maintained for a shorter time period.

General comments – the findings of this paper are interesting and seem to show a plausible 2- fold effect of later consonant onset on the maintenance of coronal plosive voicing contrasts. I did find this paper a bit convoluted to read and I found that I didn’t have a clear idea of what the author was trying to say. Additionally, raw differences in tongue-root advancement at voiced and voiceless consonant onset, for all they are statistically significant, are extremely subtle <1mm, while UTI images provide a somewhat blurred image of the tongue surface, and there is potential for error during (automatic) spline fitting due to the fuzziness of the image. I also worry about the measurement protocol itself. The ultrasound probe does not seem to have been angled towards the pharynx and yet the probe angles are quite narrow (71-93°). The example given in FIG. 1 does not contain a hyoid shadow, therefore it is difficult to determine whether movement along the selected radial fan axis shown is really capturing root retraction, or some point further up the back of the tongue. Another issue is that an increase in the value of the point at which the tongue spline intersects this chosen radial fan axis is taken to indicate greater tongue-root advancement, whereas tongue-root advancement should result in a lower value – as the tongue root moves forwards, it should move closer to the origin of the radial fan line. It is possible that the author reversed the radial-fan-line intersect values, as in (Kirkham and Nance, 2017), in which case they should state this explicitly. I believe the issues with measurement can be cleared up with some better figures and some assurances about how the measures were taken and transformed, so I suggest revise and resubmit.

Specific comments:

I think some of the content of the section l67-88 should be moved closer to the beginning of the introduction §A, to give context to the ATR focus of the study i.e. there should be an acknowledgement that there are a range of articulatory strategies associated with plosive voicing and then you can say that you are going to focus on one of these features in this study.

\color{plum}
This suggestion has been implemented in Section I.A. Now the section starts with a general overview of some of the mechanisms for voicing maintenance and then focusses on tongue root advancement.
\color{black}

1-2 "Voiced stops tend to be preceded by longer vowels and produced with a more advanced tongue root than voiceless stops." Citation missing.

\color{plum}
Citations to a long list of publications is given at multiple points within the manuscript, so I think it would not be practical to include them in the abstract.
\color{black}

2 Is "modulated" the right word here? "modified/affected". It doesn’t seem to be the right word, given that the voicing you are discussing is phonemic and not necessarily present at the phonetic level, as you point out later.

\color{plum}
I changed modulated to "modified/affected".
\color{black}

3-4 "in many languages vowels are longer when followed by voiced stops." Examples and citations missing.

\color{plum}
See comment above.
\color{black}

4-6 "Tongue root advancement is known to be an articulatory mechanism which ensures the right pressure conditions for the maintenance of voicing during closure as dictated by the Aerodynamic Voicing Constraint." Citation missing.

\color{plum}
See comment above.
\color{black}

7 "enter in a direct statistical relation". This phrase sounds odd. Rephrase as "have a direct statistical relationship"?, or later in lines 25&26, you say "acoustic duration of the vowel is positively correlated with tongue root position". Can you not say that here?

\color{plum}
Changed to "have a direct statistical relationship".
\color{black}

8-9 "17 speakers of Italian and Polish (in total)"

\color{plum}
Added "in total".
\color{black}

12-13 "in a temporally stable interval". Perhaps it would be better to say "comparatively later closure onset of voiced stops", because it is not clear without context what "stable interval" you mean – C1 release to C2 release.

\color{plum}
Changed as suggested.
\color{black}

12-14 It feels as if these lines belong earlier in the paragraph to make the proposed chain of causal relationships clear, i.e. ATR allows maintenance of voicing for voiced stops, ATR correlates with vowel length.

\color{plum}
Changed as suggested.
\color{black}

16 "characterised" is not the right word here, given that ATR is covert, "associated with"?

\color{plum}
Changed as suggested.
\color{black}

18-19 "a lot of work" citations missing. "aspects", change to "phonetic features"? "phonetic correlates"? Also l19 "relationship", rather than "relation".

\color{plum}
A selection of citations from later sections has been included here.
\color{black}

21 "in an exploratory" – change to "in this exploratory".

\color{plum}
Changed as suggested.
\color{black}

24 "this replicates previous work on tongue root position" – citation(s) missing.

\color{plum}
Citations included.
\color{black}

25 "... indicate that the acoustic duration of the vowel is positively correlated with the tongue root position (at vowel offset/ postvocalic consonant onset)..."

\color{plum}
Changed as suggested.
\color{black}

24-8 There is something oddly circular about this section. Compare to the way you talk about the trade-off between vowel and consonant length in lines 121-2. To avoid a circular argument, I would rephrase as: "Furthermore, the results of this study indicate that a comparatively later C2 onset for voiced consonants results in a longer preceding vowel duration which, in turn, results in greater tongue-root advancement during C2 onset. Both the shorter closed phase of the voiced consonant and the more advanced tongue root, which expands the supra-glottal cavity, have the potential to maintain voicing throughout C2 and preserve the voicing contrast."

\color{plum}
Changed as suggested.
\color{black}

L32 "relative to the front-back dimension" – "across/in the front-back dimension"?

\color{plum}
Fixed.
\color{black}

L33 "This has" – change to "This finding has..."

\color{plum}
Fixed.
\color{black}

L43 I think it would be worth mentioning here that there are other articulatory strategies employed to increase supralaryngeal space, e.g. larynx lowering (Rothenberg, 1967). See first comment above about moving content of lines 67-88 to beginning of introductory section.

\color{plum}
Changed as suggested.
\color{black}

L52 imply

\color{plum}
Fixed.
\color{black}

L57 "closure of a stop" – "closure of a lingual stop".

\color{plum}
Fixed.
\color{black}

L157-58 Rephrase as: "Rothenberg (1967) hypothesized after an informal investigation, that a maximal ballistic expansion movement of the tongue root to increase the size of the lower pharynx would take 70-90ms (Rothenberg, 1967: 99).

\color{plum}
Fixed.
\color{black}

P65-66 "While the tongue body is more involved in labials". Can you be more specific? What does the tongue body do?

\color{plum}
I specified that tongue body lowering is common with labials.
\color{black}

L92 "it can be" -> "it is sometimes"

\color{plum}
Fixed.
\color{black}

L104 typo "to study of the"

\color{plum}
Fixed.
\color{black}

L105-6 "given their reported differences in magnitude/presence of the effect and the relative ease of comparison." – you need to unpack this a bit.

\color{plum}
I've expanded with "Moreover, the segmental phonologies of these languages facilitate the design of sufficiently comparable experimental material (see Coretta 2018 for a more thorough discussion)".
\color{black}

L104-106 I suggest this edit: "Italian and Polish offer an opportunity to study of the articulatory aspects of the voicing effect, given that the former has been consistently reported as a voicing- effect language, while voicing effect in the latter is more complex, with some studies finding an effect and others not."

\color{plum}
Changed.
\color{black}

L110-12 What were the mean voicing differences for the two languages? Were they comparable?

\color{plum}
I've added details on the raw mean differences of the voicing effect in the two languages and mentioned that such difference is not significant in the linear model.
\color{black}

L112-114 Can you explain further? "The high degree of intra-speaker variation, backed up by statistical modelling, also indicates that these languages possibly behave similarly in regards to the voicing effect."

\color{plum}
I've corrected "intra-speaker" with "inter-speaker" and expanded on this statment by indicating that independent of language speakers show a range of possible magnitudes of the effect.
\color{black}

L124 Can you come up with a better section heading?

\color{plum}
Changed to "Rationale of the current study".
\color{black}

L126 Citations missing.

\color{plum}
I inserted here some of the citations from above for clarity.
\color{black}

L125-131 Suggested rephrasing "Previous research has established that longer preconsonantal vowel durations and greater tongue root advancement are associated with voicing in postvocalic plosives. We know that voicing during plosive closure can be sustained by advancing the tongue root during the production of voiced plosives and that tongue root advancement probably begins before the closure onset (i.e. during the preceding vowel). We also know that vowels followed by voiced plosives tend to be longer than vowels followed by voiceless plosives. Acoustic analysis of the current dataset confirmed an apparent compensatory relationship between the duration of the plosive closure and the duration of the preceding vowel; the shorter the plosive closure, the longer the preceding vowel."

\color{plum}
Rephrased as suggested.
\color{black}

L133 "insights on the link" – "insights into the link", "between closure" – "between closure duration"?? or "link between closure and vowel durations".

\color{plum}
Changed.
\color{black}

L134 I am not comfortable with the term "modulates". I think it implies a causal relationship that has not yet been proved. Can you say "correlates"? or "covaries with"?

\color{plum}
Changed.
\color{black}

L135-6 Suggested rephrasing "resulting in a three-way relationship between stop consonant duration, vowel duration and tongue-root advancement."

\color{plum}
Changed.
\color{black}

L136-8 "More specifically, the timing of the closure onset within the release-to-release interval decides the duration of the vowel..." Again, is this not a given, see comments l27-28.

\color{plum}
Yes The sentence now says "More specifically, the timing of the closure onset within the release-to-release interval determines not only the duration of the vowel and that of the closure (as discussed in Coretta 2018), but also the degree of tongue root advancement at V1 offset/C2 onset."
\color{black}

L159 Can you change to "TELEMED Echo Blaster 128 unit, with a C3.5/20/128Z-3 ultrasonic transducer (20mm radius, 2-4 MHz)." Grouping these items together makes sense. Otherwise you are just writing a random list of items that you used in your recording set up.

\color{plum}
Changed.
\color{black}

L160-1 The pre-amp is part of the audio recording set up, not the ultrasound recording system. You need to move it further down the list of equipment, i.e. "a Movo LV4-O2 Lavalier microphone with a FocusRight Scarlett Solo pre-amplifier."

\color{plum}
Changed.
\color{black}

L163 Please gloss "sub-mental triangle", and in what way was the probe "aligned with the midsagittal plane"?

\color{plum}
Now the line reads "The ultrasonic probe was placed in contact with the flat area below the chin, aligned along the participant's mid-sagittal plane so that the mid-sagittal profile of the tongue could be imaged."
\color{black}

L169 "by means of a synchronisation signal produced by the ultrasound unit and amplified by the P-Stretch unit.

\color{plum}
Changed.
\color{black}

P170-2 Does this mean that the ultrasound recording settings varied in every recording session, or between the Italian and Polish recording settings? If the latter, can you give the separate setting by language, rather than a range. Can you also say why you think this variation won’t affect what you are measuring? The range of probe angles seem quite narrow.

L184 "explore timing/ articulatory? differences in the closing gesture of voiceless and voiced stops..."

\color{plum}
Changed.
\color{black}

L202-9 Can you add a figure showing an example of annotation?

\color{plum}
Added.
\color{black}

L216-8 "Tongue root displacement was thus calculated as the displacement of the fitted spline along a selected vector." Based on the figure provided (FIG. 1) I am not convinced that tongue- root advancement is being captured. The probe angle is very narrow. The tongue root does not appear to have been imaged, as there is no visible hyoid shadow. I am not sure that a measure of displacement along a radial fan axis shown would capture tongue-root advancement. Could you provide information on the range of radial axes that were used as measurement axes?

\color{plum}
The hyoid shadow is not visible because during UTI set up the angle is adjusted so that the leftmost edge of the ultrasound image corresponds to the edge of the shadow (this is necessary for the automatic tracker to work more consistently). It is true that an ideal measure of tongue root position should be taken along a vector which is perpendicular to the movement. Such vector could for example be chosen so that it is parallel to the genioglossus tendon, which can be made visible on UTI images with the right settings. Unfortunately, the tendon was not always visible in the data. Moreover, since the data was collected without tongue root position in mind, I did not make sure to see whole of the actual tongue root all the time. Note though that the measured displacement must be related to tongue root displacement, since the fan-lines from which it was obtained were always more posterior than the fan-lines which corresponded to velar occlusion. This is the best I could do with the data at hand, although I understand it is not perfectly ideal. I'm happy to mention these issues in the paper if the reviewers think the paper might benefit from it.
\color{black}

L218-20 Can you specify the range of radial axes (i.e. their numbers) that were used as measurement axes across all speakers?

\color{plum}
Added.
\color{black}

L225 Remove the word "real".

\color{plum}
Removed.
\color{black}

L225 I am still confused about why there was no standard frame rate, although I don’t think it will make a difference to the results given that the minimum frame rate is 43fps.

\color{plum}
I added a footnote "The frame rate is adjusted by the system depending on other settings, so there is no standard frame rate."
\color{black}

L255 "...scaled (z-scored) tongue root position."

\color{plum}
Added.
\color{black}

L257-258 I might have missed this part of the data transformation. Fig. 2’s caption says that "Higher values indicate advancement." and appears to show greater ATR values at closure onset where a voiced consonant follows. I would have expected the opposite if advanced tongue root is being measured. With increased ATR, the tongue-root section of the tongue spline should intersect the radial fan axis closer to its origin, obtaining a smaller value. Kirkham and Nance (2017) reversed the sign of the z-scored tongue root distance measures, so that greater distance scores were associated with greater ATR (p71). Was that also carried out here? If it was, I think you should be explicit about that, rather than just saying you followed Kirkham and Nance’s method.

\color{plum}
I've expanded by saying that the sing has been flipped to facilitate interpretation (greater values = greater tongue root advancement).
\color{black}

282 "A second linear mixed regression was fitted to tongue root position ?at V1offset/C2onset?..."

\color{plum}
Yes. I have now specified that the time point is V1 offset/C2 onset.
\color{black}

288-289 "V1 duration and tongue root position ?at V1offset/C2onset?..."

\color{plum}
Yes. I have now specified that the time point is V1 offset/C2 onset.
\color{black}

378 Change to "It is worth briefly discussing..."

\color{plum}
Changed
\color{black}

384 phonemic symbol missing

\color{plum}
Fixed.
\color{black}

383-388 Perhaps this needs to be rephrased. It looks as if you are implying that the acoustic difference between /e/ and /ɛ/ is entirely due to differences in tongue-root position. Also phonemic contrast can occur due to quite subtle acoustic cues, so phonemic difference does not necessarily mean a huge difference in acoustics or underlying articulation.

390-3 See comments l57-58 Rothenberg’s estimated duration for tongue-root advancement.

\color{plum}
Rephrased as "If a maximal ballistic forward movement of the tongue root takes between 70 and 90 ms as suggested by the informal investigation by Rothenberg (1967), we can calculate the maximum displacement plausible to be between 4.55 to 5.85 mm (0.065 mm times 70–90 ms).".
\color{black}

393-4 Does this refer to: "Lacking further evidence we might assume it is possible to produce a vertical elongation of the pharynx in plosive production of about 0.5cm." (Rothenberg 1967: 98)?

\color{plum}
This refers to a few lines above that: "If we consider the lateral and posterior walls of the pharynx to be held fixed, the anterior-posterior dimension of the pharynx can be increased by a forward motion of the larynx and/or base of the tongue. Forward motions of the base of the tongue of the order of magnitude of 0.5 cm have been reported by PERKELL (1965). The main activation is most likely supplied by the most inferior-posterior fibers of the genioglossus muscle to the base of the tongue, the geniohyoid muscles, and the infrahyoid muscles. The forward motion of the anterior wall of the pharynx might well be more of a pivoting around an axis somewhere near the cricoid cartilage than a uniform forward motion; however, it is difficult to find empirical evidence bearing on this question."
\color{black}

FIG. 6 caption "tornge". Why are there two of each plot?

\color{plum}
Fixed. The plot duplication was a coding error and it's now fixed.
\color{black}

L431 "shows", or "these plots show"

\color{plum}
Fixed.
\color{black}

L442 "The mean difference in tongue root position (at the onset of?) voiceless vs. voiced stops..."

\color{plum}
Yes, added "at the onset of".
\color{black}

L464 and 465 citations missing.

\color{plum}
I inserted here some of the citations from above for clarity.
\color{black}

Ll468 "Similarly to what (was) previously found for English (citation)..."

\color{plum}
I inserted here some of the citations from above for clarity and I added "was".
\color{black}

L485 "replicate" -> "are replicable"

\color{plum}
Changed.
\color{black}

# Reviewer 2

The aim of this study is to show the relation between longer vowel duration and tongue root advancement (which is related to the voicing of the following stop). This manuscript contains some very interesting and original/novel data, which was not studied before. Also, it has a potential to be extended to other contexts as well as other languages. However, there are some concerns about the interpretation of the results. Here are my main concerns:

1. The result the author argues to be the main point of the manuscript (how a longer vowel duration corresponds to greater tongue root advancement) is not very well explained. The author shows some results (Figure 5), but does not explain enough why tongue root advancement is related to the longer vowel duration. This study explains why tongue root should be more advanced at the vowel offset of voiced stops, but not necessarily why more tongue root advancement is found with the longer vowel duration. The only part that explains the relation between the vowel duration and tongue root advancement is line 333 (p.21), but more explanations will be necessary—considering the main argument (and the title) of this paper is how longer vowel duration correlates with greater tongue root advancement)—or I wonder if the title purposefully used the word 'displacement' instead of 'advancement'.

2. Also, I'm concered about inter-speaker variation. In fact, out of 17 speakers, 7 speakers did not show more tongue root advancement at closure onset of voiced stops (Figure 7 and Figure 8). Considering the difficulty of analyzing everyone's data collectively when doing an ultrasound study (due to the differences in each speaker's anatomy), the statistical model(s) the author reports in the manuscript can be questionable especially with the high variability found among speakers.

3. On p. 19, Figure 5, it shows that when the vowel is longer, the tongue root position at the onset of the vowel is more retracted. The reason for this seems very important, but it's not explained why that's the case other than saying "the trajectory curvature increases with vowel duration (line 302).

4. The author reports the data on two different languages, Italian and Polish, but it is less clear why these two languages are studied, especially since as the author argues, two languages did not show any difference. Also, since the data were collected in the UK, it's worth mentioning the length of stay in the UK and English proficiency of each speaker. It is well known that English voiced/voiceless stops behave differently from other languages, so English may have some effects on participants' native languages. Regarding the materials used for the data collection, I wonder if there was any effect of including the real words. Also, why /b, p/ was not included (at least for a comparison to other lingual consonants?)

And, here are some parts I found unclear/need more explanations:

p. 3, 2nd paragraph: it's unclear what the purpose of the last sentence is.

\color{plum}
This sentence clarifies the use of "active gesture" in the paper, to avoid confusion with the more general reading of active gesture as a gestures implemented for a specific purpose.
\color{black}

p. 13, line 235: Generalized additive mixed models (GAMMs). Including more explanations on this model will be very helpful to understand how this model's prediction works in Section III B and Fig. 3.

p. 20, line 330: "Said correlation exists independent of the voicing status of the consonant following the vowel" --> I especially found it difficult to understand the paragraph including this sentence and the following two paragraphs, and I believe these paragraphs are main arguments of this manuscript. More specifically, why do we see a greater tongue root advancement when the vowel is longer? Is it simply because voiced stops show more tongue root advancement and a longer vowel duration? More importantly, why do we see a greater curvature in longer vowels? Why does a longer vowel show a more retracted tongue root at its vowel onset?

p. 21, 3rd paragraph: this paragraph suddenly mentions speech rate and its paradox, and it is not very clear what the argument here is. Considering inter-speaker variation. I think at least with speech rate and tongue root advancement of vowel onset mentioned here, it may be worth looking at individual speaker's results instead of just use speech rate as a factor in the statistical model.

p. 23-24, Section IV B: I think this section can be either condensed or deleted since estimates of tongue root displacement will be highly variable depending on speaker. Since (1) Speaker variation was reported in this study, (2) only two languages are studied, and (3) the author mentions that "the correlation between tongue root position and vowel duration needs to be replicated by expanding the enquired contexts to other types of consonants and vowels, and with other languages" (p. 24, line 410), I recommend to condense this section.

\color{plum}
It is generally desirable to discuss in some details the estimates of the sought effects, as recommended by recent literature on statistical power. It is true that the estimates will be highly variable depending on speaker, but since such estimates refer to a population of speakers it can still be useful, for example, for the determination of Bayesian priors in future work. The discussion of the estimates also links the results of this study back to theoretical argumentations from previous work, and it thus constitute a grounding point.
\color{black}

There are some parts where the tables and figures may be necessary and/or more explanations on figures may be helpful:

First of all, in the results, tables with these acoustic data are necessary: e.g. mean V1 duration, mean speech rate, mean closure-to-closure interval

p. 11, line 206: what is "higher formant"? Either give a very specific example, or provide a sample spectrogram.

\color{plum}
I have specified what is meant by "higher formants structure", taken from Machač 2009.
\color{black}

Figure 1: please indicate the front and back of the tongue

\color{plum}
Added indication of back/front.
\color{black}

Figure 2: How was the data of each speaker scaled? Also, it will be helpful if this figure is in color.

\color{plum}
I've added that those are z-scores and I made the figure in colour.
\color{black}

Figure 4: Maybe using color and indicating voiced/voiceless stops may be helpful.

\color{plum}
I've added colour by vowel in the plot. The model from which the regression line are obtained does not contain C2 voicing. This is because a separate model indicated that voicing nor its interaction with vowel duration is significant, so it was dropped from the final model. I've added a mention to this in Section III.C.
\color{black}

Figure 5: Why 145ms was used instead of 150ms? (while other V1 duration values used are 50, 100, and 200). Also, why 145 ms and 200 ms starts from more retracted tongue root position? It's not explained in the text.

\color{plum}
The figure has now 150 ms rather than 145 ms. I have also increased the number of basis functions in the smooth for vowel duration, since I realised it was too low according to "gam.check()". This has partially change the starting values for the different vowel durations, so that now there is an increase in starting tongue root position with the exception of 200 ms which decreases. I do not know why this is the case. I've added in the text: "I have no explanation for why the advancement of the root seemingly increases with increasing vowel duration except when the duration goes from 150 to 200 ms."
\color{black}

The following other minor suggestions are noted:

p. 2, line 18: "a lot of work has been done on each of these aspects separately,..." but actual references are not mentioned; also, line 24—references

\color{plum}
I have added here some of the references from later sections for clarity.
\color{black}

p. 3, line 39: "Aerodynamic Voicing Constraint": since this concept is mentioned as a very important concept of this manuscript, more detailed information about it will be helpful

\color{plum}
I am not sure what is asked here. The constraint simply states that there must be a positive trans-glottal air pressure differential, as discussed in lines 33-42.
\color{black}

p. 4, line 58: ...root "advancement" about....

\color{plum}
The sentence has been rephrased as suggested by one of the other reviewers and moved at the beginning of the paragraph.
\color{black}

p. 4, line 72: typo--'longer' --> 'shorter'

\color{plum}
Fixed.
\color{black}

p. 4, line72-73: please indicate what language(s) each paper worked on

\color{plum}
Added.
\color{black}

p. 5, line 79: (Ahn, 2018)--> Ahn (2018)

\color{plum}
Fixed.
\color{black}

p. 5, line 98: here as well, please specify what language(s) each paper worked on

\color{plum}
Added.
\color{black}

p. 6, line 106: "relative ease of comparison" --> not sure what exactly it means

\color{plum}
I've explained this now "Moreover, the segmental phonologies of these languages facilitate the design of sufficiently comparable experimental material (see Coretta 2018 for a more thorough discussion)."
\color{black}

p. 6, line 111: "the stressed vowels of disyllabic words"--> indicate which vowel is stressed

\color{plum}
Stress is indicated with a diacritic although it is not properly rendered due to restrictions of the submission system, but it should be fixed in the final form. I have now specified that the stressed vowel is the first.
\color{black}

p. 8, line 147: missing '.' After Verbania (Italy)

\color{plum}
Fixed.
\color{black}

p. 10, line 182: "high and front vowels usually produce less tongue displacement from and to a stop consonant" --> reference(s)?

p. 13, line 231: the calculated speech rate values—here, please explain how the values were calculated

\color{plum}
I have included here a condensed version of the formula from above for clarity.
\color{black}

p. 13, line 235: Generalised additive mixed models—since it's first time mentioning this model, show the abbreviation here (GAMMs?); line 238: GAMs--> GAMMs??

\color{plum}
Added abbreviation and fixed line 238.
\color{black}

P. 21, line 349 and 351: Two "howevers" are confusing. maybe change the second however to "nevertheless"?

\color{plum}
I have fixed the repetition of "however" by rephrasing.
\color{black}

P. 22, line 357: 'previous work' > reference(s)

\color{plum}
I have added a cross-reference to the patterns described in the Introduction section.
\color{black}

P. 23, line 384: a +ATR vowel, a -ATR vowel,

\color{plum}
Fixed.
\color{black}

P. 23, line 384: also missing IPA symbol in the second / /

\color{plum}
Fixed.
\color{black}

P. 25, Figure 6: typo (torngue--> tongue)

\color{plum}
Fixed.
\color{black}

P. 26, line 447: 11 speakers--> 10 speakers?

\color{plum}
Fixed.
\color{black}

# Reviewers' Responses to Questions

Is the manuscript of good scientific quality, free from errors, misconceptions or ambiguities; does it present original work; and does it contain sufficient new results, new applications or new developments of reasonable enough significance to warrant its publication in JASA? Please indicate in your report (in detailed comments, below) any points which are objectionable or which need attention.

Reviewer 1: There are some ambiguities and potential issues with measurement that need to be addressed.

Reviewer 2: 1. The manuscript contains some very interesting and original/new data. However, there are some concerns about the interpretation of the results. The result the author argues to be the main point of the manuscript (how a longer vowel duration corresponds to greater tongue root advancement) is not very well explained throught the manuscript. The author shows some results, but does not explain why that is the case. Also, I’m concered about inter-speaker variation. In fact, out of 17 speakers, 7 speakers did not show more tongue root advancement at closure onset of voiced stops (Figure 7 and Figure 8). Considering the difficulty of analyzing different speakers’ data in one statistical model when doing an ultrasound study (due to the differences in each speaker’s anatomy), the statistical model(s) the author reports in the manuscript can be questionable especially with the high variability found among speakers.

2. On p. 19, Figure 5, it shows that when the vowel is longer, the tongue root position at the onset of the vowel is more retracted. The reason for this seems very important and worth some attention. However, the author does not explain why that’s the case other than saying "the trajectory curvature increases with vowel duration (line 302).

3. There aren’t adquate explanations on why tongue root advancement will be related to the longer vowel duration. This study explains why tongue root should be more advanced at the vowel offset of voiced stops, but not necessarily why more tongue root advancement is found with the longer vowel duration. The only part that explains the relation between the vowel duration and tongue root advancement is line 333 (p.21), but that part is not very well explained.

3. The author reports the data on two different languages, Italian and Polish, but it is less clear why these two languages are studied, especially since as the author argues, two languages did not show any difference.

4. Since the data were collected in the UK, it's worth mentioning the length of stay in the UK and English proficiency of each speaker. It is well known that English voiced/voiceless stops behave differently from other languages, so English may have some effects on participants’ native languages.

5. Regarding the materials used for the data collection, including both nonce words and real words may not have been the best choice. I wonder if there was any effect of including the real words.

6. Also, this is not the crucial point, but some errors/typos in terms of writing sometimes makes it difficult to understand the writer's intention sometimes. (e.g. p. 4, line 72, 'longer' should be 'shorter', which is very important). More detailed line-by-line comments will be provided to the author.

\par\noindent\rule{\textwidth}{0.4pt}

Is JASA an appropriate journal in which to present this work? In this regard, please consider carefully the commitment of JASA to publish work that is within the scope of Acoustics. Does the content of the manuscript, including terminology and the references cited, meet this criterion?

Reviewer 1: Yes, this work is appropriate for publication in JASA.

Reviewer 2: This work includes both articulatory and acoustic data, which I believe is suitable to be published in JASA. Also, it includes some important phonetic work (both articulatory and acoustic) in the field as relevant references.

\par\noindent\rule{\textwidth}{0.4pt}

Is the manuscript a clear, concise, reasonably self-contained presentation of the material, giving adequate references to related work? Is the English satisfactory? Please indicate needed changes in your report.

Reviewer 1: The central argument of the manuscript could be made clearer. The style of the manuscript can be overly complex.

Reviewer 2: 1. The manuscript contains interesting and new results, but the writing itself is not the easiest to read. There were some sections I had to read several times to understand. The statistical models in the results will be benefited by more explanations, and the discussion section is also not very clear. More detailed comments are below:

p. 3, 2nd paragraph: it's unclear what the purpose of the last sentence is

p. 4, 2nd paragraph: the typo in line 72 ('longer' should be 'shorter') made the whole paragraph (and the following paragraphs) difficult to understand

p. 13, line 235: Generalized additive mixed models (GAMMs). It is very difficult to understand what this model does, and how this model’s prediction works in Section III B, which makes it difficult to understand Fig. 3.

p. 20, line 330: "Said correlation exists independent of the voicing status of the consonant following the vowel" --> this part made the whole paragraph and the manuscript's argument a bit confusing. I also found it difficult to understand the paragraph including this sentence and the following paragraph.

p. 21, 3rd paragraph: this paragraph suddenly mentions speech rate and its paradox, and it is not very convincing, especially considering individual variation. I think at least with speech rate and tongue root advancement of vowel onset, it may be worth looking at individual speaker's results. It may not be best to use speech rate just as a factor in the statistical model.

p. 23-24, Section IV B: I think this section can be either condensed or deleted.

p. 25, Section IV C: I actually think individual differences are very important. Since some speakers show very different patterns, I think combining everyone's data at once and running the statistical model may not be ideal. In fact, Figure 7 shows out of 17 speakers, 7 speakers either didn't show the expected results or showed the opposite results.

2. This manuscript gives some references to related work, but there are some parts where references are missing when necessary. More detailed comments are below:

p. 2, line 18: "a lot of work has been done on each of these aspects separately,..." but actual references are not mentioned

p. 3, line 39: "Aerodynamic Voicing Constraint": since this concept is mentioned as a very important concept of this manuscript, more detailed information about it will be helpful

p. 4, line72-73: please indicate what language(s) each paper worked on

p. 5, line 98: here as well, please specify what language(s) each paper worked on

p. 10, line 182: "high and front vowels usually produce less tongue displacement from and to a stop consonant" --> reference(s)?

\par\noindent\rule{\textwidth}{0.4pt}

Are the tables and figures clear and relevant, and are the captions adequate? Are there either too many or too few? If any of the figures are in color, is the color essential for conveying the scientific point?

Reviewer 1: Tables and figures are clear and relevant. Captions are adequate. More figures could be included to illustrate measurement.

Reviewer 2: Some figures are not easy to understand, and there are some parts where the tables and figures are necessary.

First of all, in the results, tables with these acoustic data are necessary: mean V1 duration, mean speech rate, mean closure-to-closure interval

p. 11, line 206: what is "higher formant"? Either give a very specific example, or provide a sample spectrogram

Figure 1: please indicate the front and back of the tongue

Figure 2: this figure is difficult to understand. How was the data of each speaker scaled? Also, it will be helpful if this figure is in color.

Figure 4: I don’t understand this figure—maybe using color and indicating voiced/voiceless stops may be helpful.

Figure 5: Why 145ms was used instead of 150ms? (while other V1 duration values used are 50, 100, and 200) Also, why 145 ms and 200 ms starts from the backer tongue root position? It's not explained in the text.

\par\noindent\rule{\textwidth}{0.4pt}

If Supplementary material was submitted, is it relevant to the manuscript and should it be deposited in the Supplemental Depository for reference to the manuscript?

Reviewer 1: NA

Reviewer 2: N/A

\par\noindent\rule{\textwidth}{0.4pt}

Does the paper make effective use of journal space, or are parts unnecessary, unimportant, or subject to condensation? If so, which?

Reviewer 1: I believe the manuscript could be shortened and made more concise, particularly the discussion section.

Reviewer 2: p. 23, Section IV B can be condensed/removed since estimates of tongue root displacement will be highly variable depending on speaker. Since (1) Speaker variation was reported in this study, (2) only two languages are studied, and (3) the author mentions that "the correlation between tongue root position and vowel duration needs to be replicated by expanding the enquired contexts to other types of consonants and vowels, and with other languages" (p. 24, line 410), I recommend to condense this section.

\par\noindent\rule{\textwidth}{0.4pt}

Is the title appropriate and the abstract adequate for verbatim reproduction in abstract journals? IMPORTANT: The lead paragraph should advertise the main points of the article and must describe in terms accessible to the general reader the context and significance or the research problem studied and the importance of the results.

Reviewer 1: Yes, the title is appropriate. There are some parts of the abstract that need to be edited to improve clarity.

Reviewer 2: I recommend the title to include that "longer vowel duration" (only) refers to the "preceding" vowel duration (not necessarily the following). I also think the word 'advancement' will be more suitable than 'displacement'. On the other hand, I wonder if the title purposefully used the word ‘displacement’ instead of ‘advancement’.

In the abstract, it will be more informative if the author includes at least a few references (e.g. the Aerodynamic Voicing Constraints--> Ohala, 2011).

The results in the abstract can be more clearly written, especially the last three sentences.

Vowel duration and tongue root position at vowel offset are positively correlated. Longer vowel durations correspond to greater tongue root advancement: I wonder if this should be the main point of this study, as I pointed out throughout my review
'the later closure onset of voiced stops within a temporally stable interval' needs more explanation because 'shorter closure duration' of voicing stop is not mentioned in the previous sentences.
